"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Role = { role_key: string; name: string; description: string | null; hierarchy_level: number };
type Permission = { permission_key: string; name: string; description: string | null; permission_type: string; screen_key: string | null; route_path: string | null; category: string | null; sort_order: number };
type Member = { user_id: string; email: string | null; role: string; role_key: string; hierarchy_level: number; parent_user_id: string | null; created_at: string; manageable: boolean; overrides: Record<string, boolean> };
type ScopeItem = { id: string; name: string; code: string | null };
type ScopeCatalog = Record<string, ScopeItem[]>;
type ScopeRow = { scope_type: string; scope_id: string };

const scopeTypes = [["legal_entity","الكيانات القانونية"],["branch","الفروع"],["department","الإدارات"],["cost_center","مراكز التكلفة"],["region","المناطق"],["product","المنتجات"],["project","المشروعات"]] as const;

export default function TeamPage() {
  const supabase = getSupabaseBrowserClient();
  const [members,setMembers]=useState<Member[]>([]),[roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]);
  const [actorLevel,setActorLevel]=useState(0),[actorPermissions,setActorPermissions]=useState<Set<string>>(new Set()),[canManage,setCanManage]=useState(false),[isSystemAdmin,setIsSystemAdmin]=useState(false);
  const [error,setError]=useState(""),[busy,setBusy]=useState(false),[showInvite,setShowInvite]=useState(false),[email,setEmail]=useState(""),[inviteRole,setInviteRole]=useState(""),[inviteLink,setInviteLink]=useState("");
  const [editing,setEditing]=useState<Member|null>(null),[saving,setSaving]=useState(false),[scopeCatalog,setScopeCatalog]=useState<ScopeCatalog>({}),[actorScopes,setActorScopes]=useState<ScopeRow[]>([]),[editingScopes,setEditingScopes]=useState<ScopeRow[]>([]),[scopeLoading,setScopeLoading]=useState(false);
  const [transferEmail,setTransferEmail]=useState(""),[transferBusy,setTransferBusy]=useState(false);

  const orgId=()=>typeof window!=="undefined"?window.sessionStorage.getItem("activeOrganizationId"):null;
  const manageableRoles=useMemo(()=>roles.filter(r=>r.hierarchy_level<=actorLevel),[roles,actorLevel]);
  const manageablePermissions=useMemo(()=>permissions.filter(p=>actorPermissions.has(p.permission_key)),[permissions,actorPermissions]);
  const screenPermissions=useMemo(()=>manageablePermissions.filter(p=>p.permission_type==="screen"),[manageablePermissions]);
  const actionPermissions=useMemo(()=>manageablePermissions.filter(p=>p.permission_type!=="screen"),[manageablePermissions]);
  const canViewScopes=actorPermissions.has("data_scope.view"),canManageScopes=actorPermissions.has("data_scope.manage");

  async function load(){
    const id=orgId(); if(!id)return; setError("");
    const [membersResult,rolesResult,permissionsResult,accessResult,manageResult,catalogResult,actorScopeResult]=await Promise.all([
      supabase.rpc("get_team_members",{p_organization_id:id}),supabase.from("organization_roles").select("role_key,name,description,hierarchy_level").eq("organization_id",id).order("hierarchy_level",{ascending:false}),
      supabase.from("organization_permissions").select("permission_key,name,description,permission_type,screen_key,route_path,category,sort_order").order("sort_order"),supabase.rpc("get_my_org_access",{p_organization_id:id}),
      supabase.rpc("has_org_permission",{p_organization_id:id,p_permission_key:"manage_users"}),supabase.rpc("get_team_data_scope_catalog",{p_organization_id:id}),
      supabase.rpc("get_team_member_data_scopes",{p_organization_id:id,p_user_id:typeof window!=="undefined"?window.sessionStorage.getItem("currentUserId"):null})
    ]);
    if(membersResult.error){setError(membersResult.error.message);return;} if(rolesResult.error){setError(rolesResult.error.message);return;} if(permissionsResult.error){setError(permissionsResult.error.message);return;} if(accessResult.error){setError(accessResult.error.message);return;}
    const roleRows=(rolesResult.data??[]) as Role[];
    setMembers((membersResult.data??[]) as Member[]);setRoles(roleRows);setPermissions((permissionsResult.data??[]) as Permission[]);
    const access=(accessResult.data??[]) as Array<{user_id:string;hierarchy_level:number;permission_key:string;granted:boolean;role_key:string}>;
    setActorLevel(access[0]?.hierarchy_level??0);setIsSystemAdmin(access[0]?.role_key==="company_admin");setActorPermissions(new Set(access.filter(x=>x.granted).map(x=>x.permission_key)));setCanManage(Boolean(manageResult.data));
    if(!catalogResult.error&&catalogResult.data)setScopeCatalog((catalogResult.data as ScopeCatalog)??{});if(!actorScopeResult.error)setActorScopes((actorScopeResult.data??[]) as ScopeRow[]);
    if(!inviteRole){const first=roleRows.filter(r=>r.hierarchy_level<=(access[0]?.hierarchy_level??0))[0];if(first)setInviteRole(first.role_key);}
  }
  useEffect(()=>{void load()},[]);

  async function invite(){const id=orgId();if(!id||!email.trim()||!inviteRole)return;setBusy(true);setError("");try{const {data,error:e}=await supabase.rpc("create_team_invite_link",{p_organization_id:id,p_email:email.trim(),p_role_key:inviteRole});if(e)throw new Error(e.message);if(!data?.ok||!data?.token)throw new Error(data?.error||"تعذر إنشاء رابط الدعوة");setInviteLink(`${window.location.origin}/invite/${data.token}`);setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء رابط الدعوة")}finally{setBusy(false)}}
  async function changeRole(){if(!editing||!editing.manageable)return;const id=orgId();if(!id)return;setSaving(true);setError("");const {error:e}=await supabase.rpc("set_team_member_role",{p_organization_id:id,p_user_id:editing.user_id,p_role_key:editing.role_key});setSaving(false);if(e){setError(e.message);return}setEditing(null);await load()}
  async function togglePermission(permission:string,granted:boolean){if(!editing||!editing.manageable)return;const id=orgId();if(!id)return;setSaving(true);setError("");const {error:e}=await supabase.rpc("set_team_member_permission_override",{p_organization_id:id,p_user_id:editing.user_id,p_permission_key:permission,p_granted:granted});setSaving(false);if(e){setError(e.message);return}setEditing({...editing,overrides:{...editing.overrides,[permission]:granted}});await load()}
  async function openEditor(member:Member){setEditing(member);if(!canViewScopes)return;const id=orgId();if(!id)return;setScopeLoading(true);setError("");const {data,error:e}=await supabase.rpc("get_team_member_data_scopes",{p_organization_id:id,p_user_id:member.user_id});setScopeLoading(false);if(e){setError(e.message);setEditingScopes([]);return}setEditingScopes((data??[]) as ScopeRow[])}
  function actorAllowedScopeIds(scopeType:string){const own=actorScopes.filter(s=>s.scope_type===scopeType).map(s=>s.scope_id);return own.length?new Set(own):null}
  async function toggleScope(scopeType:string,scopeId:string,granted:boolean){if(!editing||!editing.manageable||!canManageScopes)return;const id=orgId();if(!id)return;const ownAllowed=actorAllowedScopeIds(scopeType);if(granted&&ownAllowed&&!ownAllowed.has(scopeId)){setError("لا يمكنك منح عضو نطاقًا أوسع من النطاق المسموح لك به.");return}setSaving(true);setError("");const {error:e}=await supabase.rpc("set_team_member_data_scope",{p_organization_id:id,p_user_id:editing.user_id,p_scope_type:scopeType,p_scope_id:scopeId,p_granted:granted});setSaving(false);if(e){setError(e.message);return}setEditingScopes(prev=>granted?[...prev.filter(x=>!(x.scope_type===scopeType&&x.scope_id===scopeId)),{scope_type:scopeType,scope_id:scopeId}]:prev.filter(x=>!(x.scope_type===scopeType&&x.scope_id===scopeId)));await load()}
  async function removeMember(userId:string){const id=orgId();if(!id||!confirm("هل تريد إزالة هذا العضو من الشركة؟"))return;setSaving(true);setError("");const {error:e}=await supabase.rpc("remove_team_member",{p_organization_id:id,p_user_id:userId});setSaving(false);if(e){setError(e.message);return}setEditing(null);await load()}
  async function transferOwnership(){const id=orgId();const target=transferEmail.trim();if(!id||!target||!isSystemAdmin)return;if(!confirm(`سيتم نقل مدير النظام إلى ${target} وستفقد حسابك صلاحية مدير النظام. هل تريد المتابعة؟`))return;setTransferBusy(true);setError("");const {error:e}=await supabase.rpc("transfer_system_admin_ownership",{p_organization_id:id,p_email:target});setTransferBusy(false);if(e){const map:Record<string,string>={TARGET_USER_NOT_FOUND:"البريد الإلكتروني غير مرتبط بحساب مستخدم.",TARGET_USER_MUST_BE_COMPANY_MEMBER:"يجب أن يكون المستخدم عضوًا في الشركة أولًا.",TARGET_ALREADY_SYSTEM_ADMIN:"هذا المستخدم هو مدير النظام بالفعل.",ONLY_CURRENT_SYSTEM_ADMIN_CAN_TRANSFER_OWNERSHIP:"فقط مدير النظام الحالي يستطيع نقل الملكية."};setError(map[e.message]??e.message);return}setTransferEmail("");alert("تم نقل ملكية مدير النظام بنجاح. سيتم تحديث صلاحيات حسابك الآن.");window.location.assign("/workspace")}
  const roleName=(key:string)=>roles.find(r=>r.role_key===key)?.name??key;
  const effectivePermission=(member:Member,p:string)=>member.overrides[p]===true;
  const effectiveScope=(t:string,id:string)=>editingScopes.some(s=>s.scope_type===t&&s.scope_id===id);
  const hasAnyScope=(t:string)=>editingScopes.some(s=>s.scope_type===t);

  return <main className="min-h-screen bg-[#f7f8fa] text-[#172033]" dir="rtl">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><Link href="/workspace" className="text-sm font-semibold text-slate-500">العودة لمساحة العمل</Link><div className="text-right"><p className="text-xs font-bold tracking-[.14em] text-slate-400">IDENTITY & ACCESS</p><h1 className="mt-1 font-bold text-slate-950">الفريق والصلاحيات</h1></div></div></header>
    <section className="mx-auto max-w-[1500px] px-4 py-7 sm:px-6 lg:px-8">
      <div className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-bold text-slate-400">RBAC · HIERARCHY · LEAST PRIVILEGE</p><h2 className="mt-2 text-2xl font-bold text-slate-950 sm:text-3xl">إدارة أعضاء الشركة والصلاحيات</h2><p className="mt-3 text-sm leading-7 text-slate-500">كل مستخدم يبدأ بصلاحيات صريحة فقط. يمكنك إدارة من هم تحت مستواك، وتظهر لك فقط الأدوار والصلاحيات التي تملكها أنت.</p></div><button disabled={!canManage} onClick={()=>{setInviteLink("");setShowInvite(true)}} className="w-full rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white disabled:opacity-40 sm:w-auto">إنشاء رابط دعوة</button></div>
      {error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
      {isSystemAdmin&&<section className="mt-6 border border-amber-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-bold text-amber-700">ملكية النظام</p><h3 className="mt-1 text-lg font-bold text-slate-950">نقل مدير النظام</h3><p className="mt-2 text-sm leading-7 text-slate-500">أدخل البريد الإلكتروني لعضو موجود في هذه الشركة. سيتم نقل الصلاحيات الكاملة إليه، وستصبح أنت مستخدمًا بصلاحيات صفرية.</p></div><div className="flex w-full flex-col gap-2 sm:flex-row lg:w-auto"><input className="input min-w-0 sm:w-80" type="email" value={transferEmail} onChange={e=>setTransferEmail(e.target.value)} placeholder="البريد الإلكتروني للمدير الجديد"/><button disabled={transferBusy||!transferEmail.trim()} onClick={()=>void transferOwnership()} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{transferBusy?"جارٍ النقل…":"نقل ملكية مدير النظام"}</button></div></div></section>}
      <div className="mt-7 grid gap-4 sm:grid-cols-5"><Stat label="أعضاء الشركة" value={members.length}/><Stat label="الأدوار المتاحة لك" value={manageableRoles.length}/><Stat label="الشاشات التي يمكنك منحها" value={screenPermissions.length}/><Stat label="إجراءات يمكنك منحها" value={actionPermissions.length}/><Stat label="إدارة نطاق البيانات" value={canManageScopes?1:0}/></div>
      <section className="mt-6 rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5 sm:p-6"><h3 className="font-bold text-slate-950">الهيكل الهرمي للفريق</h3><p className="mt-1 text-sm text-slate-500">لا يمكنك تعديل مستخدم أعلى منك أو خارج شجرتك الإدارية.</p></div><div className="divide-y divide-slate-100">{members.map(m=><div key={m.user_id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-900">{m.email||"مستخدم بدون بريد ظاهر"}</p><p className="mt-1 text-xs text-slate-400">{roleName(m.role_key)} · المستوى {m.hierarchy_level} · {m.manageable?"قابل للإدارة":"محمي"}</p></div><button disabled={!m.manageable} onClick={()=>void openEditor(m)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700 disabled:opacity-40">إدارة العضو</button></div>)}</div></section>
      {showInvite&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4"><div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">إنشاء رابط دعوة</h3><button onClick={()=>setShowInvite(false)} className="text-slate-400">إغلاق</button></div><div className="mt-5 space-y-4"><input className="input w-full" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني"/><select className="input w-full" value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{manageableRoles.map(r=><option key={r.role_key} value={r.role_key}>{r.name}</option>)}</select><button disabled={busy||!email.trim()||!inviteRole} onClick={()=>void invite()} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white disabled:opacity-40">{busy?"جارٍ الإنشاء…":"إنشاء الرابط"}</button>{inviteLink&&<div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">رابط الدعوة</p><p className="mt-2 break-all text-sm font-bold text-slate-800">{inviteLink}</p></div>}</div></div></div>}
      {editing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/30 p-4"><div className="mx-auto my-8 w-full max-w-4xl rounded-2xl border border-slate-200 bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">إدارة العضو</h3><p className="mt-1 text-sm text-slate-500">{editing.email||"مستخدم"}</p></div><button onClick={()=>setEditing(null)} className="text-slate-400">إغلاق</button></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section><label className="text-sm font-bold">الدور</label><select className="input mt-2 w-full" value={editing.role_key} onChange={e=>setEditing({...editing,role_key:e.target.value})}>{manageableRoles.map(r=><option key={r.role_key} value={r.role_key}>{r.name}</option>)}</select><button disabled={saving} onClick={()=>void changeRole()} className="mt-3 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">حفظ الدور</button></section><section><p className="text-sm font-bold">الصلاحيات المباشرة</p><div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{manageablePermissions.map(p=><label key={p.permission_key} className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><span className="text-sm text-slate-700">{p.name}</span><input type="checkbox" checked={effectivePermission(editing,p.permission_key)} disabled={saving} onChange={e=>void togglePermission(p.permission_key,e.target.checked)}/></label>)}</div></section></div>{canViewScopes&&<section className="mt-7 border-t border-slate-200 pt-6"><div className="flex items-center justify-between"><div><h4 className="font-bold">نطاق بيانات العضو</h4><p className="mt-1 text-xs text-slate-500">لا يمكن منح نطاق يتجاوز نطاقك أنت.</p></div>{scopeLoading&&<span className="text-xs text-slate-400">جارٍ التحميل…</span>}</div><div className="mt-4 grid gap-4 sm:grid-cols-2">{scopeTypes.map(([type,label])=><div key={type} className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-sm">{label}</p><div className="mt-3 space-y-2">{(scopeCatalog[type]??[]).map(item=><label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={effectiveScope(type,item.id)} disabled={saving||!canManageScopes} onChange={e=>void toggleScope(type,item.id,e.target.checked)}/><span>{item.name}</span></label>)}</div>{!hasAnyScope(type)&&<p className="mt-2 text-xs text-slate-400">لا يوجد نطاق محدد</p>}</div>)}</div></section>}{editing.manageable&&<button disabled={saving} onClick={()=>void removeMember(editing.user_id)} className="mt-7 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700 disabled:opacity-40">إزالة العضو من الشركة</button>}</div></div>}
    </section>
  </main>
}

function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>}
