"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

const roles = [
  ["company_admin", "مسؤول الشركة", "إدارة المستخدمين والإعدادات والصلاحيات"], ["executive_director", "مدير تنفيذي", "كل الصلاحيات ويمكن حجب صلاحيات محددة"], ["ceo", "الرئيس التنفيذي", "الرؤية التنفيذية والقرارات"], ["cfo", "المدير المالي", "التخطيط والمراجعة والاعتماد"], ["finance_manager", "مدير مالي", "التخطيط والتوقعات والتحليل"], ["fpa_analyst", "محلل FP&A", "النماذج والتوقعات والسيناريوهات"], ["accountant", "محاسب", "الفعلي والاستيراد والمطابقات"], ["department_manager", "مدير قسم", "بيانات وأداء القسم"], ["sales_manager", "مدير مبيعات", "افتراضات المبيعات"], ["hr_manager", "مدير الموارد البشرية", "القوى العاملة"], ["procurement_manager", "مدير المشتريات", "المشتريات والتكاليف"], ["operations_manager", "مدير العمليات", "المحركات التشغيلية"], ["viewer", "مطلع", "عرض البيانات المسموح بها"],
] as const;
const permissions = [["view","عرض"],["create","إنشاء"],["edit","تعديل"],["delete","حذف"],["import","استيراد"],["export","تصدير"],["submit","إرسال"],["approve","اعتماد"],["reject","رفض"],["lock","قفل"],["manage_users","إدارة المستخدمين"],["manage_settings","الإعدادات"],["manage_budget","الميزانية"],["manage_forecast","التوقعات"],["manage_scenarios","السيناريوهات"],["access_ai","المحلل المالي الذكي"]] as const;
type Member={user_id:string;email:string|null;role:string;role_key:string;created_at:string;overrides:Record<string,boolean>};

export default function TeamPage(){
 const supabase=getSupabaseBrowserClient();
 const [members,setMembers]=useState<Member[]>([]); const [canManage,setCanManage]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [showInvite,setShowInvite]=useState(false); const [email,setEmail]=useState(""); const [inviteRole,setInviteRole]=useState("viewer"); const [editing,setEditing]=useState<Member|null>(null); const [saving,setSaving]=useState(false);
 const orgId=()=>typeof window!=="undefined"?window.sessionStorage.getItem("activeOrganizationId"):null;
 async function load(){const id=orgId();if(!id)return;setError("");const {data,error:e}=await supabase.rpc("get_team_members",{p_organization_id:id});if(e){setError(e.message);return;}setMembers((data??[]) as Member[]);const {data:p}=await supabase.rpc("has_org_permission",{p_organization_id:id,p_permission_key:"manage_users"});setCanManage(Boolean(p));}
 useEffect(()=>{void load();},[]);
 async function invite(){const id=orgId();if(!id||!email.trim())return;setBusy(true);setError("");try{const {data,error:e}=await supabase.functions.invoke("invite-team-member",{body:{organization_id:id,email:email.trim(),role_key:inviteRole}});if(e)throw new Error(e.message||"تعذر الاتصال بخدمة الدعوات");if(!data?.ok)throw new Error(data?.error||data?.message||"تعذر إرسال الدعوة");setEmail("");setShowInvite(false);await load();}catch(e){setError(e instanceof Error?e.message:"تعذر إرسال الدعوة");}finally{setBusy(false);}}
 async function changeRole(){if(!editing)return;const id=orgId();if(!id)return;setSaving(true);setError("");const {error:e}=await supabase.rpc("set_team_member_role",{p_organization_id:id,p_user_id:editing.user_id,p_role_key:editing.role_key});setSaving(false);if(e){setError(e.message);return;}setEditing(null);await load();}
 async function togglePermission(permission:string,granted:boolean){if(!editing)return;const id=orgId();if(!id)return;setSaving(true);setError("");const {error:e}=await supabase.rpc("set_team_member_permission_override",{p_organization_id:id,p_user_id:editing.user_id,p_permission_key:permission,p_granted:granted});setSaving(false);if(e){setError(e.message);return;}setEditing({...editing,overrides:{...editing.overrides,[permission]:granted}});await load();}
 async function removeMember(userId:string){const id=orgId();if(!id||!confirm("هل تريد إزالة هذا العضو من الشركة؟"))return;setSaving(true);const {error:e}=await supabase.rpc("remove_team_member",{p_organization_id:id,p_user_id:userId});setSaving(false);if(e){setError(e.message);return;}setEditing(null);await load();}
 const roleName=(key:string)=>roles.find(([r])=>r===key)?.[1]??key;
 const roleHasPermission=(roleKey:string,permission:string)=>roleKey==="executive_director";
 const effectivePermission=(member:Member,permission:string)=>member.overrides[permission] ?? roleHasPermission(member.role_key,permission);
 return <main className="min-h-screen bg-[#f7f8fa] text-[#172033]" dir="rtl"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><Link href="/workspace" className="text-sm font-semibold text-slate-500">العودة لمساحة العمل</Link><div className="text-right"><p className="text-xs font-bold tracking-[.14em] text-slate-400">IDENTITY & ACCESS</p><h1 className="mt-1 font-bold text-slate-950">الفريق والصلاحيات</h1></div></div></header>
 <section className="mx-auto max-w-[1500px] px-4 py-7 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-bold text-slate-400">RBAC · TEAM · LEAST PRIVILEGE</p><h2 className="mt-2 text-2xl font-bold text-slate-950 sm:text-3xl">إدارة أعضاء الشركة والصلاحيات</h2><p className="mt-3 text-sm leading-7 text-slate-500">الدور يحدد الصلاحيات الأساسية، ويمكن إضافة استثناءات محددة للعضو. الدور «مدير تنفيذي» يبدأ بكل الصلاحيات، ويمكنك إلغاء أي صلاحية محددة عنه دون تغيير الدور.</p></div><button disabled={!canManage} onClick={()=>setShowInvite(true)} className="w-full rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white disabled:opacity-40 sm:w-auto">دعوة عضو جديد</button></div>
 {error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
 <div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="أعضاء الشركة" value={members.length}/><Stat label="الأدوار" value={roles.length}/><Stat label="الصلاحيات" value={permissions.length}/></div>
 <section className="mt-6 rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5 sm:p-6"><h3 className="font-bold text-slate-950">أعضاء الشركة</h3><p className="mt-1 text-sm text-slate-500">كل عضو مرتبط بالشركة الحالية فقط.</p></div><div className="divide-y divide-slate-100">{members.map(m=><div key={m.user_id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-900">{m.email||"مستخدم بدون بريد ظاهر"}</p><p className="mt-1 text-xs text-slate-400">{m.user_id}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{roleName(m.role_key)}</span>{Object.entries(m.overrides).length>0&&<span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700">استثناءات مخصصة</span>}<button disabled={!canManage} onClick={()=>setEditing(m)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold disabled:opacity-40">إدارة الصلاحيات</button></div></div>)}</div></section>
 </section>
 {showInvite&&<Modal title="دعوة عضو جديد" onClose={()=>setShowInvite(false)}><label className="block"><span className="mb-2 block text-sm font-semibold">البريد الإلكتروني</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">الدور</span><select className="input" value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{roles.map(([k,n,d])=><option key={k} value={k}>{n} — {d}</option>)}</select></label><button disabled={busy||!email.trim()} onClick={()=>void invite()} className="mt-6 w-full rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white disabled:opacity-40">{busy?"جارٍ إرسال الدعوة…":"إرسال الدعوة"}</button></Modal>}
 {editing&&<Modal title="إدارة صلاحيات العضو" onClose={()=>setEditing(null)}><p className="font-bold">{editing.email}</p><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">الدور الأساسي</span><select className="input" value={editing.role_key} onChange={e=>setEditing({...editing,role_key:e.target.value})}>{roles.map(([k,n,d])=><option key={k} value={k}>{n} — {d}</option>)}</select></label><button disabled={saving} onClick={()=>void changeRole()} className="mt-4 w-full rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">حفظ الدور</button><div className="mt-6 border-t pt-5"><p className="font-bold">استثناءات الصلاحيات</p><p className="mt-1 text-xs leading-6 text-slate-500">في الدور «مدير تنفيذي» تكون كل الصلاحيات مفعلة افتراضيًا. إلغاء المربع ينشئ استثناء «ممنوع» لهذا العضو فقط.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{permissions.map(([k,n])=>{const enabled=effectivePermission(editing,k);return <label key={k} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm"><span>{n}{editing.overrides[k]===false&&<small className="mr-2 text-red-600">محجوبة</small>}</span><input disabled={saving} type="checkbox" checked={enabled} onChange={e=>void togglePermission(k,e.target.checked)}/></label>})}</div></div><button disabled={saving} onClick={()=>void removeMember(editing.user_id)} className="mt-6 w-full rounded-xl border border-red-200 px-5 py-3 text-sm font-bold text-red-700">إزالة العضو من الشركة</button></Modal>}
 </main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between"><h3 className="text-xl font-bold text-slate-950">{title}</h3><button onClick={onClose} className="rounded-lg px-3 py-2 text-slate-500">إغلاق</button></div><div className="mt-6">{children}</div></div></div>}
