"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Period={id:string;period_start:string;period_end:string;status:string};
type Option={id:string;code:string|null;name:string};
type FS={period:{start:string;end:string;status:string};fiscal_year_start:string;income_statement:any;income_statement_ytd:any;balance_sheet:{accounts:any[];total_assets:number;total_liabilities:number;total_equity:number;equity_accounts_total:number;ytd_net_income:number;balance_check:number;current_year_profit_account_balance:number};cash_flow:any;equity_statement:any;validation:{unclassified_income_accounts:number;balance_sheet_difference:number;cash_flow_reconciliation_difference:number};methodology:any};
const money=(v:number)=>(Number(v||0)/100).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString("ar-SA",{year:"numeric",month:"long",day:"numeric"});
const labelMap:Record<string,string>={revenue:"الإيرادات",cogs:"تكلفة المبيعات",operating_expenses:"المصروفات التشغيلية",other_income:"الدخل الآخر",depreciation_amortization:"الإهلاك والاستهلاك",finance_cost:"تكلفة التمويل",other_expenses:"المصروفات الأخرى",tax:"الضريبة"};

export default function FinancialStatementsPage(){
 const supabase=getSupabaseBrowserClient();
 const [org,setOrg]=useState(""); const [industry,setIndustry]=useState(""); const [periods,setPeriods]=useState<Period[]>([]); const [period,setPeriod]=useState(""); const [data,setData]=useState<FS|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false);
 const [advanced,setAdvanced]=useState(false); const [template,setTemplate]=useState("standard"); const [cashMethod,setCashMethod]=useState("indirect"); const [templates,setTemplates]=useState<any[]>([]); const [options,setOptions]=useState<any>({branches:[],departments:[],cost_centers:[],regions:[],products:[],projects:[],accounts:[]});
 const [filters,setFilters]=useState({branch:"",department:"",cost_center:"",region:"",product:"",project:"",account:""});
 const [query,setQuery]=useState("");
 useEffect(()=>{const id=window.sessionStorage.getItem("activeOrganizationId")||window.localStorage.getItem("activeOrganizationId")||"";setOrg(id);if(!id){setError("لم يتم تحديد مساحة عمل.");setLoading(false);return;}
  void Promise.all([
   supabase.from("financial_periods").select("id,period_start,period_end,status").eq("organization_id",id).order("period_start",{ascending:false}),
   supabase.from("organizations").select("industry").eq("id",id).maybeSingle(),
   supabase.from("financial_statement_templates").select("template_key,name_ar,name_en,activity_key,description_ar,config").eq("is_active",true).order("is_system",{ascending:false}),
   supabase.rpc("get_reporting_filter_options",{p_organization_id:id}),
   supabase.rpc("get_reporting_preferences",{p_organization_id:id})
  ]).then(([p,o,t,f,r])=>{if(p.error)setError(p.error.message);const rows=(p.data||[]) as Period[];setPeriods(rows);if(rows[0])setPeriod(rows[0].id);if(!o.error)setIndustry(o.data?.industry||"");if(!t.error)setTemplates(t.data||[]);if(!f.error)setOptions(f.data||{});if(!r.error&&r.data){setTemplate(r.data.template_key||"standard");setCashMethod(r.data.cash_flow_method||"indirect");}setLoading(false);});
 },[]);
 const activeTemplate=useMemo(()=>templates.find(t=>t.template_key===template),[templates,template]);
 const selectedAccount=useMemo(()=>options.accounts?.find((a:any)=>a.id===filters.account),[options.accounts,filters.account]);
 const activeFilterCount=Object.values(filters).filter(Boolean).length;
 const filteredAccounts=useMemo(()=>{const q=query.trim().toLocaleLowerCase("ar");if(!q)return options.accounts||[];return (options.accounts||[]).filter((a:any)=>`${a.code} ${a.name}`.toLocaleLowerCase("ar").includes(q));},[options.accounts,query]);
 async function load(){if(!org||!period)return;setRunning(true);setError("");const {data:result,error:e}=await supabase.rpc("get_financial_statements",{p_organization_id:org,p_period_id:period,p_branch_id:filters.branch||null,p_department_id:filters.department||null,p_cost_center_id:filters.cost_center||null,p_region_id:filters.region||null,p_product_id:filters.product||null,p_project_id:filters.project||null,p_account_id:filters.account||null,p_cash_flow_method:cashMethod});if(e){setError(e.message);setData(null);}else setData(result as FS);setRunning(false);}
 async function savePreference(nextTemplate=template,nextMethod=cashMethod){if(!org)return;const {error:e}=await supabase.rpc("set_reporting_preferences",{p_organization_id:org,p_template_key:nextTemplate,p_cash_flow_method:nextMethod});if(e)setError(e.message);}
 function clearFilters(){setFilters({branch:"",department:"",cost_center:"",region:"",product:"",project:"",account:""});setData(null);}
 function setMethod(v:string){setCashMethod(v);setData(null);void savePreference(template,v);}
 function setTemplateChoice(v:string){setTemplate(v);setData(null);void savePreference(v,cashMethod);}
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] text-[#172033]"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8"><a href="/workspace" className="text-sm font-semibold text-slate-500">العودة لمساحة العمل</a><div className="text-right"><p className="text-[10px] font-bold tracking-[.14em] text-slate-400">FINANCIAL REPORTING</p><h1 className="mt-1 font-bold text-slate-950">القوائم المالية</h1></div></div></header>
 <section className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 border-b border-slate-200 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold text-slate-400">{industry||"ملف النشاط"}</p><h2 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">مركز القوائم المالية</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">قائمة الدخل، المركز المالي، التدفقات النقدية، والتغيرات في حقوق الملكية ضمن نموذج واحد مترابط.</p></div><div className="flex gap-2"><select value={template} onChange={e=>setTemplateChoice(e.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold"><option value="standard">القالب القياسي</option>{templates.filter(t=>t.template_key!=="standard").map(t=><option key={t.template_key} value={t.template_key}>{t.name_ar}</option>)}</select><button onClick={()=>setAdvanced(v=>!v)} className={`min-h-11 rounded-xl border px-4 text-sm font-bold ${advanced||activeFilterCount?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white text-slate-800"}`}>الفلاتر {activeFilterCount?`(${activeFilterCount})`:""}</button></div></div>
 <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.4fr_1fr_1fr_auto]"><select value={period} onChange={e=>{setPeriod(e.target.value);setData(null)}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold">{periods.map(p=><option key={p.id} value={p.id}>{date(p.period_start)} — {date(p.period_end)}</option>)}</select><select value={filters.branch} onChange={e=>{setFilters({...filters,branch:e.target.value});setData(null)}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="">كل الفروع</option>{(options.branches||[]).map((x:Option)=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select><select value={cashMethod} onChange={e=>setMethod(e.target.value)} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="indirect">التدفقات النقدية — غير مباشرة</option><option value="direct">التدفقات النقدية — مباشرة</option></select><button disabled={!period||running} onClick={load} className="min-h-11 rounded-xl bg-slate-950 px-5 text-sm font-bold text-white disabled:opacity-50">{running?"جاري الحساب...":"تطبيق"}</button></div>
 {activeFilterCount>0&&<div className="mt-3 flex flex-wrap gap-2">{Object.entries(filters).filter(([,v])=>v).map(([k,v])=><button key={k} onClick={()=>setFilters({...filters,[k]:""})} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{k==='branch'?'الفرع':k==='department'?'الإدارة':k==='cost_center'?'مركز التكلفة':k==='region'?'المنطقة':k==='product'?'المنتج':k==='project'?'المشروع':'الحساب'} ×</button>)}<button onClick={clearFilters} className="text-xs font-bold text-red-600">مسح الكل</button></div>}
 {advanced&&<div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2 lg:grid-cols-4"><FilterSelect label="الإدارة" value={filters.department} setValue={v=>setFilters({...filters,department:v})} items={options.departments}/><FilterSelect label="مركز التكلفة" value={filters.cost_center} setValue={v=>setFilters({...filters,cost_center:v})} items={options.cost_centers}/><FilterSelect label="المنطقة" value={filters.region} setValue={v=>setFilters({...filters,region:v})} items={options.regions}/><FilterSelect label="المنتج" value={filters.product} setValue={v=>setFilters({...filters,product:v})} items={options.products}/><FilterSelect label="المشروع" value={filters.project} setValue={v=>setFilters({...filters,project:v})} items={options.projects}/><div><label className="text-xs font-bold text-slate-500">الحساب</label><input value={selectedAccount?`${selectedAccount.code} — ${selectedAccount.name}`:query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setFilters({...filters,account:""})}} placeholder="ابحث بكود أو اسم الحساب" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"/>{query&&<div className="mt-1 max-h-40 overflow-auto rounded-xl border border-slate-200 bg-white">{filteredAccounts.slice(0,20).map((a:any)=><button key={a.id} onClick={()=>{setFilters({...filters,account:a.id});setQuery("")}} className="block w-full px-3 py-2 text-right text-xs hover:bg-slate-50">{a.code} — {a.name}</button>)}</div>}</div></div>}
 </div>
 {activeTemplate&&<p className="mt-3 text-xs text-slate-500">{activeTemplate.description_ar}</p>}
 {loading?<div className="mt-7 rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">جاري تحميل الفترات والتصنيفات...</div>:error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>:!data?<div className="mt-7 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">اختر الفترة والفلاتر ثم اضغط تطبيق لعرض القوائم.</div>:<>
 <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="الإيرادات" value={data.income_statement.revenue}/><Metric label="مجمل الربح" value={data.income_statement.gross_profit}/><Metric label="EBITDA" value={data.income_statement.ebitda}/><Metric label="صافي الربح" value={data.income_statement.net_income}/><Metric label="حقوق الملكية" value={data.balance_sheet.total_equity}/><Metric label="النقدية آخر الفترة" value={data.cash_flow.closing_cash}/></div>
 <div className={`mt-4 rounded-xl border p-4 text-sm font-bold ${data.validation.balance_sheet_difference===0?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>حالة النموذج: {data.validation.balance_sheet_difference===0?"متوازن":"يحتاج مراجعة"} · فرق المركز المالي: {money(data.validation.balance_sheet_difference)} · صافي الربح YTD مُرحّل ضمن حقوق الملكية: {money(data.balance_sheet.ytd_net_income)}</div>
 <div className="mt-6 flex gap-1 overflow-x-auto border-b border-slate-200"><Tab title="قائمة الدخل"/><Tab title="المركز المالي"/><Tab title="التدفقات النقدية"/><Tab title="التغيرات في حقوق الملكية"/></div>
 <div className="mt-5 grid gap-6 xl:grid-cols-2">
 <Statement title="قائمة الدخل"><Line label={labelMap.revenue} value={data.income_statement.revenue}/><Line label={labelMap.cogs} value={data.income_statement.cogs}/><Line label="مجمل الربح" value={data.income_statement.gross_profit} strong/><Line label={labelMap.operating_expenses} value={data.income_statement.operating_expenses}/><Line label={labelMap.other_income} value={data.income_statement.other_income}/><Line label="EBITDA" value={data.income_statement.ebitda} strong/><Line label={labelMap.depreciation_amortization} value={data.income_statement.depreciation_amortization}/><Line label="EBIT" value={data.income_statement.ebit} strong/><Line label={labelMap.finance_cost} value={data.income_statement.finance_cost}/><Line label={labelMap.other_expenses} value={data.income_statement.other_expenses}/><Line label="الربح قبل الضريبة" value={data.income_statement.ebt} strong/><Line label={labelMap.tax} value={data.income_statement.tax}/><Line label="صافي الربح" value={data.income_statement.net_income} strong/></Statement>
 <Statement title="قائمة المركز المالي" subtitle={`تراكمية حتى ${date(data.period.end)}`}><Line label="إجمالي الأصول" value={data.balance_sheet.total_assets} strong/><Line label="إجمالي الالتزامات" value={data.balance_sheet.total_liabilities}/><Line label="حقوق الملكية + صافي الربح" value={data.balance_sheet.total_equity} strong/><div className="mt-4 overflow-auto"><table className="w-full min-w-[650px] text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-2 py-2 text-right">الحساب</th><th className="px-2 py-2 text-right">التصنيف</th><th className="px-2 py-2 text-left">الرصيد</th></tr></thead><tbody>{data.balance_sheet.accounts.map((a:any)=><tr key={a.code} className="border-b border-slate-100"><td className="px-2 py-2 font-semibold">{a.code} — {a.name}</td><td className="px-2 py-2 text-slate-500">{a.subclassification||"غير مصنف"}</td><td className="px-2 py-2 text-left tabular-nums">{money(a.balance)}</td></tr>)}</tbody></table></div></Statement>
 <Statement title={`قائمة التدفقات النقدية — ${cashMethod==='direct'?"الطريقة المباشرة":"الطريقة غير المباشرة"}`} subtitle={cashMethod==='direct'?"العرض المباشر يحتاج تصنيف مصادر واستخدامات النقد في القيود.":"تبدأ من صافي الربح وتعدل البنود غير النقدية ورأس المال العامل."}><Line label="النقدية أول الفترة" value={data.cash_flow.opening_cash}/>{cashMethod==='indirect'?<><Line label="صافي الربح" value={data.cash_flow.operating.net_income}/><Line label="الإهلاك والاستهلاك" value={data.cash_flow.operating.depreciation_amortization}/><Line label="التغير في رأس المال العامل" value={data.cash_flow.operating.working_capital_change}/><Line label="صافي التدفق التشغيلي" value={data.cash_flow.operating.net_operating_cash_flow} strong/></>:<><Line label="المقبوضات النقدية" value={data.cash_flow.operating.cash_inflows}/><Line label="المدفوعات النقدية" value={data.cash_flow.operating.cash_outflows}/><Line label="صافي التدفق التشغيلي" value={data.cash_flow.operating.net_operating_cash_flow} strong/></>}<Line label="صافي التدفق الاستثماري" value={data.cash_flow.investing.net_cash_flow}/><Line label="صافي التدفق التمويلي" value={data.cash_flow.financing.net_cash_flow}/><Line label="النقدية آخر الفترة" value={data.cash_flow.closing_cash} strong/><div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-600">{cashMethod==='direct'?`جودة بيانات الطريقة المباشرة: ${data.cash_flow.direct_data_quality==='partial'?"جزئية وتحتاج استكمال تصنيف الحسابات":"غير كافية"}`:`فرق تسوية النقدية: ${money(data.cash_flow.reconciliation_difference)}`}</div></Statement>
 <Statement title="قائمة التغيرات في حقوق الملكية" subtitle="صافي ربح قائمة الدخل YTD ينتقل إلى حقوق الملكية قبل اختبار توازن المركز المالي."><Line label="حقوق الملكية المسجلة في الحسابات" value={data.balance_sheet.equity_accounts_total}/><Line label="صافي ربح الفترة YTD" value={data.equity_statement.ytd_net_income}/><Line label="رصيد أرباح العام الحالي المسجل" value={data.equity_statement.profit_account_balance}/><Line label="حقوق الملكية المعروضة" value={data.equity_statement.displayed_closing_equity} strong/><div className="mt-4 overflow-auto"><table className="w-full min-w-[550px] text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-2 py-2 text-right">الحساب</th><th className="px-2 py-2 text-left">الرصيد</th></tr></thead><tbody>{(data.equity_statement.rows||[]).map((r:any)=><tr key={r.code} className="border-b border-slate-100"><td className="px-2 py-2 font-semibold">{r.code} — {r.name}</td><td className="px-2 py-2 text-left tabular-nums">{money(r.closing)}</td></tr>)}</tbody></table></div></Statement>
 </div></>}</section></main>
}
function FilterSelect({label,value,setValue,items}:{label:string;value:string;setValue:(v:string)=>void;items:Option[]}){return <label><span className="text-xs font-bold text-slate-500">{label}</span><select value={value} onChange={e=>setValue(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">الكل</option>{(items||[]).map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select></label>}
function Statement({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-lg font-bold text-slate-950">{title}</h3>{subtitle&&<p className="mt-1 text-xs leading-5 text-slate-500">{subtitle}</p>}<div className="mt-5">{children}</div></section>}
function Line({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex items-center justify-between border-b border-slate-100 py-3 text-sm ${strong?"font-bold text-slate-950":"text-slate-600"}`}><span>{label}</span><span className="tabular-nums">{money(value)}</span></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[11px] font-bold text-slate-400">{label}</p><p className="mt-2 text-lg font-bold text-slate-950 tabular-nums">{money(value)}</p></div>}
function Tab({title}:{title:string}){return <button className="whitespace-nowrap border-b-2 border-slate-950 px-4 py-3 text-sm font-bold text-slate-950">{title}</button>}
