"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Period={id:string;period_start:string;period_end:string;status:string};
type Option={id:string;code:string|null;name:string};
type FS={period:{start:string;end:string;status:string};fiscal_year_start:string;income_statement:any;income_statement_ytd:any;balance_sheet:any;cash_flow:any;equity_statement:any;validation:any;methodology:any};
type OCI={period:{rows:any[];total:number};ytd:{rows:any[];total:number};comprehensive_income_adjustment:number};
const money=(v:number)=>(Number(v||0)/100).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString("ar-SA",{year:"numeric",month:"long",day:"numeric"});
const fields=[
 {key:"branch",label:"الفرع",itemsKey:"branches"},{key:"department",label:"الإدارة",itemsKey:"departments"},{key:"cost_center",label:"مركز التكلفة",itemsKey:"cost_centers"},{key:"region",label:"المنطقة",itemsKey:"regions"},{key:"product",label:"المنتج",itemsKey:"products"},{key:"project",label:"المشروع",itemsKey:"projects"},{key:"account",label:"الحساب",itemsKey:"accounts"}
];
const labels:Record<string,string>={revenue:"الإيرادات",cogs:"تكلفة المبيعات",operating_expenses:"المصروفات التشغيلية",other_income:"الدخل الآخر",depreciation_amortization:"الإهلاك والاستهلاك",finance_cost:"تكلفة التمويل",other_expenses:"المصروفات الأخرى",tax:"الضريبة"};
const statements=["balance","income","oci","cash","equity"] as const;
type StatementKey=typeof statements[number];

export default function FinancialStatementsPage(){
 const supabase=getSupabaseBrowserClient();
 const [org,setOrg]=useState(""); const [industry,setIndustry]=useState(""); const [periods,setPeriods]=useState<Period[]>([]); const [period,setPeriod]=useState(""); const [data,setData]=useState<FS|null>(null); const [oci,setOci]=useState<OCI|null>(null); const [options,setOptions]=useState<any>({}); const [templates,setTemplates]=useState<any[]>([]);
 const [template,setTemplate]=useState("standard"); const [cashMethod,setCashMethod]=useState("indirect"); const [filters,setFilters]=useState<Record<string,string>>({branch:"",department:"",cost_center:"",region:"",product:"",project:"",account:""});
 const [advanced,setAdvanced]=useState(false); const [filterField,setFilterField]=useState("branch"); const [filterValue,setFilterValue]=useState(""); const [accountQuery,setAccountQuery]=useState(""); const [active,setActive]=useState<StatementKey>("balance");
 const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{const id=window.sessionStorage.getItem("activeOrganizationId")||window.localStorage.getItem("activeOrganizationId")||"";setOrg(id);if(!id){setError("لم يتم تحديد مساحة عمل.");setLoading(false);return;} const savedTemplate=window.localStorage.getItem(`fpa:statement-template:${id}`);const savedMethod=window.localStorage.getItem(`fpa:cash-method:${id}`);if(savedTemplate)setTemplate(savedTemplate);if(savedMethod)setCashMethod(savedMethod);
  void Promise.all([
   supabase.from("financial_periods").select("id,period_start,period_end,status").eq("organization_id",id).order("period_start",{ascending:false}),
   supabase.from("organizations").select("industry").eq("id",id).maybeSingle(),
   supabase.from("financial_statement_templates").select("template_key,name_ar,name_en,activity_key,description_ar,config").eq("is_active",true).order("is_system",{ascending:false}),
   supabase.rpc("get_reporting_filter_options",{p_organization_id:id})
  ]).then(([p,o,t,f])=>{if(p.error)setError(p.error.message);const rows=(p.data||[]) as Period[];setPeriods(rows);if(rows[0])setPeriod(rows[0].id);if(!o.error)setIndustry(o.data?.industry||"");if(!t.error)setTemplates(t.data||[]);if(!f.error)setOptions(f.data||{});setLoading(false);});
 },[]);
 const activeTemplate=useMemo(()=>templates.find(t=>t.template_key===template),[templates,template]);
 const preferredTerms=activeTemplate?.config?.preferred_terms||{};
 const activeFilterCount=Object.values(filters).filter(Boolean).length;
 const accountItems=(options.accounts||[]) as any[];
 const filteredAccounts=useMemo(()=>{const q=accountQuery.trim().toLocaleLowerCase("ar");return q?accountItems.filter(a=>`${a.code} ${a.name}`.toLocaleLowerCase("ar").includes(q)):accountItems;},[accountItems,accountQuery]);
 const currentField=fields.find(x=>x.key===filterField)||fields[0];
 const currentItems=(options[currentField.itemsKey]||[]) as Option[];
 function chooseTemplate(v:string){setTemplate(v);if(org)window.localStorage.setItem(`fpa:statement-template:${org}`,v);setData(null);}
 function chooseMethod(v:string){setCashMethod(v);if(org)window.localStorage.setItem(`fpa:cash-method:${org}`,v);setData(null);}
 function addFilter(){if(!filterValue)return;setFilters(prev=>({...prev,[filterField]:filterValue}));setFilterValue("");setData(null);}
 function clearFilters(){setFilters({branch:"",department:"",cost_center:"",region:"",product:"",project:"",account:""});setAccountQuery("");setData(null);}
 async function load(){if(!org||!period)return;setRunning(true);setError("");const args={p_organization_id:org,p_period_id:period,p_branch_id:filters.branch||null,p_department_id:filters.department||null,p_cost_center_id:filters.cost_center||null,p_region_id:filters.region||null,p_product_id:filters.product||null,p_project_id:filters.project||null,p_account_id:filters.account||null,p_cash_flow_method:cashMethod}; const [r,o]=await Promise.all([supabase.rpc("get_financial_statements",args),supabase.rpc("get_other_comprehensive_income",{p_organization_id:org,p_period_id:period,p_branch_id:filters.branch||null,p_department_id:filters.department||null,p_cost_center_id:filters.cost_center||null,p_region_id:filters.region||null,p_product_id:filters.product||null,p_project_id:filters.project||null})]); if(r.error){setError(r.error.message);setData(null);}else setData(r.data as FS);if(o.error){setOci(null);if(!r.error)setError(`تعذر تحميل قائمة الدخل الشامل الآخر: ${o.error.message}`);}else setOci(o.data as OCI);setRunning(false);}
 function move(dir:-1|1){const i=statements.indexOf(active);setActive(statements[(i+dir+statements.length)%statements.length]);}
 const title=active==="balance"?"قائمة المركز المالي":active==="income"?"قائمة الدخل":active==="oci"?"قائمة الدخل الشامل الآخر":active==="cash"?"قائمة التدفقات النقدية":"قائمة التغير في حقوق الملكية";
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] text-[#172033]"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8"><a href="/workspace" className="text-sm font-semibold text-slate-500">العودة لمساحة العمل</a><div className="text-right"><p className="text-[10px] font-bold tracking-[.14em] text-slate-400">FINANCIAL REPORTING</p><h1 className="mt-1 font-bold text-slate-950">مركز القوائم المالية</h1></div></div></header>
 <section className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8"><div className="border-b border-slate-200 pb-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold text-slate-400">{industry||"ملف النشاط"}</p><h2 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">القوائم المالية المترابطة</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-500">مصدر واحد للبيانات الفعلية المنشورة، مع فلاتر تحليلية وقوالب حسب النشاط وربط مباشر بين الربح وحقوق الملكية والنقدية.</p></div><div className="flex flex-wrap gap-2"><select value={template} onChange={e=>chooseTemplate(e.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold"><option value="standard">القالب القياسي</option>{templates.filter(t=>t.template_key!=="standard").map(t=><option key={t.template_key} value={t.template_key}>{t.name_ar}</option>)}</select><select value={cashMethod} onChange={e=>chooseMethod(e.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold"><option value="indirect">التدفقات النقدية — غير مباشرة</option><option value="direct">التدفقات النقدية — مباشرة</option></select></div></div></div>
 <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.45fr_1fr_auto_auto]"><select value={period} onChange={e=>{setPeriod(e.target.value);setData(null)}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold">{periods.map(p=><option key={p.id} value={p.id}>{date(p.period_start)} — {date(p.period_end)}</option>)}</select><select value={filters.branch||""} onChange={e=>{setFilters({...filters,branch:e.target.value});setData(null)}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="">كل الفروع</option>{(options.branches||[]).map((x:Option)=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select><button onClick={()=>setAdvanced(v=>!v)} className={`min-h-11 rounded-xl border px-4 text-sm font-bold ${advanced||activeFilterCount?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white text-slate-800"}`}>الفلاتر {activeFilterCount?`(${activeFilterCount})`:""}</button><button disabled={!period||running} onClick={load} className="min-h-11 rounded-xl bg-slate-950 px-5 text-sm font-bold text-white disabled:opacity-50">{running?"جاري الحساب...":"تطبيق"}</button></div>
 {activeFilterCount>0&&<div className="mt-3 flex flex-wrap items-center gap-2">{Object.entries(filters).filter(([,v])=>v).map(([k,v])=>{const f=fields.find(x=>x.key===k);const item=(options[f?.itemsKey||""]||[]).find((x:any)=>x.id===v);return <button key={k} onClick={()=>setFilters({...filters,[k]:""})} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{f?.label}: {item?.name||v} ×</button>})}<button onClick={clearFilters} className="text-xs font-bold text-red-600">مسح الكل</button></div>}
 {advanced&&<div className="mt-4 border-t border-slate-100 pt-4"><div className="grid gap-3 lg:grid-cols-[.8fr_1.5fr_auto]"><select value={filterField} onChange={e=>{setFilterField(e.target.value);setFilterValue("")}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold">{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select>{filterField==="account"?<div className="relative"><input value={accountQuery} onChange={e=>setAccountQuery(e.target.value)} placeholder="ابحث باسم أو كود الحساب" className="min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"/>{accountQuery&&<div className="absolute inset-x-0 top-12 z-20 max-h-48 overflow-auto rounded-xl border border-slate-200 bg-white shadow-lg">{filteredAccounts.slice(0,25).map(a=><button key={a.id} onClick={()=>{setFilterValue(a.id);setAccountQuery(`${a.code} — ${a.name}`)}} className="block w-full px-3 py-2 text-right text-xs hover:bg-slate-50">{a.code} — {a.name}</button>)}</div>}</div>:<select value={filterValue} onChange={e=>setFilterValue(e.target.value)} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="">اختر قيمة الفلتر</option>{currentItems.map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select>}<button onClick={addFilter} className="min-h-11 rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold">+ إضافة فلتر</button></div><p className="mt-2 text-xs text-slate-400">الفلاتر تعمل بمنطق AND وتُطبق على القيود المنشورة فقط، ويمكن إزالة أي فلتر من الشرائح أعلاه.</p></div>}
 </div>
 {activeTemplate?.config?.preferred_terms&&<p className="mt-3 text-xs font-semibold text-slate-500">مصطلحات القالب: {Object.values(preferredTerms).join(" · ")}</p>}
 {loading?<div className="mt-7 rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">جاري تحميل الفترات والقوالب والفلاتر...</div>:error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold leading-6 text-red-700">{error}</div>:!data?<div className="mt-7 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">اختر الفترة والفلاتر ثم اضغط تطبيق لعرض القوائم.</div>:<>
 <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="الإيرادات" value={data.income_statement.revenue}/><Metric label="مجمل الربح" value={data.income_statement.gross_profit}/><Metric label="EBITDA" value={data.income_statement.ebitda}/><Metric label="صافي الربح" value={data.income_statement.net_income}/><Metric label="حقوق الملكية" value={data.balance_sheet.total_equity}/><Metric label="النقدية آخر الفترة" value={data.cash_flow.closing_cash}/></div>
 <div className={`mt-4 rounded-xl border p-4 text-sm font-bold ${data.validation.balance_sheet_difference===0?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>حالة النموذج: {data.validation.balance_sheet_difference===0?"متوازن":"يحتاج مراجعة"} · فرق المركز المالي: {money(data.validation.balance_sheet_difference)} · صافي الربح YTD داخل حقوق الملكية: {money(data.balance_sheet.ytd_net_income)}{data.validation.cash_flow_reconciliation_difference!==0&&<span> · فرق تسوية التدفقات النقدية: {money(data.validation.cash_flow_reconciliation_difference)}</span>}</div>
 <div className="mt-6 flex items-center gap-2"><button onClick={()=>move(-1)} aria-label="القائمة السابقة" className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-slate-300 bg-white text-slate-700 hover:bg-slate-50">←</button><div className="flex min-w-0 flex-1 gap-2 overflow-x-auto pb-1">{statements.map(k=><button key={k} onClick={()=>setActive(k)} className={`min-w-[180px] rounded-xl border px-4 py-3 text-sm font-bold ${active===k?"border-slate-950 bg-slate-950 text-white":"border-slate-200 bg-white text-slate-700"}`}>{k==="balance"?"قائمة المركز المالي":k==="income"?"قائمة الدخل":k==="oci"?"قائمة الدخل الشامل الآخر":k==="cash"?"قائمة التدفقات النقدية":"قائمة التغير في حقوق الملكية"}</button>)}</div><button onClick={()=>move(1)} aria-label="القائمة التالية" className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-slate-300 bg-white text-slate-700 hover:bg-slate-50">→</button></div>
 <div className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex flex-col gap-1 border-b border-slate-100 pb-4"><h3 className="text-lg font-bold text-slate-950">{title}</h3><p className="text-xs text-slate-400">{active==="balance"?`تراكمية حتى ${date(data.period.end)}`:active==="income"?`${date(data.period.start)} — ${date(data.period.end)}`:active==="cash"?`طريقة العرض: ${cashMethod==="direct"?"مباشرة":"غير مباشرة"}`:"بيانات مترابطة مع الفترة المحددة"}</p></div>{active==="balance"&&<Balance data={data.balance_sheet}/>} {active==="income"&&<Income data={data.income_statement} terms={preferredTerms}/>} {active==="oci"&&<OCIView data={oci}/>} {active==="cash"&&<CashFlow data={data.cash_flow}/>} {active==="equity"&&<Equity data={data.equity_statement}/>}</div>
 </>}</section></main>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[11px] font-bold text-slate-400">{label}</p><p className="mt-2 text-lg font-bold tabular-nums text-slate-950">{money(value)}</p></div>}
function Row({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex items-center justify-between border-b border-slate-100 py-3 last:border-0 ${strong?"font-bold text-slate-950":"text-slate-700"}`}><span>{label}</span><span className="tabular-nums">{money(value)}</span></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-xl border border-slate-100 p-4"><h4 className="mb-2 text-sm font-bold text-slate-950">{title}</h4>{children}</div>}
function Balance({data}:{data:any}){return <div className="grid gap-6 lg:grid-cols-3"><Section title="الأصول"><Row label="إجمالي الأصول" value={data.total_assets} strong/></Section><Section title="الالتزامات"><Row label="إجمالي الالتزامات" value={data.total_liabilities} strong/></Section><Section title="حقوق الملكية"><Row label="حقوق الملكية" value={data.total_equity} strong/><Row label="صافي الربح YTD" value={data.ytd_net_income}/></Section><div className="lg:col-span-3 rounded-xl bg-slate-50 p-4 text-sm font-bold">اختبار التوازن: {money(data.balance_check)} {data.balance_check===0?"✓ متوازن":"— يحتاج مراجعة"}</div><div className="lg:col-span-3 overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-3 py-3">الحساب</th><th className="px-3 py-3">التصنيف</th><th className="px-3 py-3">مدين</th><th className="px-3 py-3">دائن</th><th className="px-3 py-3">الرصيد</th></tr></thead><tbody>{(data.accounts||[]).map((r:any)=><tr key={r.code} className="border-b border-slate-100"><td className="px-3 py-2 font-semibold">{r.code} — {r.name}</td><td className="px-3 py-2 text-xs text-slate-500">{r.subclassification||"غير مصنف"}</td><td className="px-3 py-2 tabular-nums">{money(r.debit)}</td><td className="px-3 py-2 tabular-nums">{money(r.credit)}</td><td className="px-3 py-2 tabular-nums">{money(r.balance)}</td></tr>)}</tbody></table></div></div>}
function Income({data,terms}:{data:any;terms:any}){return <div className="max-w-4xl"><Row label={terms.revenue||labels.revenue} value={data.revenue}/><Row label={terms.cogs||labels.cogs} value={data.cogs}/><Row label="مجمل الربح" value={data.gross_profit} strong/><Row label={terms.operating_expenses||labels.operating_expenses} value={data.operating_expenses}/><Row label={labels.other_income} value={data.other_income}/><Row label="EBITDA" value={data.ebitda} strong/><Row label={labels.depreciation_amortization} value={data.depreciation_amortization}/><Row label="EBIT" value={data.ebit} strong/><Row label={labels.finance_cost} value={data.finance_cost}/><Row label={labels.other_expenses} value={data.other_expenses}/><Row label="الربح قبل الضريبة" value={data.ebt} strong/><Row label={labels.tax} value={data.tax}/><Row label="صافي الربح" value={data.net_income} strong/></div>}
function OCIView({data}:{data:OCI|null}){if(!data)return <Empty text="لا توجد بيانات للدخل الشامل الآخر في الفترة الحالية."/>;return <div className="grid gap-6 lg:grid-cols-2"><Section title="الفترة"><>{(data.period.rows||[]).map((r:any)=><Row key={r.code} label={`${r.code} — ${r.name}`} value={r.amount}/>)}<Row label="إجمالي الدخل الشامل الآخر" value={data.period.total} strong/></></Section><Section title="من بداية السنة المالية"><>{(data.ytd.rows||[]).map((r:any)=><Row key={r.code} label={`${r.code} — ${r.name}`} value={r.amount}/>)}<Row label="إجمالي الدخل الشامل الآخر YTD" value={data.ytd.total} strong/></></Section></div>}
function CashFlow({data}:{data:any}){const op=data.operating||{},inv=data.investing||{},fin=data.financing||{};return <div className="grid gap-6 lg:grid-cols-3"><Section title="الأنشطة التشغيلية"><Row label={data.method==="direct"?"المقبوضات التشغيلية":"صافي الربح"} value={data.method==="direct"?op.cash_inflows:op.net_income}/>{data.method==="direct"?<Row label="المدفوعات التشغيلية" value={-Number(op.cash_outflows||0)}/>:<><Row label="الإهلاك والاستهلاك" value={op.depreciation_amortization}/><Row label="تسويات التشغيل ورأس المال العامل" value={op.working_capital_change}/></>}<Row label="صافي التدفق التشغيلي" value={op.net_operating_cash_flow} strong/></Section><Section title="الأنشطة الاستثمارية"><Row label="صافي التدفق الاستثماري" value={inv.net_cash_flow} strong/></Section><Section title="الأنشطة التمويلية"><Row label="صافي التدفق التمويلي" value={fin.net_cash_flow} strong/></Section><div className="lg:col-span-3 grid gap-3 sm:grid-cols-3"><Metric label="نقدية أول الفترة" value={data.opening_cash}/><Metric label="التغير في النقدية" value={data.net_change}/><Metric label="نقدية آخر الفترة" value={data.closing_cash}/></div><div className={`lg:col-span-3 rounded-xl p-4 text-sm font-bold ${data.reconciliation_difference===0?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>مطابقة النقدية: {money(data.reconciliation_difference)} {data.reconciliation_difference===0?"✓":"— تحتاج مراجعة"}{data.method==="direct"&&data.direct_data_quality!=="complete"&&<span> · الطريقة المباشرة تحتاج استكمال تصنيف بعض الحركات.</span>}</div></div>}
function Equity({data}:{data:any}){return <div className="grid gap-6 lg:grid-cols-2"><Section title="التغير في حقوق الملكية"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-3 py-3">البند</th><th className="px-3 py-3">افتتاحي</th><th className="px-3 py-3">الحركة</th><th className="px-3 py-3">ختامي</th></tr></thead><tbody>{(data.rows||[]).map((r:any)=><tr key={r.code} className="border-b border-slate-100"><td className="px-3 py-3 font-semibold">{r.code} — {r.name}</td><td className="px-3 py-3 tabular-nums">{money(r.opening)}</td><td className="px-3 py-3 tabular-nums">{money(r.movement)}</td><td className="px-3 py-3 tabular-nums">{money(r.closing)}</td></tr>)}</tbody></table></div></Section><Section title="النتيجة المرتبطة بقائمة الدخل"><Row label="صافي الربح YTD" value={data.ytd_net_income} strong/><Row label="حقوق الملكية المعروضة" value={data.displayed_closing_equity} strong/></Section></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm text-slate-500">{text}</div>}
