"use client";

import { useCallback, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Scenario={id:string;name:string;description:string|null;scenario_type:string;status:string;base_version_id:string|null};
type Period={id:string;period_start:string;period_end:string};
type Account={id:string;code:string;name:string};
type Version={id:string;name:string;version_type:string;status:string};
type Adjustment={id:string;scenario_id:string;financial_period_id:string;account_id:string;adjustment_type:string;adjustment_value:number;notes:string|null};
type Payload={scenarios:Scenario[];adjustments:Adjustment[];periods:Period[];accounts:Account[];base_versions:Version[]};
type Results={scenario:{id:string;name:string;type:string;status:string};base_version:{id:string;name:string;type:string;status:string};metrics:Record<string,number>;rows:Array<{period_id:string;account_id:string;code:string;name:string;account_type:string|null;base:number;adjustment:number;scenario:number}>};
const labels:Record<string,string>={what_if:"ماذا لو",upside:"سيناريو متفائل",downside:"سيناريو متحفظ",stress:"ضغط"};
const money=(v:number)=>new Intl.NumberFormat("ar-SA",{maximumFractionDigits:0}).format(v/100);
export default function ScenariosPage(){
 const supabase=getSupabaseBrowserClient(); const [org,setOrg]=useState<string|null>(null); const [data,setData]=useState<Payload>({scenarios:[],adjustments:[],periods:[],accounts:[],base_versions:[]}); const [scenarioId,setScenarioId]=useState(""); const [baseVersion,setBaseVersion]=useState(""); const [name,setName]=useState(""); const [type,setType]=useState("what_if"); const [period,setPeriod]=useState(""); const [account,setAccount]=useState(""); const [adjType,setAdjType]=useState("percentage"); const [value,setValue]=useState(""); const [results,setResults]=useState<Results|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const load=useCallback(async(id:string)=>{setError("");const {data:d,error:e}=await supabase.rpc("get_scenarios_workspace",{p_organization_id:id});if(e){setError(e.message);return}const x=d??{};const next={scenarios:x.scenarios??[],adjustments:x.adjustments??[],periods:x.periods??[],accounts:x.accounts??[],base_versions:x.base_versions??[]};setData(next);setScenarioId(s=>s||next.scenarios?.[0]?.id||"")},[supabase]);
 useEffect(()=>{const id=window.sessionStorage.getItem("activeOrganizationId");if(id){setOrg(id);void load(id)}else setError("لم يتم تحديد الشركة الحالية.")},[load]);
 const create=async()=>{if(!org||!name.trim()||!baseVersion)return;setBusy(true);setError("");const {data:d,error:e}=await supabase.rpc("create_scenario",{p_organization_id:org,p_name:name.trim(),p_scenario_type:type,p_base_version_id:baseVersion});if(e)setError(e.message);else{setName("");setScenarioId(d as string);await load(org)}setBusy(false)};
 const add=async()=>{if(!org||!scenarioId||!period||!account||!value.trim())return;setBusy(true);setError("");const {error:e}=await supabase.rpc("upsert_scenario_adjustment",{p_organization_id:org,p_scenario_id:scenarioId,p_financial_period_id:period,p_account_id:account,p_adjustment_type:adjType,p_adjustment_value:Number(value),p_notes:null});if(e)setError(e.message);else{setValue("");await load(org);await calculate(scenarioId)}setBusy(false)};
 const calculate=async(id:string)=>{if(!org||!id)return;const {data:d,error:e}=await supabase.rpc("get_scenario_results",{p_organization_id:org,p_scenario_id:id});if(e)setError(e.message);else setResults(d as Results)};
 const current=data.scenarios.find(s=>s.id===scenarioId); const rows=data.adjustments.filter(a=>a.scenario_id===scenarioId); const metricLabels:[string,string][]=[['base_revenue','الإيرادات الأساسية'],['scenario_revenue','إيرادات السيناريو'],['base_gross_profit','مجمل الربح الأساسي'],['scenario_gross_profit','مجمل ربح السيناريو'],['base_ebitda','EBITDA الأساسي'],['scenario_ebitda','EBITDA السيناريو'],['scenario_net_income','صافي الربح السيناريو']];
 return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-[1500px] px-4 py-6"><p className="text-xs font-bold tracking-[.16em] text-slate-400">SCENARIOS ENGINE</p><h1 className="mt-2 text-2xl font-bold text-slate-950">السيناريوهات</h1><p className="mt-1 text-sm text-slate-500">اختبر أثر التغييرات على الخطة المالية قبل اتخاذ القرار.</p></div></header><div className="mx-auto max-w-[1500px] space-y-6 px-4 py-6">{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">إنشاء سيناريو</h2><div className="mt-4 grid gap-3 md:grid-cols-[1.4fr_1.1fr_1.4fr_auto]"><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: انخفاض المبيعات 10٪"/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="what_if">ماذا لو</option><option value="upside">متفائل</option><option value="downside">متحفظ</option><option value="stress">ضغط</option></select><select className="input" value={baseVersion} onChange={e=>setBaseVersion(e.target.value)}><option value="">الخطة الأساسية</option>{data.base_versions.map(v=><option key={v.id} value={v.id}>{v.name} · {v.version_type} · {v.status}</option>)}</select><button disabled={busy||!name.trim()||!baseVersion} onClick={()=>void create()} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">إنشاء</button></div></section>
 <section className="grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold">السيناريوهات</h2><div className="mt-3 space-y-2">{data.scenarios.length===0?<p className="p-3 text-sm text-slate-500">لا توجد سيناريوهات.</p>:data.scenarios.map(s=><button key={s.id} onClick={()=>{setScenarioId(s.id);void calculate(s.id)}} className={`w-full rounded-xl border p-4 text-right ${s.id===scenarioId?"border-slate-900 bg-slate-50":"border-slate-200"}`}><div className="font-bold">{s.name}</div><div className="mt-1 text-xs text-slate-500">{labels[s.scenario_type]??s.scenario_type} · {s.status}</div></button>)}</div></aside>
 <div className="space-y-6">{current&&<><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{current.name}</h2><p className="mt-1 text-sm text-slate-500">{labels[current.scenario_type]??current.scenario_type}</p></div><button disabled={busy} onClick={()=>void calculate(current.id)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">إعادة الحساب</button></div><div className="mt-5 grid gap-3 md:grid-cols-4"><select className="input" value={period} onChange={e=>setPeriod(e.target.value)}><option value="">الفترة</option>{data.periods.map(p=><option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><select className="input" value={account} onChange={e=>setAccount(e.target.value)}><option value="">الحساب المتأثر</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select><select className="input" value={adjType} onChange={e=>setAdjType(e.target.value)}><option value="percentage">نسبة مئوية</option><option value="absolute">قيمة ثابتة</option></select><div className="flex gap-2"><input className="input" inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} placeholder="القيمة"/><button disabled={busy||!period||!account||!value} onClick={()=>void add()} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">إضافة</button></div></div></section>
 {results&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">نتيجة السيناريو</h2><p className="mt-1 text-sm text-slate-500">مبنية على {results.base_version.name}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{results.base_version.type}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metricLabels.map(([k,l])=><div key={k} className="rounded-xl border border-slate-200 p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-lg font-bold">{money(results.metrics[k]??0)} ر.س</p></div>)}</div></section>}
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">تعديلات السيناريو</h2><p className="mt-1 text-sm text-slate-500">{rows.length} تعديل</p></div>{rows.length===0?<div className="p-8 text-center text-sm text-slate-500">لم تتم إضافة تعديلات.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500"><tr><th className="px-5 py-3">الفترة</th><th className="px-5 py-3">الحساب</th><th className="px-5 py-3">نوع التعديل</th><th className="px-5 py-3">القيمة</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="px-5 py-4">{data.periods.find(p=>p.id===r.financial_period_id)?.period_start??"—"}</td><td className="px-5 py-4">{data.accounts.find(a=>a.id===r.account_id)?.code??"—"}</td><td className="px-5 py-4">{r.adjustment_type==='percentage'?"نسبة مئوية":"قيمة ثابتة"}</td><td className="px-5 py-4 font-bold">{r.adjustment_value}</td></tr>)}</tbody></table></div>}</section></>}</div></section></div></main>;
}