"use client";
import { useState } from "react";

type Option={id:string;code?:string;name:string};
export type ReportDimensionFilterState={branch:string;department:string;costCenter:string;region:string;product:string;project:string;account:string};
export const emptyReportDimensionFilters:ReportDimensionFilterState={branch:"",department:"",costCenter:"",region:"",product:"",project:"",account:""};
type Options={branches:Option[];departments:Option[];cost_centers:Option[];regions:Option[];products:Option[];projects:Option[];accounts:Option[]};
const fieldsConfig:[keyof ReportDimensionFilterState,string,string,Option[]][]=[];
export function ReportDimensionFilters({options,filters,setFilters}:{options:Options;filters:ReportDimensionFilterState;setFilters:(v:ReportDimensionFilterState)=>void}){const[open,setOpen]=useState(false);const fields:[keyof ReportDimensionFilterState,string,string,Option[]][]=[["branch","الفرع","Branch",options.branches],["department","القسم","Department",options.departments],["costCenter","مركز التكلفة","Cost center",options.cost_centers],["region","المنطقة","Region",options.regions],["product","المنتج","Product",options.products],["project","المشروع","Project",options.projects],["account","الحساب","Account",options.accounts]];const count=Object.values(filters).filter(Boolean).length;const clear=()=>setFilters(emptyReportDimensionFilters);return <div className="relative"><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)} className={`min-h-10 border px-3 text-xs font-bold transition ${count?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white text-slate-800 hover:bg-slate-50"}`}>الأبعاد{count?` · ${count}`:""}⌄</button>{open&&<div className="absolute right-0 top-11 z-50 w-[min(94vw,520px)] border border-slate-200 bg-white p-4 shadow-xl"><div className="mb-4 flex items-center justify-between border-b border-slate-100 pb-3"><div><p className="text-sm font-bold text-slate-950">أبعاد التقرير</p><p className="mt-1 text-[11px] text-slate-500">اختر البعد الذي تريد تقييد التقرير به</p></div><button type="button" onClick={clear} disabled={!count} className="text-[11px] font-bold text-slate-500 disabled:opacity-40">مسح الكل</button></div><div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label,english,items])=><label key={key} title={english} className="text-[11px] font-bold text-slate-600">{label}<select value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})} className="mt-1 min-h-10 w-full border border-slate-300 bg-white px-2 text-xs text-slate-900 outline-none focus:border-slate-950"><option value="">الكل</option>{items.map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select></label>)}</div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-[10px] text-slate-400">{count?`تم اختيار ${count} من 7 أبعاد`:"لم يتم اختيار أبعاد"}</span><button type="button" onClick={()=>setOpen(false)} className="min-h-9 bg-slate-950 px-4 text-xs font-bold text-white">تم</button></div></div>}</div>}
