"use client";
import { useEffect, useRef, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Option={id:string;code?:string;name:string};
export type ReportDimensionFilterState={branch:string;department:string;costCenter:string;region:string;product:string;project:string;account:string};
export const emptyReportDimensionFilters:ReportDimensionFilterState={branch:"",department:"",costCenter:"",region:"",product:"",project:"",account:""};
type Options={branches:Option[];departments:Option[];cost_centers:Option[];regions:Option[];products:Option[];projects:Option[];accounts:Option[]};
const fallback:Options={branches:[],departments:[],cost_centers:[],regions:[],products:[],projects:[],accounts:[]};
export function ReportDimensionFilters({options,filters,setFilters}:{options:Options;filters:ReportDimensionFilterState;setFilters:(v:ReportDimensionFilterState)=>void}){
 const[open,setOpen]=useState(false);const[dynamicOptions,setDynamicOptions]=useState<Options>(options||fallback);const[loading,setLoading]=useState(false);const requestRef=useRef(0);const supabase=getSupabaseBrowserClient();
 useEffect(()=>{setDynamicOptions(options||fallback)},[options]);
 useEffect(()=>{let cancelled=false;const organizationId=typeof window!=="undefined"?(window.sessionStorage.getItem("activeOrganizationId")||window.localStorage.getItem("activeOrganizationId")||""):"";if(!organizationId)return;const requestId=++requestRef.current;setLoading(true);void supabase.rpc("get_dynamic_reporting_filter_options",{p_organization_id:organizationId,p_branch_id:filters.branch||null,p_department_id:filters.department||null,p_cost_center_id:filters.costCenter||null,p_region_id:filters.region||null,p_product_id:filters.product||null,p_project_id:filters.project||null,p_account_id:filters.account||null}).then(({data,error})=>{if(cancelled||requestId!==requestRef.current)return;if(!error&&data)setDynamicOptions({...fallback,...data});setLoading(false)});return()=>{cancelled=true}},[filters.branch,filters.department,filters.costCenter,filters.region,filters.product,filters.project,filters.account]);
 const fields:[keyof ReportDimensionFilterState,string,string,Option[]][]=[["branch","الفرع","Branch",dynamicOptions.branches||[]],["department","القسم","Department",dynamicOptions.departments||[]],["costCenter","مركز التكلفة","Cost center",dynamicOptions.cost_centers||[]],["region","المنطقة","Region",dynamicOptions.regions||[]],["product","المنتج","Product",dynamicOptions.products||[]],["project","المشروع","Project",dynamicOptions.projects||[]],["account","الحساب","Account",dynamicOptions.accounts||[]]];const count=Object.values(filters).filter(Boolean).length;const clear=()=>setFilters(emptyReportDimensionFilters);
 return <div className="relative"><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)} className={`min-h-10 border px-3 text-xs font-bold transition ${count?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white text-slate-800 hover:bg-slate-50"}`}>الأبعاد{count?` · ${count}`:""}{loading?" · …":""}⌄</button>{open&&<div className="absolute right-0 top-11 z-50 w-[min(94vw,520px)] border border-slate-200 bg-white p-4 shadow-xl"><div className="mb-4 flex items-center justify-between border-b border-slate-100 pb-3"><div><p className="text-sm font-bold text-slate-950">أبعاد التقرير</p><p className="mt-1 text-[11px] text-slate-500">القوائم تتغير تلقائيًا حسب البيانات المنشورة والفلاتر المختارة</p></div><button type="button" onClick={clear} disabled={!count||loading} className="text-[11px] font-bold text-slate-500 disabled:opacity-40">مسح الكل</button></div><div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label,english,items])=><label key={key} title={english} className="text-[11px] font-bold text-slate-600">{label}<select value={filters[key]} disabled={loading} onChange={e=>setFilters({...filters,[key]:e.target.value})} className="mt-1 min-h-10 w-full border border-slate-300 bg-white px-2 text-xs text-slate-900 outline-none focus:border-slate-950 disabled:bg-slate-50"><option value="">الكل</option>{items.map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select></label>)}</div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-[10px] text-slate-400">{count?`تم اختيار ${count} من 7 أبعاد`:"لم يتم اختيار أبعاد"}</span><button type="button" onClick={()=>setOpen(false)} className="min-h-9 bg-slate-950 px-4 text-xs font-bold text-white">تم</button></div></div>}</div>;
}
