"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type AccessRow={permission_key?:string;granted?:boolean}; type NavItem=readonly[string,string,string,string]; type NavSection=readonly[string,readonly NavItem[]];
const navigation:NavSection[]=[
 ["نظرة عامة",[["screen.executive_dashboard.view","لوحة المؤشرات","/workspace/executive-dashboard","▦"]]],
 ["البيانات",[["screen.data.view","مركز البيانات المالية","/workspace/data","◈"],["screen.actuals.view","البيانات الفعلية","/workspace/actuals","✓"],["screen.trial_balance.view","ميزان المراجعة","/workspace/trial-balance","≡"]]],
 ["التخطيط",[["screen.budget.view","الميزانية","/workspace/budget","□"],["screen.forecast.view","التوقعات","/workspace/forecast","⌁"],["screen.scenarios.view","السيناريوهات","/workspace/scenarios","◇"]]],
 ["التحليل",[["screen.financial_analysis.view","التحليل المالي","/workspace/financial-analysis","◒"],["screen.variance.view","الفروقات","/workspace/variance","±"],["screen.cash.view","التدفق النقدي","/workspace/cash","↗"]]],
 ["التقارير",[["screen.financial_statements.view","القوائم المالية","/workspace/financial-statements","▤"],["screen.reports.view","التقارير","/workspace/reports","▥"],["screen.group_reporting.view","تقارير المجموعة","/workspace/group-reporting","◎"],["screen.financial_statements.view","الزكاة وضريبة الدخل","/workspace/tax-zakat","٪"]]],
 ["الإدارة",[["screen.ai_analyst.view","المحلل المالي","/workspace/ai-analyst","✦"],["screen.dimensions.view","الأبعاد","/workspace/dimensions","⊞"],["screen.team.view","الفريق والصلاحيات","/workspace/team","♙"],["screen.audit.view","سجل العمليات","/workspace/audit","◷"],["screen.company_profile.view","ملف الشركة","/workspace/company-profile","○"]]]
];
function NavLink({item,allowed,pathname}:{item:NavItem;allowed:Set<string>;pathname:string}){const enabled=allowed.has(item[0]);const active=pathname===item[2]||pathname.startsWith(`${item[2]}/`);const cls=`group flex min-h-10 items-center gap-3 rounded-lg px-3 text-[13px] transition ${active?"bg-slate-900 font-bold text-white shadow-sm":"font-semibold text-slate-600 hover:bg-slate-50 hover:text-slate-950"}`;if(!enabled)return <div aria-disabled="true" title={`ليس لديك صلاحية الدخول إلى ${item[1]}`} className={`${cls} cursor-not-allowed text-slate-300 hover:bg-transparent hover:text-slate-300`}><span className="w-5 text-center text-xs">{item[3]}</span><span className="truncate">{item[1]}</span><span className="mr-auto text-[10px]">🔒</span></div>;return <Link href={item[2]} title={item[1]} aria-current={active?"page":undefined} className={cls}><span className={`flex h-5 w-5 items-center justify-center text-xs ${active?"text-slate-300":"text-slate-400 group-hover:text-slate-700"}`}>{item[3]}</span><span className="truncate">{item[1]}</span></Link>}
export default function WorkspaceSidebar(){const pathname=usePathname()||"/workspace";const[access,setAccess]=useState<AccessRow[]>([]);useEffect(()=>{const s=getSupabaseBrowserClient();let alive=true;async function load(){const{data:user}=await s.auth.getUser();if(!user.user)return;const id=window.sessionStorage.getItem("activeOrganizationId");if(!id)return;const{data}=await s.rpc("get_my_org_access",{p_organization_id:id});if(alive)setAccess((data??[]) as AccessRow[])}void load();return()=>{alive=false}},[pathname]);const allowed=useMemo(()=>new Set(access.filter(x=>x.granted===true).map(x=>x.permission_key).filter(Boolean) as string[]),[access]);return <aside className="fixed bottom-0 right-0 top-[84px] z-40 hidden w-[264px] overflow-y-auto border-l border-slate-200 bg-white lg:block"><div className="px-4 pb-4 pt-5"><div className="mb-5 rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="eyebrow">FINANCIAL WORKSPACE</p><p className="mt-1 text-sm font-bold text-slate-950">مساحة العمل</p><p className="mt-1 text-[11px] leading-5 text-slate-500">بياناتك، خطتك، وتحليلك في مكان واحد</p></div><nav className="space-y-5">{navigation.map(([section,items])=><section key={section}><h2 className="px-3 pb-2 text-[10px] font-extrabold tracking-wide text-slate-400">{section}</h2><div className="space-y-0.5">{items.map(item=><NavLink key={item[2]} item={item} allowed={allowed} pathname={pathname}/>)}</div></section>)}</nav></div></aside>}
