"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Company = { id: string; name: string; base_currency: string; role: string; role_key: string };
type AccessRow = { permission_key?: string; granted?: boolean };
type NavItem = readonly [string, string, string];
const roles: Record<string, string> = { company_admin: "مدير النظام", admin: "مدير النظام", owner: "المالك", ceo: "الرئيس التنفيذي", cfo: "المدير المالي", finance_manager: "مدير مالي", fpa_analyst: "محلل FP&A", accountant: "محاسب", department_manager: "مدير قسم", sales_manager: "مدير مبيعات", hr_manager: "مدير الموارد البشرية", procurement_manager: "مدير المشتريات", operations_manager: "مدير العمليات", viewer: "مطلع", executive_director: "مدير تنفيذي", planner: "محلل FP&A" };
const navigation: NavItem[] = [
  ["screen.executive_dashboard.view", "لوحة المؤشرات", "/workspace/executive-dashboard"], ["screen.accounts.view", "إدخال البيانات", "/workspace/data/accounts"], ["screen.data_monitoring.view", "مراقبة مصادر البيانات", "/workspace/data-monitoring"], ["screen.group_reporting.view", "تقارير المجموعة", "/workspace/group-reporting"], ["screen.trial_balance.view", "ميزان المراجعة", "/workspace/trial-balance"], ["screen.financial_statements.view", "القوائم المالية", "/workspace/financial-statements"], ["screen.financial_analysis.view", "التحليل المالي", "/workspace/financial-analysis"], ["screen.budget.view", "الميزانية", "/workspace/budget"], ["screen.forecast.view", "التوقعات", "/workspace/forecast"], ["screen.variance.view", "الفروقات", "/workspace/variance"], ["screen.cash.view", "التدفق النقدي", "/workspace/cash"], ["screen.scenarios.view", "السيناريوهات", "/workspace/scenarios"], ["screen.dimensions.view", "الأبعاد", "/workspace/dimensions"], ["screen.reports.view", "التقارير", "/workspace/reports"], ["screen.ai_analyst.view", "المحلل المالي الذكي", "/workspace/ai-analyst"], ["screen.team.view", "الفريق والصلاحيات", "/workspace/team"], ["screen.audit.view", "سجل العمليات", "/workspace/audit"], ["screen.company_profile.view", "ملف الشركة", "/workspace/company-profile"]
];
const dataItems: NavItem[] = [["screen.data.view", "رفع البيانات", "/workspace/data/import"], ["screen.data.view", "الإدخال اليدوي", "/workspace/data/manual"], ["screen.connector_management.view", "ربط الأنظمة والمصادر", "/workspace/data-monitoring/connectors"]];
function NavLink({ item, allowed, pathname }: { item: NavItem; allowed: Set<string>; pathname: string }) { const enabled = allowed.has(item[0]); const active = pathname === item[2] || pathname.startsWith(`${item[2]}/`); return <Link href={item[2]} title={enabled ? item[1] : `ليس لديك صلاحية الدخول إلى ${item[1]}`} aria-current={active ? "page" : undefined} className={`flex items-center justify-between border-b border-slate-100 px-3 py-2.5 text-sm ${active ? "bg-slate-50 font-bold text-slate-950" : enabled ? "font-semibold text-slate-700 hover:bg-slate-50" : "text-slate-400 hover:bg-slate-50"}`}><span>{item[1]}</span><span aria-hidden="true">{enabled ? "›" : "🔒"}</span></Link>; }
export default function WorkspaceSidebar() {
  const router = useRouter(); const pathname = usePathname() || "/workspace"; const [company, setCompany] = useState<Company | null>(null); const [companies, setCompanies] = useState<Company[]>([]); const [access, setAccess] = useState<AccessRow[]>([]); const [companyOpen, setCompanyOpen] = useState(false); const [dataOpen] = useState(true); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  useEffect(() => { const supabase = getSupabaseBrowserClient(); let alive = true; async function load() { const { data: user } = await supabase.auth.getUser(); if (!user.user) return; const { data } = await supabase.rpc("get_my_workspaces"); if (!alive || !data?.length) return; const list = data as Company[]; const activeId = window.sessionStorage.getItem("activeOrganizationId"); const selected = list.find((item) => item.id === activeId) ?? list[0]; let ids: string[] = []; try { const raw = window.sessionStorage.getItem("selectedOrganizationIds"); const parsed = raw ? JSON.parse(raw) : []; if (Array.isArray(parsed)) ids = parsed.filter((id): id is string => typeof id === "string" && list.some((item) => item.id === id)); } catch { ids = []; } if (!ids.length) ids = [selected.id]; const { data: accessRows } = await supabase.rpc("get_my_org_access", { p_organization_id: selected.id }); if (!alive) return; window.sessionStorage.setItem("activeOrganizationId", selected.id); window.sessionStorage.setItem("selectedOrganizationIds", JSON.stringify(ids)); setCompany(selected); setCompanies(list); setSelectedIds(ids); setAccess((accessRows ?? []) as AccessRow[]); } void load(); return () => { alive = false; }; }, [pathname]);
  const allowed = useMemo(() => new Set(access.filter((row) => row.granted === true).map((row) => row.permission_key).filter(Boolean) as string[]), [access]); const enabledCount = navigation.filter((item) => allowed.has(item[0])).length;
  function toggleCompany(id: string) { setSelectedIds((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]); }
  function applySelection() { if (!company || !selectedIds.length) return; const active = selectedIds.includes(company.id) ? company.id : selectedIds[0]; window.sessionStorage.setItem("activeOrganizationId", active); window.sessionStorage.setItem("selectedOrganizationIds", JSON.stringify(selectedIds)); setCompanyOpen(false); window.location.reload(); }
  function selectCompany(id: string) { if (!companies.some((item) => item.id === id)) return; window.sessionStorage.setItem("activeOrganizationId", id); window.sessionStorage.setItem("selectedOrganizationIds", JSON.stringify([id])); setCompanyOpen(false); window.location.reload(); }
  return <aside className="sticky top-0 z-30 h-screen min-h-screen self-start overflow-y-auto overscroll-contain border-l border-slate-200 bg-white p-3 lg:col-start-1 lg:row-start-1 max-lg:relative max-lg:h-auto max-lg:min-h-0 max-lg:border-l-0 max-lg:border-b"><div className="mb-3 border-b border-slate-100 px-3 pb-3"><p className="text-[10px] font-bold tracking-[.16em] text-slate-400">FP&A WORKSPACE</p><p className="mt-1 text-sm font-bold">كل الشاشات</p><p className="mt-1 text-xs text-slate-400">المتاح لك: {enabledCount} من {navigation.length}</p></div><nav><NavLink item={navigation[0]} allowed={allowed} pathname={pathname}/><div className="border-b border-slate-100"><Link href="/workspace/data/accounts" title="دليل الحسابات" className={`flex items-center justify-between px-3 py-2.5 text-sm ${pathname.startsWith("/workspace/data") ? "bg-slate-50 font-bold text-slate-950" : allowed.has("screen.accounts.view") ? "font-bold text-slate-700 hover:bg-slate-50" : "text-slate-400 hover:bg-slate-50"}`}><span>إدخال البيانات</span><span aria-hidden="true">{allowed.has("screen.accounts.view") ? "›" : "🔒"}</span></Link>{dataOpen && <div className="mr-3 border-r border-slate-200 pr-2">{dataItems.map((item, index) => <NavLink key={`${item[2]}-${index}`} item={item} allowed={allowed} pathname={pathname}/>)}</div>}</div>{navigation.slice(2).map((item) => <NavLink key={item[2]} item={item} allowed={allowed} pathname={pathname}/>)}</nav>{company && <div className="mt-4 border-t border-slate-100 pt-3"><button type="button" onClick={() => setCompanyOpen((value) => !value)} className="w-full border border-slate-200 px-3 py-2 text-right hover:bg-slate-50" aria-expanded={companyOpen}><span className="block text-[11px] text-slate-400">الشركة الحالية</span><span className="mt-1 block truncate text-sm font-bold text-slate-900">{company.name} ▾</span></button>{companyOpen && <div className="mt-2 border border-slate-200 bg-white p-2 shadow-lg">{companies.map((item) => <div key={item.id} className="flex items-center gap-2 border-b border-slate-100 py-2 last:border-0"><button type="button" onClick={() => selectCompany(item.id)} className="min-w-0 flex-1 text-right"><span className="block truncate text-sm font-semibold">{item.name}</span><span className="text-[11px] text-slate-400">{item.id === company.id ? "الشركة الحالية" : roles[item.role_key] ?? item.role_key}</span></button><input type="checkbox" aria-label={`تحديد ${item.name}`} checked={selectedIds.includes(item.id)} onChange={() => toggleCompany(item.id)} className="h-4 w-4 accent-slate-900"/></div>)}<div className="mt-2 flex items-center justify-between"><button type="button" onClick={() => router.push("/start/new")} className="text-xs font-bold">+ شركة</button><button type="button" onClick={applySelection} disabled={!selectedIds.length} className="bg-slate-950 px-3 py-1.5 text-xs font-bold text-white disabled:opacity-40">تطبيق</button></div></div>}</div>}</aside>;
}
