"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Source = { id:string; source_type:string; system_name:string|null; status:string; sync_mode:string; last_sync_at:string|null; last_success_at:string|null; last_error_at:string|null; last_error_message:string|null; health_status:string };
type Run = { id:string; data_source_id:string; system_name:string|null; started_at:string; completed_at:string|null; status:string; records_received:number; records_accepted:number; records_rejected:number; error_count:number; warning_count:number; error_message:string|null };
type Summary = { sources_total:number; sources_healthy:number; sources_stale:number; sources_error:number; sync_runs_24h:number; failed_runs_24h:number; rejected_records_24h:number };

const sourceLabels:Record<string,string>={manual:"يدوي",excel_csv:"Excel / CSV",integration:"تكامل",api:"API",database:"قاعدة بيانات",other:"أخرى"};
const statusLabels:Record<string,string>={active:"نشط",paused:"متوقف مؤقتًا",error:"خطأ",disconnected:"غير متصل"};
const healthLabels:Record<string,string>={healthy:"سليم",stale:"متأخر",never:"لم تتم مزامنته"};
const runLabels:Record<string,string>={running:"جارٍ",succeeded:"نجح",partial:"جزئي",failed:"فشل"};
function fmt(value:string|null){return value?new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—"}
function age(value:string|null){if(!value)return "لم تتم مزامنة ناجحة بعد";const mins=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(mins<60)return `منذ ${mins} دقيقة`;const h=Math.floor(mins/60);if(h<24)return `منذ ${h} ساعة`;return `منذ ${Math.floor(h/24)} يوم`}

export default function DataMonitoringPage(){
 const [summary,setSummary]=useState<Summary|null>(null);const [sources,setSources]=useState<Source[]>([]);const [runs,setRuns]=useState<Run[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let alive=true;const supabase=getSupabaseBrowserClient();async function load(){setLoading(true);setError("");const {data:userData}=await supabase.auth.getUser();if(!userData.user){window.location.assign("/login?next=/workspace/data-monitoring");return}const org=window.sessionStorage.getItem("activeOrganizationId");if(!org){window.location.assign("/start");return}const {data,error:rpcError}=await supabase.rpc("get_data_monitoring",{p_organization_id:org});if(rpcError){if(alive)setError(rpcError.message);setLoading(false);return}if(alive){setSummary(data?.summary??null);setSources(data?.sources??[]);setRuns(data?.recent_sync_runs??[]);setLoading(false)}}void load();return()=>{alive=false}},[]);
 const cards=useMemo(()=>summary?[['مصادر البيانات',summary.sources_total],['مصادر سليمة',summary.sources_healthy],['مصادر متأخرة',summary.sources_stale],['أخطاء المصادر',summary.sources_error],['مزامنات آخر 24 ساعة',summary.sync_runs_24h],['مزامنات فاشلة',summary.failed_runs_24h],['سجلات مرفوضة',summary.rejected_records_24h]]:[],[summary]);
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-5 sm:px-6 lg:px-8"><div><p className="text-[11px] font-bold tracking-[0.14em] text-slate-400">DATA MONITORING</p><h1 className="mt-1 text-xl font-bold sm:text-2xl">مراقبة مصادر البيانات</h1></div><Link href="/workspace" className="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50">مساحة العمل</Link></div></header>
 <section className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-9"><div className="mb-7"><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">حالة البيانات أمام الإدارة المالية</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">مراقبة اتصال مصادر البيانات وحداثة آخر مزامنة وجودة عمليات النقل. لا يعرض النظام حالة اتصال غير مؤكدة أو بيانات وهمية.</p></div>
 {error?<div className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm leading-7 text-red-700">تعذر تحميل مراقبة البيانات: {error}</div>:loading?<div className="rounded-xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">جارٍ تحميل حالة مصادر البيانات…</div>:<>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{cards.map(([label,value])=><div key={label} className="border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>)}</div>
 <div className="mt-8 overflow-hidden border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h3 className="font-bold">مصادر البيانات</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">المصدر</th><th className="px-5 py-3">النوع</th><th className="px-5 py-3">الحالة</th><th className="px-5 py-3">وضع المزامنة</th><th className="px-5 py-3">آخر مزامنة ناجحة</th><th className="px-5 py-3">الصحة</th><th className="px-5 py-3">آخر خطأ</th></tr></thead><tbody className="divide-y divide-slate-100">{sources.length?sources.map(s=><tr key={s.id}><td className="px-5 py-4 font-semibold">{s.system_name||"مصدر بدون اسم"}</td><td className="px-5 py-4 text-slate-600">{sourceLabels[s.source_type]??s.source_type}</td><td className="px-5 py-4">{statusLabels[s.status]??s.status}</td><td className="px-5 py-4 text-slate-600">{s.sync_mode}</td><td className="px-5 py-4"><div>{fmt(s.last_success_at)}</div><div className="mt-1 text-xs text-slate-400">{age(s.last_success_at)}</div></td><td className="px-5 py-4 font-semibold">{healthLabels[s.health_status]??s.health_status}</td><td className="max-w-[260px] px-5 py-4 text-xs text-slate-500">{s.last_error_message||"—"}</td></tr>):<tr><td colSpan={7} className="px-5 py-10 text-center text-slate-400">لا توجد مصادر بيانات مرتبطة بالشركة حتى الآن.</td></tr>}</tbody></table></div></div>
 <div className="mt-8 overflow-hidden border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h3 className="font-bold">آخر عمليات المزامنة</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">المصدر</th><th className="px-5 py-3">وقت البدء</th><th className="px-5 py-3">الحالة</th><th className="px-5 py-3">مستلمة</th><th className="px-5 py-3">مقبولة</th><th className="px-5 py-3">مرفوضة</th><th className="px-5 py-3">أخطاء / تحذيرات</th></tr></thead><tbody className="divide-y divide-slate-100">{runs.length?runs.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.system_name||"مصدر بدون اسم"}</td><td className="px-5 py-4 text-slate-600">{fmt(r.started_at)}</td><td className="px-5 py-4 font-semibold">{runLabels[r.status]??r.status}</td><td className="px-5 py-4">{r.records_received}</td><td className="px-5 py-4">{r.records_accepted}</td><td className="px-5 py-4">{r.records_rejected}</td><td className="px-5 py-4">{r.error_count} / {r.warning_count}</td></tr>):<tr><td colSpan={7} className="px-5 py-10 text-center text-slate-400">لا توجد عمليات مزامنة بعد.</td></tr>}</tbody></table></div></div>
 </>}</section></main>;
}
