"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Source={id:string;source_type:string;system_name:string|null;status:string;sync_mode:string;last_success_at:string|null;last_error_message:string|null;health_status:string};
type Run={id:string;data_source_id:string;system_name:string|null;started_at:string;status:string;records_received:number;records_accepted:number;records_rejected:number;error_count:number;warning_count:number};
type Summary={sources_total:number;sources_healthy:number;sources_stale:number;sources_error:number;sync_runs_24h:number;failed_runs_24h:number;rejected_records_24h:number};
const sourceLabels:Record<string,string>={manual:"يدوي",excel_csv:"Excel / CSV",integration:"تكامل",api:"API",database:"قاعدة بيانات",other:"أخرى"};
const statusLabels:Record<string,string>={active:"نشط",paused:"متوقف مؤقتًا",error:"خطأ",disconnected:"غير متصل"};
const healthLabels:Record<string,string>={healthy:"سليم",stale:"متأخر",never:"لم تتم مزامنته",error:"خطأ"};
const runLabels:Record<string,string>={running:"جارٍ",succeeded:"نجح",partial:"جزئي",failed:"فشل"};
function fmt(v:string|null){return v?new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—"}
function age(v:string|null){if(!v)return "لم تتم مزامنة ناجحة بعد";const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<60)return `منذ ${m} دقيقة`;const h=Math.floor(m/60);if(h<24)return `منذ ${h} ساعة`;return `منذ ${Math.floor(h/24)} يوم`}
export default function DataMonitoringPage(){
 const supabase=getSupabaseBrowserClient();const[summary,setSummary]=useState<Summary|null>(null);const[sources,setSources]=useState<Source[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[canManage,setCanManage]=useState(false);const[openCreate,setOpenCreate]=useState(false);const[name,setName]=useState("");const[type,setType]=useState("excel_csv");const[mode,setMode]=useState("manual");const[connectionKey,setConnectionKey]=useState("");
 async function load(){setLoading(true);setError("");const{data:userData}=await supabase.auth.getUser();if(!userData.user){window.location.assign("/login?next=/workspace/data-monitoring");return}const org=window.sessionStorage.getItem("activeOrganizationId");if(!org){window.location.assign("/start");return}const[{data,error:rpcError},{data:accessRows}]=await Promise.all([supabase.rpc("get_data_monitoring",{p_organization_id:org}),supabase.rpc("get_my_org_access",{p_organization_id:org})]);if(rpcError){setError(rpcError.message);setLoading(false);return}setSummary(data?.summary??null);setSources(data?.sources??[]);setRuns(data?.recent_sync_runs??[]);setCanManage((accessRows??[]).some((x:{permission_key?:string;granted?:boolean})=>x.permission_key==="data_source.manage"&&x.granted===true));setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function manage(id:string|null,action:string,createPayload?:{source_type:string;system_name:string;connection_key:string|null;sync_mode:string}){const org=window.sessionStorage.getItem("activeOrganizationId");if(!org)return;setBusy(id?`${id}:${action}`:action);setError("");setNotice("");const args={p_organization_id:org,p_data_source_id:id,p_action:action,p_source_type:createPayload?.source_type??null,p_system_name:createPayload?.system_name??null,p_connection_key:createPayload?.connection_key??null,p_sync_mode:createPayload?.sync_mode??"manual"};const{error:e}=await supabase.rpc("manage_data_source",args);if(e)setError(e.message);else{setNotice(action==="delete"?"تم حذف مصدر البيانات":action==="pause"?"تم إيقاف المصدر مؤقتًا":action==="activate"?"تم تفعيل المصدر":action==="disconnect"?"تم فصل المصدر":"تم إنشاء مصدر البيانات");setOpenCreate(false);setName("");setConnectionKey("");await load()}setBusy("")}
 async function create(e:FormEvent){e.preventDefault();await manage(null,"create",{source_type:type,system_name:name.trim(),connection_key:connectionKey.trim()||null,sync_mode:mode})}
 const cards=useMemo(()=>summary?[['مصادر البيانات',summary.sources_total],['مصادر سليمة',summary.sources_healthy],['مصادر متأخرة',summary.sources_stale],['أخطاء المصادر',summary.sources_error],['مزامنات 24 ساعة',summary.sync_runs_24h],['مزامنات فاشلة',summary.failed_runs_24h],['سجلات مرفوضة',summary.rejected_records_24h]]:[],[summary]);
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-5 sm:px-6 lg:px-8"><div><p className="text-[11px] font-bold tracking-[0.14em] text-slate-400">DATA MONITORING</p><h1 className="mt-1 text-xl font-bold sm:text-2xl">مراقبة مصادر البيانات</h1></div><div className="flex gap-2">{canManage&&<button onClick={()=>setOpenCreate(true)} className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">+ إضافة مصدر</button>}<Link href="/workspace" className="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">مساحة العمل</Link></div></div></header>
 <section className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-9"><div className="mb-7"><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">حالة البيانات أمام الإدارة المالية</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">راقب حداثة البيانات وحالة مصادرها وعمليات المزامنة. حالة المصدر لا تعني أن اتصالًا خارجيًا قائم بالفعل؛ التكامل لا يصبح نشطًا إلا بعد تنفيذ الموصل.</p></div>
 {notice&&<div className="mb-5 border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{notice}</div>}{error&&<div className="mb-5 border border-red-200 bg-red-50 p-4 text-sm text-red-700">تعذر تنفيذ العملية: {error}</div>}
 {loading?<div className="border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">جارٍ تحميل حالة مصادر البيانات…</div>:<>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{cards.map(([label,value])=><div key={label} className="border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>)}</div>
 <div className="mt-8 overflow-hidden border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h3 className="font-bold">مصادر البيانات</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">المصدر</th><th className="px-5 py-3">النوع</th><th className="px-5 py-3">الحالة</th><th className="px-5 py-3">وضع المزامنة</th><th className="px-5 py-3">آخر مزامنة ناجحة</th><th className="px-5 py-3">الصحة</th><th className="px-5 py-3">الإجراء</th></tr></thead><tbody className="divide-y divide-slate-100">{sources.length?sources.map(s=><tr key={s.id}><td className="px-5 py-4 font-semibold">{s.system_name||"مصدر بدون اسم"}</td><td className="px-5 py-4 text-slate-600">{sourceLabels[s.source_type]??s.source_type}</td><td className="px-5 py-4">{statusLabels[s.status]??s.status}</td><td className="px-5 py-4 text-slate-600">{s.sync_mode}</td><td className="px-5 py-4"><div>{fmt(s.last_success_at)}</div><div className="mt-1 text-xs text-slate-400">{age(s.last_success_at)}</div></td><td className="px-5 py-4 font-semibold">{healthLabels[s.health_status]??s.health_status}</td><td className="px-5 py-4">{canManage&&<div className="flex flex-wrap gap-2">{s.status==="active"&&<button disabled={!!busy} onClick={()=>void manage(s.id,"pause")} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-xs font-semibold disabled:opacity-50">إيقاف</button>}{s.status==="paused"&&<button disabled={!!busy} onClick={()=>void manage(s.id,"activate")} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-xs font-semibold disabled:opacity-50">تفعيل</button>}{s.status!=="disconnected"&&<button disabled={!!busy} onClick={()=>void manage(s.id,"disconnect")} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-xs font-semibold disabled:opacity-50">فصل</button>}<button disabled={!!busy} onClick={()=>{if(window.confirm("حذف مصدر البيانات؟ لا يمكن التراجع عن هذا الإجراء."))void manage(s.id,"delete")}} className="rounded-md border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-700 disabled:opacity-50">حذف</button></div>}</td></tr>):<tr><td colSpan={7} className="px-5 py-10 text-center text-slate-400">لا توجد مصادر بيانات مرتبطة بالشركة حتى الآن.</td></tr>}</tbody></table></div></div>
 <div className="mt-8 overflow-hidden border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h3 className="font-bold">آخر عمليات المزامنة</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">المصدر</th><th className="px-5 py-3">وقت البدء</th><th className="px-5 py-3">الحالة</th><th className="px-5 py-3">مستلمة</th><th className="px-5 py-3">مقبولة</th><th className="px-5 py-3">مرفوضة</th><th className="px-5 py-3">أخطاء / تحذيرات</th></tr></thead><tbody className="divide-y divide-slate-100">{runs.length?runs.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.system_name||"مصدر بدون اسم"}</td><td className="px-5 py-4 text-slate-600">{fmt(r.started_at)}</td><td className="px-5 py-4 font-semibold">{runLabels[r.status]??r.status}</td><td className="px-5 py-4">{r.records_received}</td><td className="px-5 py-4">{r.records_accepted}</td><td className="px-5 py-4">{r.records_rejected}</td><td className="px-5 py-4">{r.error_count} / {r.warning_count}</td></tr>):<tr><td colSpan={7} className="px-5 py-10 text-center text-slate-400">لا توجد عمليات مزامنة بعد.</td></tr>}</tbody></table></div></div>
 </>}</section>
 {openCreate&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={create} className="w-full max-w-lg border border-slate-200 bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">إضافة مصدر بيانات</h3><button type="button" onClick={()=>setOpenCreate(false)} className="text-slate-400">✕</button></div><p className="mt-2 text-sm leading-6 text-slate-500">هذا يسجل مصدر البيانات في المنصة. لا يتم إنشاء اتصال خارجي تلقائيًا.</p><label className="mt-5 block text-sm font-semibold">اسم المصدر<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full border border-slate-200 px-3 py-2.5 outline-none" placeholder="مثال: ERP الرئيسي"/></label><label className="mt-4 block text-sm font-semibold">نوع المصدر<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 w-full border border-slate-200 px-3 py-2.5 bg-white">{Object.entries(sourceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">وضع المزامنة<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-2 w-full border border-slate-200 px-3 py-2.5 bg-white"><option value="manual">يدوي</option><option value="scheduled">مجدول</option><option value="near_real_time">شبه لحظي</option><option value="real_time">لحظي</option></select></label><label className="mt-4 block text-sm font-semibold">معرّف الاتصال الداخلي<input value={connectionKey} onChange={e=>setConnectionKey(e.target.value)} className="mt-2 w-full border border-slate-200 px-3 py-2.5 outline-none" placeholder="اختياري — لا تضع كلمة مرور أو مفتاحًا سريًا"/></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setOpenCreate(false)} className="border border-slate-200 px-4 py-2.5 text-sm font-semibold">إلغاء</button><button disabled={!!busy} type="submit" className="bg-slate-950 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy==="create"?"جارٍ الحفظ…":"حفظ المصدر"}</button></div></form></div>}
 </main>;
}
