"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Company={id:string;name:string;role:string;role_key:string};
const roles:Record<string,string>={company_admin:"مدير النظام",admin:"مدير النظام",owner:"المالك",ceo:"الرئيس التنفيذي",cfo:"المدير المالي",finance_manager:"مدير مالي",fpa_analyst:"محلل FP&A",accountant:"محاسب",viewer:"مطلع",planner:"محلل FP&A"};
const modules=[
 ["01","البيانات الفعلية","Actuals","استيراد وتنظيم البيانات الفعلية.","/workspace/actuals"],["02","الميزانية","Budget","بناء الخطط والميزانيات المالية.","/workspace/budget"],["03","التوقعات","Forecast","تحديث مستمر للرؤية المستقبلية.","/workspace/forecast"],["04","الفروقات","Variance","معرفة ما تغيّر عن الخطة ولماذا.","/workspace/variance"],["05","السيناريوهات","Scenarios","اختبار What If قبل اتخاذ القرار.","/workspace/scenarios"],["06","التدفق النقدي","Cash Flow","رؤية السيولة الداخلة والخارجة.","/workspace/cash"],["07","التقارير","Reports","تقارير مالية وإدارية واضحة.","/workspace/reports"]
];
export default function WorkspacePage(){const[company,setCompany]=useState<Company|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{const supabase=getSupabaseBrowserClient();let alive=true;async function load(){const{data:user}=await supabase.auth.getUser();if(!user.user){window.location.href="/login?next=/workspace";return}const{data,error}=await supabase.rpc("get_my_workspaces");if(error||!data?.length){window.location.href="/start";return}const list=data as Company[];const activeId=window.sessionStorage.getItem("activeOrganizationId");const active=list.find(x=>x.id===activeId)||list[0];window.sessionStorage.setItem("activeOrganizationId",active.id);window.sessionStorage.setItem("selectedOrganizationIds",JSON.stringify([active.id]));if(alive){setCompany(active);setLoading(false)}}void load();return()=>{alive=false}},[]);
if(loading||!company)return <section dir="rtl" className="flex min-h-[calc(100vh-84px)] items-center justify-center"><div className="text-center"><div className="mx-auto h-8 w-8 animate-pulse rounded-full bg-slate-200"/><p className="mt-3 text-sm text-slate-500">جارٍ تجهيز مساحة العمل…</p></div></section>;
return <section dir="rtl" className="min-h-[calc(100vh-84px)] bg-[#f8fafc]"><div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
<div className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">FINANCIAL INTELLIGENCE WORKSPACE</p><h1 className="section-title mt-2 text-3xl sm:text-4xl">مرحباً بك في {company.name}</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-500">مساحة واحدة تجمع البيانات الفعلية والتخطيط والتوقع والتحليل لمساعدة المالية والإدارة على اتخاذ قرارات أوضح.</p></div><div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">{company.name.slice(0,1)}</span><span><span className="block text-[10px] text-slate-400">الدور</span><span className="text-sm font-bold text-slate-900">{roles[company.role_key]||company.role_key}</span></span></div></div>
<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Actuals" value="البيانات الفعلية" note="المصدر المالي الأساسي" href="/workspace/actuals"/><Metric label="Planning" value="التخطيط" note="الميزانية والتوقعات" href="/workspace/budget"/><Metric label="Analysis" value="التحليل" note="الفروقات والأداء" href="/workspace/financial-analysis"/><Metric label="Reports" value="التقارير" note="القوائم والتقارير الإدارية" href="/workspace/reports"/></div>
<div className="mt-9 flex items-end justify-between"><div><p className="eyebrow">PRODUCT MODULES</p><h2 className="section-title mt-1 text-xl">من البيانات إلى القرار</h2></div><Link href="/workspace/executive-dashboard" className="text-xs font-bold text-slate-600 hover:text-slate-950">لوحة الإدارة ←</Link></div>
<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{modules.map(([n,title,en,desc,href])=><Link key={href} href={href} className="saas-card saas-card-hover group p-5"><div className="flex items-start justify-between"><span className="text-[10px] font-black text-slate-300">{n}</span><span className="rounded-md border border-slate-200 px-2 py-1 text-[9px] font-bold text-slate-400">{en}</span></div><h3 className="mt-7 text-base font-extrabold text-slate-950">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{desc}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3 text-[11px] font-bold text-slate-400"><span>فتح الوحدة</span><span className="transition group-hover:-translate-x-1">←</span></div></Link>)}</div>
<div className="mt-9 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><section className="saas-card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="eyebrow">MANAGEMENT QUESTIONS</p><h2 className="mt-1 text-base font-extrabold text-slate-950">كل شاشة تجيب على سؤال إداري</h2></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4">{[["Performance","كيف نؤدي؟","/workspace/executive-dashboard"],["Variance","ماذا تغيّر؟","/workspace/variance"],["Forecast","إلى أين نتجه؟","/workspace/forecast"],["Scenarios","ماذا لو؟","/workspace/scenarios"]].map(([en,q,href])=><Link href={href} key={en} className="border-b border-slate-100 p-5 transition hover:bg-slate-50 lg:border-b-0 lg:border-l last:border-l-0"><span className="text-[9px] font-bold tracking-widest text-slate-400">{en}</span><p className="mt-7 text-sm font-bold text-slate-800">{q}</p></Link>)}</div></section><section className="rounded-xl border border-slate-200 bg-slate-950 p-5 text-white"><p className="eyebrow text-slate-500">WORKSPACE STATUS</p><p className="mt-2 text-lg font-bold">مساحة العمل جاهزة</p><p className="mt-2 text-xs leading-6 text-slate-400">تنتقل الصلاحيات والفلاتر والبيانات مع الشركة الحالية دون تغيير منطق النظام.</p></section></div>
</div></section>}
function Metric({label,value,note,href}:{label:string;value:string;note:string;href:string}){return <Link href={href} className="saas-card saas-card-hover p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-extrabold tracking-widest text-slate-400">{label}</span><span className="h-2 w-2 rounded-full bg-slate-900"/></div><p className="mt-3 text-sm font-extrabold text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-500">{note}</p></Link>}
