"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Version = { id: string; name: string; status: string; review_note: string | null };
type Period = { id: string; period_start: string; period_end: string; status: string };
type Line = { id: string; financial_period_id: string; cash_category: string; amount_minor: number; currency: string; notes: string | null };
type Payload = { version: Version | null; periods: Period[]; lines: Line[] };

const labels: Record<string,string> = { opening_cash:"الرصيد الافتتاحي", cash_inflow:"التدفقات الداخلة", cash_outflow:"التدفقات الخارجة", financing:"التمويل", closing_cash:"الرصيد الختامي" };
const statusLabels: Record<string,string> = { draft:"مسودة", submitted:"بانتظار المراجعة", changes_requested:"مطلوب تعديل", approved:"معتمدة", locked:"مقفلة" };
const money=(n:number)=>new Intl.NumberFormat("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n/100);

export default function CashPage(){
 const supabase=getSupabaseBrowserClient(); const [orgId,setOrgId]=useState<string|null>(null); const [payload,setPayload]=useState<Payload>({version:null,periods:[],lines:[]}); const [versionId,setVersionId]=useState<string|null>(null); const [name,setName]=useState(""); const [periodId,setPeriodId]=useState(""); const [category,setCategory]=useState("cash_inflow"); const [amount,setAmount]=useState(""); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async(org:string,version?:string|null)=>{setLoading(true);setError(null);const {data,error:e}=await supabase.rpc("get_cash_forecast_workspace",{p_organization_id:org,p_planning_version_id:version??null});if(e){setError(e.message);setLoading(false);return;}const x=(data??{}) as Payload;setPayload({version:x.version??null,periods:x.periods??[],lines:x.lines??[]});setVersionId(x.version?.id??null);setLoading(false)},[supabase]);
 useEffect(()=>{const id=window.sessionStorage.getItem("activeOrganizationId");if(!id){setError("لم يتم تحديد الشركة الحالية.");setLoading(false);return;}setOrgId(id);void load(id)},[load]);
 const editable=payload.version?.status==="draft"; const totalIn=useMemo(()=>payload.lines.filter(x=>x.cash_category==="cash_inflow").reduce((s,x)=>s+Number(x.amount_minor),0),[payload.lines]); const totalOut=useMemo(()=>payload.lines.filter(x=>x.cash_category==="cash_outflow").reduce((s,x)=>s+Number(x.amount_minor),0),[payload.lines]); const financing=useMemo(()=>payload.lines.filter(x=>x.cash_category==="financing").reduce((s,x)=>s+Number(x.amount_minor),0),[payload.lines]); const closing=useMemo(()=>{const o=payload.lines.find(x=>x.cash_category==="opening_cash");return Number(o?.amount_minor||0)+totalIn-totalOut+financing},[payload.lines,totalIn,totalOut,financing]);
 async function createVersion(){if(!orgId||!name.trim())return;setBusy(true);const {data,error:e}=await supabase.rpc("create_planning_version",{p_organization_id:orgId,p_version_type:"forecast",p_name:name.trim()});if(e)setError(e.message);else{setName("");await load(orgId,data as string)}setBusy(false)}
 async function save(){if(!orgId||!versionId||!periodId||!amount.trim()){setError("اختر الفترة وأدخل المبلغ.");return}const n=Number(amount.replace(/,/g,""));if(!Number.isFinite(n)){setError("المبلغ غير صحيح.");return}setBusy(true);setError(null);const {error:e}=await supabase.rpc("upsert_cash_forecast_line",{p_organization_id:orgId,p_planning_version_id:versionId,p_financial_period_id:periodId,p_cash_category:category,p_amount_minor:Math.round(n*100),p_currency:"SAR",p_notes:notes.trim()||null});if(e)setError(e.message);else{setAmount("");setNotes("");await load(orgId,versionId)}setBusy(false)}
 async function del(id:string){if(!orgId)return;setBusy(true);setError(null);const {error:e}=await supabase.rpc("delete_cash_forecast_line",{p_organization_id:orgId,p_cash_forecast_line_id:id});if(e)setError(e.message);else await load(orgId,versionId);setBusy(false)}
 async function submit(){if(!orgId||!versionId)return;setBusy(true);setError(null);const {error:e}=await supabase.rpc("submit_planning_version",{p_planning_version_id:versionId});if(e)setError(e.message);else await load(orgId,versionId);setBusy(false)}
 return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">06 / CASH FLOW</p><h1 className="section-title mt-1 text-2xl sm:text-3xl">التدفقات النقدية</h1><p className="mt-2 text-sm leading-6 text-slate-500">توقع السيولة ومتابعة الرصيد النقدي المتوقع لكل فترة.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat title="داخل" value={totalIn}/><Stat title="خارج" value={totalOut}/><Stat title="تمويل" value={financing}/><Stat title="ختامي" value={closing}/></div></div></div></header>
  <div className="mx-auto max-w-[1500px] space-y-5 px-4 py-6 sm:px-6 lg:px-8 lg:py-7">
   {error&&<div role="alert" className="border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
   <section className="saas-card p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">FORECAST VERSION</p><h2 className="mt-1 text-base font-extrabold">إصدار توقع السيولة</h2><p className="mt-1 text-sm text-slate-500">إصدار Forecast هو الحاوية الرسمية لتوقع التدفقات.</p></div>{payload.version&&<span className="border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold">{statusLabels[payload.version.status]??payload.version.status}</span>}</div>{!payload.version?<div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={name} onChange={e=>setName(e.target.value)} className="input flex-1" placeholder="مثال: توقع السيولة للربع الرابع"/><button disabled={busy||!name.trim()} onClick={()=>void createVersion()} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-50">إنشاء التوقع</button></div>:<div className="mt-4 flex flex-wrap items-center gap-3"><b>{payload.version.name}</b>{editable&&<button disabled={busy} onClick={()=>void submit()} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-50">إرسال للمراجعة</button>}</div>}</section>
   {payload.version&&<><section className="saas-card p-5 sm:p-6"><p className="eyebrow">INPUT</p><h2 className="mt-1 font-extrabold">إضافة حركة نقدية</h2><p className="mt-1 text-sm text-slate-500">الإدخال يدوي حاليًا؛ الربط الآلي بالمبيعات والمصروفات سيأتي في طبقة التخطيط المتقدمة.</p><div className="mt-5 grid gap-3 md:grid-cols-4"><select disabled={!editable||busy} value={periodId} onChange={e=>setPeriodId(e.target.value)} className="input"><option value="">اختر الفترة</option>{payload.periods.map(p=><option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><select disabled={!editable||busy} value={category} onChange={e=>setCategory(e.target.value)} className="input">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input disabled={!editable||busy} value={amount} onChange={e=>setAmount(e.target.value)} className="input" inputMode="decimal" placeholder="المبلغ بالريال"/><button disabled={!editable||busy} onClick={()=>void save()} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-40">حفظ</button></div><input disabled={!editable||busy} value={notes} onChange={e=>setNotes(e.target.value)} className="input mt-3 w-full" placeholder="ملاحظة اختيارية"/></section><section className="saas-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 sm:px-6"><p className="eyebrow">CASH MOVEMENTS</p><h2 className="mt-1 font-extrabold">حركات السيولة</h2><p className="mt-1 text-sm text-slate-500">{payload.lines.length} بند</p></div>{loading?<div className="p-8 text-center text-sm text-slate-500">جارٍ التحميل…</div>:payload.lines.length===0?<div className="p-8 text-center text-sm text-slate-500">لا توجد حركات بعد.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500"><tr><th className="px-5 py-3">الفترة</th><th className="px-5 py-3">البند</th><th className="px-5 py-3">المبلغ</th><th className="px-5 py-3">ملاحظة</th><th className="px-5 py-3">إجراء</th></tr></thead><tbody className="divide-y divide-slate-100">{payload.lines.map(l=><tr key={l.id} className="transition hover:bg-slate-50"><td className="px-5 py-4">{payload.periods.find(p=>p.id===l.financial_period_id)?.period_start??l.financial_period_id}</td><td className="px-5 py-4 font-semibold">{labels[l.cash_category]??l.cash_category}</td><td className="px-5 py-4 font-bold tabular-nums">{money(Number(l.amount_minor))} ريال</td><td className="px-5 py-4 text-slate-500">{l.notes||"—"}</td><td className="px-5 py-4">{editable&&<button disabled={busy} onClick={()=>void del(l.id)} className="text-xs font-bold text-red-600 disabled:opacity-40">حذف</button>}</td></tr>)}</tbody></table></div>}</section></>}
  </div>
 </main>
}
function Stat({title,value}:{title:string,value:number}){return <div className="border border-slate-200 bg-slate-50 px-3 py-2"><span className="text-[10px] font-bold text-slate-400">{title}</span><div className="mt-1 text-sm font-black tabular-nums">{money(value)} ريال</div></div>}
