import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const JSON_HEADERS={ "Content-Type":"application/json" };
const QOYOD_BASE="https://api.qoyod.com/2.0";
const RESOURCES=["accounts","journal_entries"] as const;
function pickRows(body:unknown,resource:string):unknown[]{if(Array.isArray(body))return body;if(!body||typeof body!=="object")return[];const o=body as Record<string,unknown>;if(Array.isArray(o[resource]))return o[resource] as unknown[];if(Array.isArray(o.results))return o.results as unknown[];const d=o.data;if(Array.isArray(d))return d;if(d&&typeof d==="object"){const x=d as Record<string,unknown>;if(Array.isArray(x[resource]))return x[resource] as unknown[];if(Array.isArray(x.results))return x.results as unknown[];}return[]}
function recordKey(row:unknown,resource:string,index:number){if(row&&typeof row==="object"){const o=row as Record<string,unknown>;for(const k of["id","uuid","entry_id","journal_entry_id","account_id","code","index"]){if(o[k]!=null&&String(o[k]).trim())return String(o[k])}}return `${resource}:row:${index}`}
async function userId(req:Request,url:string,key:string){const auth=req.headers.get("Authorization");if(!auth)throw new Error("AUTH_REQUIRED");const c=createClient(url,key,{global:{headers:{Authorization:auth}},auth:{autoRefreshToken:false,persistSession:false}});const{data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("AUTH_REQUIRED");return data.user.id}
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:JSON_HEADERS});try{
 const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),anon=Deno.env.get("SUPABASE_ANON_KEY");if(!url||!service||!anon)throw new Error("FUNCTION_ENV_INCOMPLETE");
 const admin=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});const uid=await userId(req,url,anon);const body=await req.json().catch(()=>({}));const org=String(body?.organization_id||"").trim(),connectorId=String(body?.connector_id||"").trim(),mode=body?.mode==="test"?"test":"sync";if(!org||!connectorId)throw new Error("ORGANIZATION_AND_CONNECTOR_REQUIRED");
 const userClient=createClient(url,anon,{global:{headers:{Authorization:req.headers.get("Authorization")||""}},auth:{autoRefreshToken:false,persistSession:false}});const{data:access,error:ae}=await userClient.rpc("get_my_org_access",{p_organization_id:org});if(ae)throw ae;if(!(access??[]).some((x:{permission_key?:string;granted?:boolean})=>x.permission_key==="connector.manage"&&x.granted===true))throw new Error("PERMISSION_DENIED");
 const{data:connector,error:ce}=await admin.from("data_source_connectors").select("id,organization_id,data_source_id,enabled,sync_config,connector_catalog:connector_id(connector_key,display_name)").eq("id",connectorId).eq("organization_id",org).maybeSingle();if(ce)throw ce;if(!connector||!connector.enabled)throw new Error("CONNECTOR_NOT_ENABLED");
 const catalog=connector.connector_catalog as {connector_key?:string}|null;if(catalog?.connector_key!=="qoyod")throw new Error("ONLY_QOYOD_IS_EXECUTABLE_IN_THIS_STAGE");
 const ref=String((connector.sync_config as Record<string,unknown>|null)?.credential_ref||"");if(!ref)throw new Error("CREDENTIAL_NOT_CONFIGURED");
 const{data:secret,error:se}=await admin.schema("vault").from("decrypted_secrets").select("decrypted_secret").eq("name",ref).maybeSingle();if(se)throw se;const apiKey=secret?.decrypted_secret;if(!apiKey)throw new Error("CREDENTIAL_NOT_FOUND");
 async function get(resource:string,page=1){const u=new URL(`${QOYOD_BASE}/${resource}`);u.searchParams.set("page",String(page));u.searchParams.set("per_page","100");const r=await fetch(u,{method:"GET",headers:{"API-KEY":apiKey,"Accept":"application/json"}});const t=await r.text();let p:unknown;try{p=JSON.parse(t)}catch{p={raw:t.slice(0,2000)}}if(!r.ok)throw new Error(`QOYOD_${r.status}_${resource}`);return p}
 if(mode==="test"){const a=await get("accounts",1);return new Response(JSON.stringify({ok:true,provider:"qoyod",mode,accounts_sample_count:pickRows(a,"accounts").length,read_only:true}),{status:200,headers:JSON_HEADERS})}
 const{data:run,error:re}=await admin.from("data_sync_runs").insert({organization_id:org,data_source_id:connector.data_source_id,status:"running",created_by:uid}).select("id").single();if(re)throw re;
 let received=0,accepted=0,errors=0;try{for(const resource of RESOURCES){for(let page=1;page<=100;page++){const payload=await get(resource,page),rows=pickRows(payload,resource);received+=rows.length;if(!rows.length)break;for(let i=0;i<rows.length;i++){const{error}=await admin.from("sync_payloads").insert({organization_id:org,data_source_id:connector.data_source_id,sync_run_id:run.id,source_entity_type:resource,source_record_key:recordKey(rows[i],resource,i),payload:rows[i]});if(error)errors++;else accepted++}if(rows.length<100)break}}const status=errors>0?(accepted>0?"partial":"failed"):"succeeded";await admin.from("data_sync_runs").update({completed_at:new Date().toISOString(),status,records_received:received,records_accepted:accepted,records_rejected:errors,error_count:errors,error_message:errors?"Some source records could not be stored":null}).eq("id",run.id).eq("organization_id",org);await admin.from("data_sources").update({last_sync_at:new Date().toISOString(),last_success_at:status!=="failed"?new Date().toISOString():null,last_error_at:status==="failed"?new Date().toISOString():null,last_error_message:errors?"Some source records could not be stored":null,status:status==="failed"?"error":"active",updated_at:new Date().toISOString()}).eq("id",connector.data_source_id).eq("organization_id",org);return new Response(JSON.stringify({ok:status!=="failed",provider:"qoyod",mode,run_id:run.id,status,received,accepted,errors,read_only:true}),{status:status==="failed"?502:200,headers:JSON_HEADERS})}catch(e){const m=e instanceof Error?e.message:"SYNC_FAILED";await admin.from("data_sync_runs").update({completed_at:new Date().toISOString(),status:"failed",error_count:1,error_message:m}).eq("id",run.id).eq("organization_id",org);throw e}
}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:"INTEGRATION_SYNC_FAILED"}),{status:400,headers:JSON_HEADERS})}});