begin;
create index if not exists account_categories_parent_id_fkey_idx on public.account_categories (parent_id);
create index if not exists account_import_batches_applied_by_fkey_idx on public.account_import_batches (applied_by);
create index if not exists account_import_batches_created_by_fkey_idx on public.account_import_batches (created_by);
create index if not exists account_mappings_approved_by_fkey_idx on public.account_mappings (approved_by);
create index if not exists account_mappings_created_by_fkey_idx on public.account_mappings (created_by);
create index if not exists account_mappings_rejected_by_fkey_idx on public.account_mappings (rejected_by);
create index if not exists accounts_category_id_fkey_idx on public.accounts (category_id);
create index if not exists accounts_parent_account_id_fkey_idx on public.accounts (parent_account_id);
create index if not exists actuals_publish_batches_import_id_fkey_idx on public.actuals_publish_batches (import_id);
create index if not exists actuals_publish_batches_published_by_fkey_idx on public.actuals_publish_batches (published_by);
create index if not exists branches_legal_entity_id_fkey_idx on public.branches (legal_entity_id);
create index if not exists branches_legal_entity_same_org_fk_idx on public.branches (organization_id, legal_entity_id);
create index if not exists budget_lines_account_id_fkey_idx on public.budget_lines (account_id);
create index if not exists budget_lines_branch_id_fkey_idx on public.budget_lines (branch_id);
create index if not exists budget_lines_cost_center_id_fkey_idx on public.budget_lines (cost_center_id);
create index if not exists budget_lines_created_by_fkey_idx on public.budget_lines (created_by);
create index if not exists budget_lines_department_id_fkey_idx on public.budget_lines (department_id);
create index if not exists budget_lines_financial_period_id_fkey_idx on public.budget_lines (financial_period_id);
create index if not exists budget_lines_legal_entity_id_fkey_idx on public.budget_lines (legal_entity_id);
create index if not exists budget_lines_planning_version_id_fkey_idx on public.budget_lines (planning_version_id);
create index if not exists budget_lines_product_id_fkey_idx on public.budget_lines (product_id);
create index if not exists budget_lines_project_id_fkey_idx on public.budget_lines (project_id);
create index if not exists budget_lines_region_id_fkey_idx on public.budget_lines (region_id);
create index if not exists budget_lines_updated_by_fkey_idx on public.budget_lines (updated_by);
create index if not exists data_lineage_sync_run_id_fkey_idx on public.data_lineage (sync_run_id);
create index if not exists data_source_connectors_created_by_fkey_idx on public.data_source_connectors (created_by);
create index if not exists financial_facts_account_id_fkey_idx on public.financial_facts (account_id);
create index if not exists financial_facts_branch_id_fkey_idx on public.financial_facts (branch_id);
create index if not exists financial_facts_cost_center_id_fkey_idx on public.financial_facts (cost_center_id);
create index if not exists financial_facts_cost_center_same_org_fk_idx on public.financial_facts (organization_id, cost_center_id);
create index if not exists financial_facts_department_id_fkey_idx on public.financial_facts (department_id);
create index if not exists financial_facts_department_same_org_fk_idx on public.financial_facts (organization_id, department_id);
create index if not exists financial_facts_financial_period_id_fkey_idx on public.financial_facts (financial_period_id);
create index if not exists financial_facts_legal_entity_id_fkey_idx on public.financial_facts (legal_entity_id);
create index if not exists financial_facts_planning_version_id_fkey_idx on public.financial_facts (planning_version_id);
create index if not exists financial_facts_planning_version_same_org_fk_idx on public.financial_facts (organization_id, planning_version_id);
create index if not exists financial_facts_product_id_fkey_idx on public.financial_facts (product_id);
create index if not exists financial_facts_product_same_org_fk_idx on public.financial_facts (organization_id, product_id);
create index if not exists financial_facts_project_id_fkey_idx on public.financial_facts (project_id);
create index if not exists financial_facts_project_same_org_fk_idx on public.financial_facts (organization_id, project_id);
create index if not exists financial_facts_region_id_fkey_idx on public.financial_facts (region_id);
create index if not exists financial_facts_region_same_org_fk_idx on public.financial_facts (organization_id, region_id);
create index if not exists financial_facts_source_import_id_fkey_idx on public.financial_facts (source_import_id);
create index if not exists forecast_lines_account_id_fkey_idx on public.forecast_lines (account_id);
create index if not exists group_account_mappings_account_id_fkey_idx on public.group_account_mappings (account_id);
create index if not exists group_account_mappings_group_reporting_account_id_fkey_idx on public.group_account_mappings (group_reporting_account_id);
create index if not exists group_account_mappings_organization_id_fkey_idx on public.group_account_mappings (organization_id);
create index if not exists import_audit_events_actor_id_fkey_idx on public.import_audit_events (actor_id);
create index if not exists import_audit_events_organization_id_fkey_idx on public.import_audit_events (organization_id);
create index if not exists import_reconciliations_overridden_by_fkey_idx on public.import_reconciliations (overridden_by);
create index if not exists imports_published_by_fkey_idx on public.imports (published_by);
create index if not exists notifications_organization_id_fkey_idx on public.notifications (organization_id);
create index if not exists notifications_recipient_user_id_fkey_idx on public.notifications (recipient_user_id);
create index if not exists organization_invitations_invited_by_fkey_idx on public.organization_invitations (invited_by);
create index if not exists organization_invitations_invited_user_id_fkey_idx on public.organization_invitations (invited_user_id);
create index if not exists organization_member_permission_overrides_permission_key_fkey_idx on public.organization_member_permission_overrides (permission_key);
create index if not exists organization_member_permission_overrides_user_id_fkey_idx on public.organization_member_permission_overrides (user_id);
create index if not exists organization_member_scopes_user_id_fkey_idx on public.organization_member_scopes (user_id);
create index if not exists organization_role_permissions_permission_key_fkey_idx on public.organization_role_permissions (permission_key);
create index if not exists organizations_owner_user_id_fkey_idx on public.organizations (owner_user_id);
create index if not exists planning_approval_policies_created_by_fkey_idx on public.planning_approval_policies (created_by);
create index if not exists planning_driver_values_created_by_fkey_idx on public.planning_driver_values (created_by);
create index if not exists planning_driver_values_financial_period_id_fkey_idx on public.planning_driver_values (financial_period_id);
create index if not exists planning_driver_values_scenario_id_fkey_idx on public.planning_driver_values (scenario_id);
create index if not exists planning_drivers_created_by_fkey_idx on public.planning_drivers (created_by);
create index if not exists planning_version_approval_steps_assigned_to_fkey_idx on public.planning_version_approval_steps (assigned_to);
create index if not exists planning_version_approval_steps_decided_by_fkey_idx on public.planning_version_approval_steps (decided_by);
create index if not exists planning_versions_approved_by_fkey_idx on public.planning_versions (approved_by);
create index if not exists planning_versions_based_on_version_id_fkey_idx on public.planning_versions (based_on_version_id);
create index if not exists planning_versions_submitted_by_fkey_idx on public.planning_versions (submitted_by);
create index if not exists sync_payloads_organization_id_fkey_idx on public.sync_payloads (organization_id);
commit;
