-- Analytics must consume only currently published actuals.
-- Historical/superseded and rolled-back facts remain stored for lineage/audit but are excluded.

CREATE OR REPLACE FUNCTION public.get_financial_analysis(p_organization_id uuid, p_period_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
declare
  v_user uuid := auth.uid(); v_period record; v_prior_period record; v_current record; v_prior record;
  v_revenue_growth numeric; v_revenue_growth_pct numeric; v_gross_margin numeric; v_ebitda_margin numeric; v_net_margin numeric; v_opex_ratio numeric; v_trend text;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_organization_id is null or p_period_id is null then raise exception 'Organization and period are required'; end if;
  if not public.has_org_permission(p_organization_id, 'screen.financial_analysis.view') then raise exception 'Not authorized'; end if;
  select id, organization_id, period_start, period_end, status into v_period from public.financial_periods where id=p_period_id and organization_id=p_organization_id;
  if v_period.id is null then raise exception 'Financial period not found'; end if;
  select id, organization_id, period_start, period_end, status into v_prior_period from public.financial_periods where organization_id=p_organization_id and period_end < v_period.period_start order by period_end desc limit 1;
  with scoped_facts as (
    select ff.financial_period_id, ff.account_id,
      coalesce(ff.debit_minor, case when ff.amount_minor > 0 then ff.amount_minor else 0 end)::bigint debit_minor,
      coalesce(ff.credit_minor, case when ff.amount_minor < 0 then -ff.amount_minor else 0 end)::bigint credit_minor
    from public.financial_facts ff
    where ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published'
      and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id)
      and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id)
      and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id)
      and public.has_org_data_scope(ff.organization_id,'project',ff.project_id)
  ), classified as (
    select sf.financial_period_id, lower(coalesce(a.account_type,'')) account_type, sf.debit_minor, sf.credit_minor
    from scoped_facts sf join public.accounts a on a.id=sf.account_id and a.organization_id=p_organization_id
  )
  select coalesce(sum(case when account_type in ('revenue','income') then credit_minor-debit_minor else 0 end),0)::bigint revenue,
    coalesce(sum(case when account_type in ('cost_of_sales','cogs') then debit_minor-credit_minor else 0 end),0)::bigint cogs,
    coalesce(sum(case when account_type in ('expense','operating_expense','operating_expenses') then debit_minor-credit_minor else 0 end),0)::bigint operating_expenses,
    coalesce(sum(case when account_type in ('finance_cost','finance_expense') then debit_minor-credit_minor else 0 end),0)::bigint finance_cost,
    coalesce(sum(case when account_type in ('tax','income_tax') then debit_minor-credit_minor else 0 end),0)::bigint tax into v_current from classified where financial_period_id=p_period_id;
  if v_prior_period.id is not null then
    with scoped_facts as (
      select ff.financial_period_id, ff.account_id,
        coalesce(ff.debit_minor, case when ff.amount_minor > 0 then ff.amount_minor else 0 end)::bigint debit_minor,
        coalesce(ff.credit_minor, case when ff.amount_minor < 0 then -ff.amount_minor else 0 end)::bigint credit_minor
      from public.financial_facts ff
      where ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published' and ff.financial_period_id=v_prior_period.id
        and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id)
        and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id)
        and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id)
        and public.has_org_data_scope(ff.organization_id,'project',ff.project_id)
    ), classified as (select lower(coalesce(a.account_type,'')) account_type,sf.debit_minor,sf.credit_minor from scoped_facts sf join public.accounts a on a.id=sf.account_id and a.organization_id=p_organization_id)
    select coalesce(sum(case when account_type in ('revenue','income') then credit_minor-debit_minor else 0 end),0)::bigint revenue,
      coalesce(sum(case when account_type in ('cost_of_sales','cogs') then debit_minor-credit_minor else 0 end),0)::bigint cogs,
      coalesce(sum(case when account_type in ('expense','operating_expense','operating_expenses') then debit_minor-credit_minor else 0 end),0)::bigint operating_expenses,
      coalesce(sum(case when account_type in ('finance_cost','finance_expense') then debit_minor-credit_minor else 0 end),0)::bigint finance_cost,
      coalesce(sum(case when account_type in ('tax','income_tax') then debit_minor-credit_minor else 0 end),0)::bigint tax into v_prior from classified;
  else v_prior := row(0::bigint,0::bigint,0::bigint,0::bigint,0::bigint); end if;
  if v_prior_period.id is null then v_prior := row(0::bigint,0::bigint,0::bigint,0::bigint,0::bigint); end if;
  if v_prior.revenue <> 0 then v_revenue_growth := v_current.revenue-v_prior.revenue; v_revenue_growth_pct := round((v_revenue_growth::numeric/abs(v_prior.revenue)::numeric)*100,2); end if;
  if v_current.revenue <> 0 then v_gross_margin := round(((v_current.revenue-v_current.cogs)::numeric/abs(v_current.revenue)::numeric)*100,2); v_ebitda_margin := round(((v_current.revenue-v_current.cogs-v_current.operating_expenses)::numeric/abs(v_current.revenue)::numeric)*100,2); v_net_margin := round(((v_current.revenue-v_current.cogs-v_current.operating_expenses-v_current.finance_cost-v_current.tax)::numeric/abs(v_current.revenue)::numeric)*100,2); v_opex_ratio := round((v_current.operating_expenses::numeric/abs(v_current.revenue)::numeric)*100,2); end if;
  if v_prior_period.id is null then v_trend:='no_prior_period'; elsif v_current.revenue>v_prior.revenue then v_trend:='up'; elsif v_current.revenue<v_prior.revenue then v_trend:='down'; else v_trend:='flat'; end if;
  return jsonb_build_object('organization_id',p_organization_id,'period',jsonb_build_object('id',v_period.id,'start',v_period.period_start,'end',v_period.period_end,'status',v_period.status),'prior_period',case when v_prior_period.id is null then null else jsonb_build_object('id',v_prior_period.id,'start',v_prior_period.period_start,'end',v_prior_period.period_end,'status',v_prior_period.status) end,'current',jsonb_build_object('revenue',v_current.revenue,'cogs',v_current.cogs,'gross_profit',v_current.revenue-v_current.cogs,'operating_expenses',v_current.operating_expenses,'ebitda',v_current.revenue-v_current.cogs-v_current.operating_expenses,'finance_cost',v_current.finance_cost,'tax',v_current.tax,'net_income',v_current.revenue-v_current.cogs-v_current.operating_expenses-v_current.finance_cost-v_current.tax),'prior',case when v_prior_period.id is null then null else jsonb_build_object('revenue',v_prior.revenue,'cogs',v_prior.cogs,'gross_profit',v_prior.revenue-v_prior.cogs,'operating_expenses',v_prior.operating_expenses,'ebitda',v_prior.revenue-v_prior.cogs-v_prior.operating_expenses,'finance_cost',v_prior.finance_cost,'tax',v_prior.tax,'net_income',v_prior.revenue-v_prior.cogs-v_prior.operating_expenses-v_prior.finance_cost-v_prior.tax) end,'metrics',jsonb_build_object('revenue_change',v_revenue_growth,'revenue_growth_pct',v_revenue_growth_pct,'gross_margin_pct',v_gross_margin,'ebitda_margin_pct',v_ebitda_margin,'net_margin_pct',v_net_margin,'operating_expense_ratio_pct',v_opex_ratio,'revenue_trend',v_trend),'methodology',jsonb_build_object('source','published actual financial facts','ai_authoritative',false,'prior_period','immediately preceding financial period by period_end'));
end; $function$;

CREATE OR REPLACE FUNCTION public.get_dimension_analysis(p_organization_id uuid, p_period_id uuid, p_dimension text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
declare v_period record; v_dimension text:=lower(trim(coalesce(p_dimension,''))); v_rows jsonb;
begin
 if auth.uid() is null or not public.has_org_permission(p_organization_id,'screen.dimensions.view') or not public.has_org_permission(p_organization_id,'dimensions.view') then raise exception 'Not authorized'; end if;
 select id,organization_id,period_start,period_end,status into v_period from public.financial_periods where id=p_period_id and organization_id=p_organization_id; if v_period.id is null then raise exception 'Financial period not found'; end if;
 if v_dimension not in ('branch','cost_center') then raise exception 'Unsupported dimension'; end if;
 if v_dimension='branch' then
  select coalesce(jsonb_agg(x order by x.revenue desc),'[]'::jsonb) into v_rows from (select coalesce(b.name,'غير محدد') dimension_name,b.id dimension_id,coalesce(sum(case when lower(coalesce(a.account_type,'')) in ('revenue','income') then ff.credit_minor-ff.debit_minor else 0 end),0)::bigint revenue,coalesce(sum(case when lower(coalesce(a.account_type,'')) in ('cost_of_sales','cogs') then ff.debit_minor-ff.credit_minor else 0 end),0)::bigint cogs,coalesce(sum(case when lower(coalesce(a.account_type,'')) in ('expense','operating_expense','operating_expenses') then ff.debit_minor-ff.credit_minor else 0 end),0)::bigint operating_expenses from public.financial_facts ff join public.accounts a on a.id=ff.account_id and a.organization_id=p_organization_id left join public.branches b on b.id=ff.branch_id and b.organization_id=p_organization_id where ff.organization_id=p_organization_id and ff.financial_period_id=p_period_id and ff.fact_type='actual' and ff.status='published' and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id) group by b.id,b.name) x;
 else
  select coalesce(jsonb_agg(x order by x.revenue desc),'[]'::jsonb) into v_rows from (select coalesce(cc.name,'غير محدد') dimension_name,cc.id dimension_id,coalesce(sum(case when lower(coalesce(a.account_type,'')) in ('revenue','income') then ff.credit_minor-ff.debit_minor else 0 end),0)::bigint revenue,coalesce(sum(case when lower(coalesce(a.account_type,'')) in ('cost_of_sales','cogs') then ff.debit_minor-ff.credit_minor else 0 end),0)::bigint cogs,coalesce(sum(case when lower(coalesce(a.account_type,'')) in ('expense','operating_expense','operating_expenses') then ff.debit_minor-ff.credit_minor else 0 end),0)::bigint operating_expenses from public.financial_facts ff join public.accounts a on a.id=ff.account_id and a.organization_id=p_organization_id left join public.cost_centers cc on cc.id=ff.cost_center_id and cc.organization_id=p_organization_id where ff.organization_id=p_organization_id and ff.financial_period_id=p_period_id and ff.fact_type='actual' and ff.status='published' and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id) group by cc.id,cc.name) x;
 end if;
 return jsonb_build_object('organization_id',p_organization_id,'period',jsonb_build_object('id',v_period.id,'start',v_period.period_start,'end',v_period.period_end,'status',v_period.status),'dimension',v_dimension,'rows',v_rows,'methodology',jsonb_build_object('source','published actual financial facts','ai_authoritative',false));
end; $function$;

CREATE OR REPLACE FUNCTION public.get_financial_statements(p_organization_id uuid, p_period_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
declare v_user uuid := (select auth.uid()); v_period record; v_rows jsonb; v_income jsonb; v_balance jsonb;
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if not public.has_org_permission(p_organization_id,'statements.view') then raise exception 'Financial statements view permission required'; end if;
 select id,organization_id,period_start,period_end,status into v_period from public.financial_periods where id=p_period_id and organization_id=p_organization_id; if v_period.id is null then raise exception 'Financial period not found'; end if;
 with balances as (select a.id,a.code,a.name,a.statement_type,a.statement_section,a.account_type,a.normal_balance,coalesce(sum(f.debit_minor),0)::bigint debit,coalesce(sum(f.credit_minor),0)::bigint credit,coalesce(sum(f.amount_minor),0)::bigint balance from public.accounts a left join public.financial_facts f on f.account_id=a.id and f.organization_id=p_organization_id and f.financial_period_id=p_period_id and f.fact_type='actual' and f.status='published' where a.organization_id=p_organization_id group by a.id,a.code,a.name,a.statement_type,a.statement_section,a.account_type,a.normal_balance), income as (select * from balances where lower(coalesce(statement_type,'')) in ('income','income_statement','profit_and_loss','p&l','pnl') or lower(coalesce(account_type,'')) in ('revenue','income','expense','cost_of_sales','cogs')), bs as (select * from balances where lower(coalesce(statement_type,'')) in ('balance_sheet','balance sheet','bs','financial_position') or lower(coalesce(account_type,'')) in ('asset','liability','equity')), ir as (select coalesce(sum(case when lower(coalesce(account_type,'')) in ('revenue','income') then credit-debit else 0 end),0)::bigint revenue, coalesce(sum(case when lower(coalesce(account_type,'')) in ('cost_of_sales','cogs') then debit-credit else 0 end),0)::bigint cogs, coalesce(sum(case when lower(coalesce(account_type,'')) in ('expense','operating_expense','operating_expenses') then debit-credit else 0 end),0)::bigint operating_expenses, coalesce(sum(case when lower(coalesce(account_type,'')) in ('finance_cost','finance_expense') then debit-credit else 0 end),0)::bigint finance_cost, coalesce(sum(case when lower(coalesce(account_type,'')) in ('tax','income_tax') then debit-credit else 0 end),0)::bigint tax from income) select jsonb_build_object('revenue',revenue,'cogs',cogs,'gross_profit',revenue-cogs,'operating_expenses',operating_expenses,'ebitda',revenue-cogs-operating_expenses,'finance_cost',finance_cost,'ebt',revenue-cogs-operating_expenses-finance_cost,'tax',tax,'net_income',revenue-cogs-operating_expenses-finance_cost-tax) into v_income from ir;
 select coalesce(jsonb_agg(jsonb_build_object('code',code,'name',name,'section',statement_section,'account_type',account_type,'debit',debit,'credit',credit,'balance',balance) order by code),'[]'::jsonb) into v_rows from bs;
 v_balance=jsonb_build_object('accounts',v_rows,'total_assets',coalesce((select sum(case when lower(coalesce(account_type,''))='asset' then balance else 0 end) from bs),0),'total_liabilities',coalesce((select sum(case when lower(coalesce(account_type,''))='liability' then -balance else 0 end) from bs),0),'total_equity',coalesce((select sum(case when lower(coalesce(account_type,''))='equity' then -balance else 0 end) from bs),0));
 return jsonb_build_object('period',jsonb_build_object('id',v_period.id,'start',v_period.period_start,'end',v_period.period_end,'status',v_period.status),'income_statement',v_income,'balance_sheet',v_balance);
end; $function$;

CREATE OR REPLACE FUNCTION public.get_trial_balance(p_organization_id uuid, p_period_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
declare v_period record; v_rows jsonb; v_row_count integer; v_total_debit bigint; v_total_credit bigint; v_total_opening bigint; v_total_closing bigint;
begin
 if auth.uid() is null or not public.has_org_permission(p_organization_id,'screen.trial_balance.view') or not public.has_org_permission(p_organization_id,'trial_balance.view') then raise exception 'Not authorized'; end if;
 select id,organization_id,period_start,period_end,status into v_period from public.financial_periods where id=p_period_id and organization_id=p_organization_id; if v_period.id is null then raise exception 'Financial period not found'; end if;
 with scoped as (select ff.account_id,ff.financial_period_id,coalesce(ff.debit_minor,case when ff.amount_minor>0 then ff.amount_minor else 0 end) debit_minor,coalesce(ff.credit_minor,case when ff.amount_minor<0 then -ff.amount_minor else 0 end) credit_minor from public.financial_facts ff where ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published' and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id)), ap as (select a.id account_id,a.code,a.name,a.account_type,a.statement_type,a.statement_section,coalesce(sum(case when fp.period_start<v_period.period_start then s.debit_minor-s.credit_minor else 0 end),0)::bigint opening_balance,coalesce(sum(case when fp.id=p_period_id then s.debit_minor else 0 end),0)::bigint period_debit,coalesce(sum(case when fp.id=p_period_id then s.credit_minor else 0 end),0)::bigint period_credit from public.accounts a join scoped s on s.account_id=a.id join public.financial_periods fp on fp.id=s.financial_period_id and fp.organization_id=p_organization_id where a.organization_id=p_organization_id group by a.id,a.code,a.name,a.account_type,a.statement_type,a.statement_section), fr as (select *,opening_balance+period_debit-period_credit closing_balance from ap where opening_balance<>0 or period_debit<>0 or period_credit<>0) select count(*),coalesce(sum(period_debit),0),coalesce(sum(period_credit),0),coalesce(sum(opening_balance),0),coalesce(sum(closing_balance),0),coalesce(jsonb_agg(to_jsonb(fr) order by code),'[]'::jsonb) into v_row_count,v_total_debit,v_total_credit,v_total_opening,v_total_closing,v_rows from fr;
 return jsonb_build_object('organization_id',p_organization_id,'period_id',v_period.id,'period_start',v_period.period_start,'period_end',v_period.period_end,'period_status',v_period.status,'row_count',v_row_count,'total_period_debit',v_total_debit,'total_period_credit',v_total_credit,'period_difference',v_total_debit-v_total_credit,'total_opening_balance',v_total_opening,'total_closing_balance',v_total_closing,'rows',v_rows);
end; $function$;

CREATE OR REPLACE FUNCTION public.get_group_trial_balance(p_root_organization_id uuid, p_period_start date, p_period_end date)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
declare v_uid uuid := (select auth.uid()); v_orgs jsonb; v_rows jsonb; v_unmapped jsonb;
begin
 if v_uid is null then raise exception 'UNAUTHENTICATED'; end if;
 if p_period_start is null or p_period_end is null or p_period_start>p_period_end then raise exception 'INVALID_PERIOD_RANGE'; end if;
 if not public.has_org_permission(p_root_organization_id,'group.view') then raise exception 'FORBIDDEN'; end if;
 v_orgs:=public.get_group_organizations(p_root_organization_id);
 with recursive tree as (select o.id,o.base_currency from public.organizations o where o.id=p_root_organization_id union all select c.id,c.base_currency from public.organizations c join tree t on c.parent_organization_id=t.id), scoped as (select ff.organization_id,ff.account_id,t.base_currency as currency,coalesce(ff.debit_minor,case when ff.amount_minor>0 then ff.amount_minor else 0 end) debit_minor,coalesce(ff.credit_minor,case when ff.amount_minor<0 then -ff.amount_minor else 0 end) credit_minor from public.financial_facts ff join tree t on t.id=ff.organization_id join public.financial_periods fp on fp.id=ff.financial_period_id and fp.organization_id=ff.organization_id where ff.fact_type='actual' and ff.status='published' and fp.period_start>=p_period_start and fp.period_end<=p_period_end and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id)), mapped as (select s.organization_id,s.account_id,s.currency,s.debit_minor,s.credit_minor,g.id group_id,g.code group_code,g.name group_name from scoped s join public.group_account_mappings m on m.root_organization_id=p_root_organization_id and m.organization_id=s.organization_id and m.account_id=s.account_id join public.group_reporting_accounts g on g.id=m.group_reporting_account_id and g.root_organization_id=p_root_organization_id and g.is_active), unmapped as (select s.*,a.code,a.name,o.name organization_name from scoped s join public.accounts a on a.id=s.account_id and a.organization_id=s.organization_id join public.organizations o on o.id=s.organization_id where not exists(select 1 from public.group_account_mappings m where m.root_organization_id=p_root_organization_id and m.organization_id=s.organization_id and m.account_id=s.account_id)), grouped_rows as (select group_id,group_code,group_name,currency,sum(debit_minor)::bigint period_debit,sum(credit_minor)::bigint period_credit,(sum(debit_minor)-sum(credit_minor))::bigint period_net from mapped group by group_id,group_code,group_name,currency), unmapped_rows as (select organization_id,organization_name,code,name,currency,sum(debit_minor)::bigint period_debit,sum(credit_minor)::bigint period_credit,(sum(debit_minor)-sum(credit_minor))::bigint period_net from unmapped group by organization_id,organization_name,code,name,currency)
 select coalesce((select jsonb_agg(to_jsonb(grouped_rows) order by currency,group_code) from grouped_rows),'[]'::jsonb),coalesce((select jsonb_agg(to_jsonb(unmapped_rows) order by organization_name,code) from unmapped_rows),'[]'::jsonb) into v_rows,v_unmapped;
 return jsonb_build_object('root_organization_id',p_root_organization_id,'period_start',p_period_start,'period_end',p_period_end,'organizations',v_orgs,'rows',v_rows,'unmapped_rows',v_unmapped);
end $function$;
