-- Forecast engine: forecast management metrics directly instead of forecasting components then deriving EBITDA/NI.
-- Production-equivalent definitions were applied to Supabase before this ledger sync.

create or replace function public.get_executive_dashboard_forecast(p_organization_id uuid,p_start_date date,p_end_date date,p_branch_id uuid default null,p_department_id uuid default null,p_cost_center_id uuid default null,p_region_id uuid default null,p_product_id uuid default null,p_project_id uuid default null,p_account_id uuid default null,p_horizon_months integer default 3) returns jsonb language plpgsql security definer set search_path='' set statement_timeout='15s' as $function$
declare v_user_id uuid:=auth.uid(); v_result jsonb;
begin
 if v_user_id is null then raise exception 'Authentication required'; end if;
 if p_start_date is null or p_end_date is null or p_start_date>p_end_date then raise exception 'Invalid date range'; end if;
 if p_horizon_months<1 or p_horizon_months>12 then raise exception 'Invalid forecast horizon'; end if;
 if not exists(select 1 from public.organization_members om where om.organization_id=p_organization_id and om.user_id=v_user_id) then raise exception 'Organization access required'; end if;
 if not public.has_org_permission(p_organization_id,'screen.forecast.view') then raise exception 'Not authorized'; end if;
 with scope_flags as materialized (select coalesce(array_agg(s.scope_id) filter(where s.scope_type='legal_entity'),'{}'::uuid[]) legal_entities,coalesce(array_agg(s.scope_id) filter(where s.scope_type='branch'),'{}'::uuid[]) branches,coalesce(array_agg(s.scope_id) filter(where s.scope_type='department'),'{}'::uuid[]) departments,coalesce(array_agg(s.scope_id) filter(where s.scope_type='cost_center'),'{}'::uuid[]) cost_centers,coalesce(array_agg(s.scope_id) filter(where s.scope_type='region'),'{}'::uuid[]) regions,coalesce(array_agg(s.scope_id) filter(where s.scope_type='product'),'{}'::uuid[]) products,coalesce(array_agg(s.scope_id) filter(where s.scope_type='project'),'{}'::uuid[]) projects,count(*)>0 has_any from public.organization_member_scopes s where s.organization_id=p_organization_id and s.user_id=v_user_id),
facts as materialized (select f.debit_minor,f.credit_minor,f.transaction_date,a.statement_subclassification,a.cash_flow_direct_category,f.account_id,f.legal_entity_id,f.branch_id,f.department_id,f.cost_center_id,f.region_id,f.product_id,f.project_id from public.financial_facts f join public.accounts a on a.id=f.account_id and a.organization_id=p_organization_id cross join scope_flags sf where f.organization_id=p_organization_id and f.fact_type='actual' and f.status='published' and f.transaction_date between p_start_date and p_end_date and (p_branch_id is null or f.branch_id=p_branch_id) and (p_department_id is null or f.department_id=p_department_id) and (p_cost_center_id is null or f.cost_center_id=p_cost_center_id) and (p_region_id is null or f.region_id=p_region_id) and (p_product_id is null or f.product_id=p_product_id) and (p_project_id is null or f.project_id=p_project_id) and (p_account_id is null or f.account_id=p_account_id) and (not sf.has_any or cardinality(sf.legal_entities)=0 or f.legal_entity_id is null or f.legal_entity_id=any(sf.legal_entities)) and (not sf.has_any or cardinality(sf.branches)=0 or f.branch_id is null or f.branch_id=any(sf.branches)) and (not sf.has_any or cardinality(sf.departments)=0 or f.department_id is null or f.department_id=any(sf.departments)) and (not sf.has_any or cardinality(sf.cost_centers)=0 or f.cost_center_id is null or f.cost_center_id=any(sf.cost_centers)) and (not sf.has_any or cardinality(sf.regions)=0 or f.region_id is null or f.region_id=any(sf.regions)) and (not sf.has_any or cardinality(sf.products)=0 or f.product_id is null or f.product_id=any(sf.products)) and (not sf.has_any or cardinality(sf.projects)=0 or f.project_id is null or f.project_id=any(sf.projects))),
months as (select gs::date month_start from generate_series(date_trunc('month',p_start_date)::date,date_trunc('month',p_end_date)::date,interval '1 month') gs),
monthly_components as (select m.month_start,coalesce(sum(case when f.statement_subclassification='revenue' then f.credit_minor-f.debit_minor else 0 end),0)::numeric revenue,coalesce(sum(case when f.statement_subclassification='cogs' then f.debit_minor-f.credit_minor else 0 end),0)::numeric cogs,coalesce(sum(case when f.statement_subclassification='operating_expense' then f.debit_minor-f.credit_minor else 0 end),0)::numeric opex,coalesce(sum(case when f.statement_subclassification='other_income' then f.credit_minor-f.debit_minor else 0 end),0)::numeric other_income,coalesce(sum(case when f.statement_subclassification='depreciation_amortization' then f.debit_minor-f.credit_minor else 0 end),0)::numeric da,coalesce(sum(case when f.statement_subclassification='finance_cost' then f.debit_minor-f.credit_minor else 0 end),0)::numeric finance,coalesce(sum(case when f.statement_subclassification='other_expense' then f.debit_minor-f.credit_minor else 0 end),0)::numeric other_expense,coalesce(sum(case when f.statement_subclassification='tax' then f.debit_minor-f.credit_minor else 0 end),0)::numeric tax,coalesce(sum(case when f.cash_flow_direct_category='operating_inflow' then f.credit_minor-f.debit_minor when f.cash_flow_direct_category='operating_outflow' then f.debit_minor-f.credit_minor else 0 end),0)::numeric operating_cash_flow from months m left join facts f on f.transaction_date between greatest(m.month_start,p_start_date) and least((m.month_start+interval '1 month - 1 day')::date,p_end_date) group by m.month_start),
observed as (select month_start,revenue,cogs,opex,other_income,da,finance,other_expense,tax,operating_cash_flow,(revenue-cogs)::numeric gross_profit,(revenue-cogs-opex+other_income)::numeric ebitda,(revenue-cogs-opex+other_income-da-finance-other_expense-tax)::numeric net_income from monthly_components where revenue<>0 or cogs<>0 or opex<>0 or other_income<>0 or da<>0 or finance<>0 or other_expense<>0 or tax<>0 or operating_cash_flow<>0),
recent as (select * from observed order by month_start desc limit 6),
stats as (select count(*)::integer n,regr_slope(revenue,extract(epoch from month_start)/2629800.0) revenue_slope,regr_intercept(revenue,extract(epoch from month_start)/2629800.0) revenue_intercept,regr_slope(gross_profit,extract(epoch from month_start)/2629800.0) gross_profit_slope,regr_intercept(gross_profit,extract(epoch from month_start)/2629800.0) gross_profit_intercept,regr_slope(ebitda,extract(epoch from month_start)/2629800.0) ebitda_slope,regr_intercept(ebitda,extract(epoch from month_start)/2629800.0) ebitda_intercept,regr_slope(net_income,extract(epoch from month_start)/2629800.0) net_income_slope,regr_intercept(net_income,extract(epoch from month_start)/2629800.0) net_income_intercept,regr_slope(operating_cash_flow,extract(epoch from month_start)/2629800.0) ocf_slope,regr_intercept(operating_cash_flow,extract(epoch from month_start)/2629800.0) ocf_intercept from recent),
horizon as (select gs::date month_start from generate_series((date_trunc('month',p_end_date)+interval '1 month')::date,(date_trunc('month',p_end_date)+make_interval(months=>p_horizon_months))::date,interval '1 month') gs),
fv as (select h.month_start,s.n,(s.revenue_slope*extract(epoch from h.month_start)/2629800.0+s.revenue_intercept)::numeric revenue,(s.gross_profit_slope*extract(epoch from h.month_start)/2629800.0+s.gross_profit_intercept)::numeric gross_profit,(s.ebitda_slope*extract(epoch from h.month_start)/2629800.0+s.ebitda_intercept)::numeric ebitda,(s.net_income_slope*extract(epoch from h.month_start)/2629800.0+s.net_income_intercept)::numeric net_income,(s.ocf_slope*extract(epoch from h.month_start)/2629800.0+s.ocf_intercept)::numeric operating_cash_flow from horizon h cross join stats s),
payload as (select jsonb_agg(jsonb_build_object('month',to_char(month_start,'YYYY-MM'),'revenue',round(revenue)::bigint,'gross_profit',round(gross_profit)::bigint,'ebitda',round(ebitda)::bigint,'net_income',round(net_income)::bigint,'operating_cash_flow',round(operating_cash_flow)::bigint) order by month_start) forecast from fv)
select jsonb_build_object('ready',(select n>=6 from stats),'history_months',(select n from stats),'minimum_history_months',6,'horizon_months',p_horizon_months,'forecast',coalesce((select forecast from payload),'[]'::jsonb),'methodology',jsonb_build_object('model','linear_trend_over_last_6_observed_management_metrics','source','published actual financial facts','actuals_only',true,'published_only',true,'no_missing_as_zero',true,'filters_applied',true,'metrics_directly_forecasted',jsonb_build_array('revenue','gross_profit','ebitda','net_income','operating_cash_flow'))) into v_result;
return v_result;
end;$function$;
revoke all on function public.get_executive_dashboard_forecast(uuid,date,date,uuid,uuid,uuid,uuid,uuid,uuid,uuid,integer) from public,anon;
grant execute on function public.get_executive_dashboard_forecast(uuid,date,date,uuid,uuid,uuid,uuid,uuid,uuid,uuid,integer) to authenticated;

create or replace function public.get_executive_dashboard_forecast_validation(p_organization_id uuid,p_start_date date,p_end_date date,p_branch_id uuid default null,p_department_id uuid default null,p_cost_center_id uuid default null,p_region_id uuid default null,p_product_id uuid default null,p_project_id uuid default null,p_account_id uuid default null) returns jsonb language plpgsql security definer set search_path='' set statement_timeout='15s' as $function$
declare v_user_id uuid:=auth.uid(); v_result jsonb;
begin
 if v_user_id is null then raise exception 'Authentication required'; end if;
 if p_start_date is null or p_end_date is null or p_start_date>p_end_date then raise exception 'Invalid date range'; end if;
 if not exists(select 1 from public.organization_members om where om.organization_id=p_organization_id and om.user_id=v_user_id) then raise exception 'Organization access required'; end if;
 if not public.has_org_permission(p_organization_id,'screen.forecast.view') then raise exception 'Not authorized'; end if;
 with scope_flags as materialized (select coalesce(array_agg(s.scope_id) filter(where s.scope_type='legal_entity'),'{}'::uuid[]) legal_entities,coalesce(array_agg(s.scope_id) filter(where s.scope_type='branch'),'{}'::uuid[]) branches,coalesce(array_agg(s.scope_id) filter(where s.scope_type='department'),'{}'::uuid[]) departments,coalesce(array_agg(s.scope_id) filter(where s.scope_type='cost_center'),'{}'::uuid[]) cost_centers,coalesce(array_agg(s.scope_id) filter(where s.scope_type='region'),'{}'::uuid[]) regions,coalesce(array_agg(s.scope_id) filter(where s.scope_type='product'),'{}'::uuid[]) products,coalesce(array_agg(s.scope_id) filter(where s.scope_type='project'),'{}'::uuid[]) projects,count(*)>0 has_any from public.organization_member_scopes s where s.organization_id=p_organization_id and s.user_id=v_user_id),
facts as materialized (select f.debit_minor,f.credit_minor,f.transaction_date,a.statement_subclassification,a.cash_flow_direct_category,f.account_id,f.legal_entity_id,f.branch_id,f.department_id,f.cost_center_id,f.region_id,f.product_id,f.project_id from public.financial_facts f join public.accounts a on a.id=f.account_id and a.organization_id=p_organization_id cross join scope_flags sf where f.organization_id=p_organization_id and f.fact_type='actual' and f.status='published' and f.transaction_date between p_start_date and p_end_date and (p_branch_id is null or f.branch_id=p_branch_id) and (p_department_id is null or f.department_id=p_department_id) and (p_cost_center_id is null or f.cost_center_id=p_cost_center_id) and (p_region_id is null or f.region_id=p_region_id) and (p_product_id is null or f.product_id=p_product_id) and (p_project_id is null or f.project_id=p_project_id) and (p_account_id is null or f.account_id=p_account_id) and (not sf.has_any or cardinality(sf.legal_entities)=0 or f.legal_entity_id is null or f.legal_entity_id=any(sf.legal_entities)) and (not sf.has_any or cardinality(sf.branches)=0 or f.branch_id is null or f.branch_id=any(sf.branches)) and (not sf.has_any or cardinality(sf.departments)=0 or f.department_id is null or f.department_id=any(sf.departments)) and (not sf.has_any or cardinality(sf.cost_centers)=0 or f.cost_center_id is null or f.cost_center_id=any(sf.cost_centers)) and (not sf.has_any or cardinality(sf.regions)=0 or f.region_id is null or f.region_id=any(sf.regions)) and (not sf.has_any or cardinality(sf.products)=0 or f.product_id is null or f.product_id=any(sf.products)) and (not sf.has_any or cardinality(sf.projects)=0 or f.project_id is null or f.project_id=any(sf.projects))),
months as (select gs::date month_start from generate_series(date_trunc('month',p_start_date)::date,date_trunc('month',p_end_date)::date,interval '1 month') gs),
monthly_components as (select m.month_start,coalesce(sum(case when f.statement_subclassification='revenue' then f.credit_minor-f.debit_minor else 0 end),0)::numeric revenue,coalesce(sum(case when f.statement_subclassification='cogs' then f.debit_minor-f.credit_minor else 0 end),0)::numeric cogs,coalesce(sum(case when f.statement_subclassification='operating_expense' then f.debit_minor-f.credit_minor else 0 end),0)::numeric opex,coalesce(sum(case when f.statement_subclassification='other_income' then f.credit_minor-f.debit_minor else 0 end),0)::numeric other_income,coalesce(sum(case when f.statement_subclassification='depreciation_amortization' then f.debit_minor-f.credit_minor else 0 end),0)::numeric da,coalesce(sum(case when f.statement_subclassification='finance_cost' then f.debit_minor-f.credit_minor else 0 end),0)::numeric finance,coalesce(sum(case when f.statement_subclassification='other_expense' then f.debit_minor-f.credit_minor else 0 end),0)::numeric other_expense,coalesce(sum(case when f.statement_subclassification='tax' then f.debit_minor-f.credit_minor else 0 end),0)::numeric tax,coalesce(sum(case when f.cash_flow_direct_category='operating_inflow' then f.credit_minor-f.debit_minor when f.cash_flow_direct_category='operating_outflow' then f.debit_minor-f.credit_minor else 0 end),0)::numeric operating_cash_flow from months m left join facts f on f.transaction_date between m.month_start and (m.month_start+interval '1 month - 1 day')::date group by m.month_start),
observed as (select month_start,revenue,cogs,opex,other_income,da,finance,other_expense,tax,operating_cash_flow,(revenue-cogs)::numeric gross_profit,(revenue-cogs-opex+other_income)::numeric ebitda,(revenue-cogs-opex+other_income-da-finance-other_expense-tax)::numeric net_income,row_number() over(order by month_start) rn from monthly_components where revenue<>0 or cogs<>0 or opex<>0 or other_income<>0 or da<>0 or finance<>0 or other_expense<>0 or tax<>0 or operating_cash_flow<>0),
targets as (select * from observed where rn>(select max(rn)-3 from observed) and rn>=7),
backtest as (select t.*,s.* from targets t cross join lateral (select regr_slope(r.revenue,extract(epoch from r.month_start)/2629800.0) revenue_slope,regr_intercept(r.revenue,extract(epoch from r.month_start)/2629800.0) revenue_intercept,regr_slope(r.gross_profit,extract(epoch from r.month_start)/2629800.0) gross_profit_slope,regr_intercept(r.gross_profit,extract(epoch from r.month_start)/2629800.0) gross_profit_intercept,regr_slope(r.ebitda,extract(epoch from r.month_start)/2629800.0) ebitda_slope,regr_intercept(r.ebitda,extract(epoch from r.month_start)/2629800.0) ebitda_intercept,regr_slope(r.net_income,extract(epoch from r.month_start)/2629800.0) net_income_slope,regr_intercept(r.net_income,extract(epoch from r.month_start)/2629800.0) net_income_intercept,regr_slope(r.operating_cash_flow,extract(epoch from r.month_start)/2629800.0) ocf_slope,regr_intercept(r.operating_cash_flow,extract(epoch from r.month_start)/2629800.0) ocf_intercept from observed r where r.rn between t.rn-6 and t.rn-1) s),
predicted as (select b.*,coalesce(b.revenue_slope*extract(epoch from b.month_start)/2629800.0+b.revenue_intercept,0)::numeric revenue_f,coalesce(b.gross_profit_slope*extract(epoch from b.month_start)/2629800.0+b.gross_profit_intercept,0)::numeric gross_profit_f,coalesce(b.ebitda_slope*extract(epoch from b.month_start)/2629800.0+b.ebitda_intercept,0)::numeric ebitda_f,coalesce(b.net_income_slope*extract(epoch from b.month_start)/2629800.0+b.net_income_intercept,0)::numeric net_income_f,coalesce(b.ocf_slope*extract(epoch from b.month_start)/2629800.0+b.ocf_intercept,0)::numeric ocf_f from backtest b),
errors as (select p.*,case when p.revenue<>0 then abs(p.revenue-p.revenue_f)/abs(p.revenue)*100 end revenue_ape,case when p.gross_profit<>0 then abs(p.gross_profit-p.gross_profit_f)/abs(p.gross_profit)*100 end gross_profit_ape,case when p.ebitda<>0 then abs(p.ebitda-p.ebitda_f)/abs(p.ebitda)*100 end ebitda_ape,case when p.operating_cash_flow<>0 then abs(p.operating_cash_flow-p.ocf_f)/abs(p.operating_cash_flow)*100 end operating_cash_flow_ape from predicted p),
summary as (select count(*)::integer backtest_months,round(avg(revenue_ape)::numeric,2) revenue_mape,round(avg(gross_profit_ape)::numeric,2) gross_profit_mape,round(avg(ebitda_ape)::numeric,2) ebitda_mape,round(avg(operating_cash_flow_ape)::numeric,2) operating_cash_flow_mape from errors),
scored_summary as (select s.*,round((select avg(v)::numeric from (values(s.revenue_mape),(s.gross_profit_mape),(s.ebitda_mape),(s.operating_cash_flow_mape)) q(v) where v is not null),2) overall_mape from summary s),
rows_payload as (select coalesce(jsonb_agg(jsonb_build_object('month',to_char(e.month_start,'YYYY-MM'),'actual',jsonb_build_object('revenue',round(e.revenue)::bigint,'gross_profit',round(e.gross_profit)::bigint,'ebitda',round(e.ebitda)::bigint,'net_income',round(e.net_income)::bigint,'operating_cash_flow',round(e.operating_cash_flow)::bigint),'forecast',jsonb_build_object('revenue',round(e.revenue_f)::bigint,'gross_profit',round(e.gross_profit_f)::bigint,'ebitda',round(e.ebitda_f)::bigint,'net_income',round(e.net_income_f)::bigint,'operating_cash_flow',round(e.ocf_f)::bigint),'variance',jsonb_build_object('revenue',round(e.revenue-e.revenue_f)::bigint,'gross_profit',round(e.gross_profit-e.gross_profit_f)::bigint,'ebitda',round(e.ebitda-e.ebitda_f)::bigint,'net_income',round(e.net_income-e.net_income_f)::bigint,'operating_cash_flow',round(e.operating_cash_flow-e.ocf_f)::bigint),'ape',jsonb_build_object('revenue',round(e.revenue_ape::numeric,2),'gross_profit',round(e.gross_profit_ape::numeric,2),'ebitda',round(e.ebitda_ape::numeric,2),'operating_cash_flow',round(e.operating_cash_flow_ape::numeric,2))) order by e.month_start),'[]'::jsonb) rows from errors e)
select jsonb_build_object('validated',(select backtest_months>=3 from scored_summary),'backtest_months',(select backtest_months from scored_summary),'minimum_backtest_months',3,'metrics',jsonb_build_object('revenue_mape',(select revenue_mape from scored_summary),'gross_profit_mape',(select gross_profit_mape from scored_summary),'ebitda_mape',(select ebitda_mape from scored_summary),'operating_cash_flow_mape',(select operating_cash_flow_mape from scored_summary),'overall_mape',(select overall_mape from scored_summary)),'quality',case when (select backtest_months from scored_summary)<3 or (select overall_mape from scored_summary) is null then 'insufficient' when (select max(v) from (values((select revenue_mape from scored_summary)),((select gross_profit_mape from scored_summary)),((select ebitda_mape from scored_summary)),((select operating_cash_flow_mape from scored_summary))) q(v) where v is not null)>50 then 'low' when (select overall_mape from scored_summary)<=10 then 'high' when (select overall_mape from scored_summary)<=30 then 'moderate' else 'low' end,'rows',(select rows from rows_payload),'methodology',jsonb_build_object('model','linear_trend_over_last_6_observed_management_metrics','validation','rolling_holdout_up_to_3_latest_observed_months','error_metric','MAPE','quality_rules',jsonb_build_object('insufficient','backtest_months<3_or_overall_mape_null','high','overall_mape<=10_and_no_metric_mape_above_50','moderate','overall_mape<=30_and_no_metric_mape_above_50','low','any_metric_mape>50_or_overall_mape>30'),'actuals_only',true,'published_only',true,'missing_months_excluded',true,'filters_applied',true,'metrics_directly_forecasted',jsonb_build_array('revenue','gross_profit','ebitda','net_income','operating_cash_flow'))) into v_result;
return v_result;
end;$function$;
revoke all on function public.get_executive_dashboard_forecast_validation(uuid,date,date,uuid,uuid,uuid,uuid,uuid,uuid,uuid) from public,anon;
grant execute on function public.get_executive_dashboard_forecast_validation(uuid,date,date,uuid,uuid,uuid,uuid,uuid,uuid,uuid) to authenticated;
