create or replace function public.get_variance_analysis(p_organization_id uuid, p_period_id uuid, p_budget_version_id uuid, p_forecast_version_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $func$
declare v_result jsonb;
begin
 if auth.uid() is null or not public.has_org_permission(p_organization_id,'view') then raise exception 'forbidden'; end if;
 if not exists(select 1 from public.financial_periods where id=p_period_id and organization_id=p_organization_id) then raise exception 'invalid period'; end if;
 if not exists(select 1 from public.planning_versions where id=p_budget_version_id and organization_id=p_organization_id and version_type='budget' and status='approved') then raise exception 'budget version must be approved'; end if;
 if p_forecast_version_id is not null and not exists(select 1 from public.planning_versions where id=p_forecast_version_id and organization_id=p_organization_id and version_type='forecast' and status='approved') then raise exception 'forecast version must be approved'; end if;
 with actuals as (select ff.account_id,sum(ff.amount_minor)::bigint amount_minor from public.financial_facts ff where ff.organization_id=p_organization_id and ff.financial_period_id=p_period_id and ff.status='published' group by ff.account_id), budget as (select bl.account_id,sum(bl.amount_minor)::bigint amount_minor from public.budget_lines bl where bl.organization_id=p_organization_id and bl.planning_version_id=p_budget_version_id and bl.financial_period_id=p_period_id group by bl.account_id), forecast as (select fl.account_id,sum(fl.amount_minor)::bigint amount_minor from public.forecast_lines fl where fl.organization_id=p_organization_id and fl.planning_version_id=p_forecast_version_id and fl.financial_period_id=p_period_id group by fl.account_id), rows as (select a.id account_id,a.code,a.name,a.account_type,coalesce(x.amount_minor,0)::bigint actual_minor,coalesce(b.amount_minor,0)::bigint budget_minor,coalesce(f.amount_minor,0)::bigint forecast_minor from public.accounts a left join actuals x on x.account_id=a.id left join budget b on b.account_id=a.id left join forecast f on f.account_id=a.id where a.organization_id=p_organization_id and (x.account_id is not null or b.account_id is not null or f.account_id is not null)), m as (select coalesce(sum(actual_minor) filter(where lower(account_type) in ('revenue','income','sales')),0)::bigint ar,coalesce(sum(budget_minor) filter(where lower(account_type) in ('revenue','income','sales')),0)::bigint br,coalesce(sum(forecast_minor) filter(where lower(account_type) in ('revenue','income','sales')),0)::bigint fr,coalesce(sum(actual_minor) filter(where lower(account_type) in ('cogs','cost_of_sales')),0)::bigint ac,coalesce(sum(budget_minor) filter(where lower(account_type) in ('cogs','cost_of_sales')),0)::bigint bc,coalesce(sum(forecast_minor) filter(where lower(account_type) in ('cogs','cost_of_sales')),0)::bigint fc,coalesce(sum(actual_minor) filter(where lower(account_type) in ('opex','operating_expense')),0)::bigint ao,coalesce(sum(budget_minor) filter(where lower(account_type) in ('opex','operating_expense')),0)::bigint bo,coalesce(sum(forecast_minor) filter(where lower(account_type) in ('opex','operating_expense')),0)::bigint fo from rows)
 select jsonb_build_object('period_id',p_period_id,'budget_version_id',p_budget_version_id,'forecast_version_id',p_forecast_version_id,'rows',coalesce((select jsonb_agg(jsonb_build_object('account_id',account_id,'code',code,'name',name,'account_type',account_type,'actual_minor',actual_minor,'budget_minor',budget_minor,'forecast_minor',forecast_minor,'variance_vs_budget_minor',actual_minor-budget_minor,'variance_vs_forecast_minor',case when p_forecast_version_id is null then null else actual_minor-forecast_minor end,'variance_vs_budget_pct',case when budget_minor=0 then null else round(((actual_minor-budget_minor)::numeric/abs(budget_minor))*100,2) end) order by code) from rows),'[]'::jsonb),'metrics',(select jsonb_build_object('revenue',jsonb_build_object('actual_minor',ar,'budget_minor',br,'forecast_minor',fr,'variance_vs_budget_minor',ar-br,'variance_vs_forecast_minor',case when p_forecast_version_id is null then null else ar-fr end),'cogs',jsonb_build_object('actual_minor',ac,'budget_minor',bc,'forecast_minor',fc,'variance_vs_budget_minor',ac-bc,'variance_vs_forecast_minor',case when p_forecast_version_id is null then null else ac-fc end),'gross_profit',jsonb_build_object('actual_minor',ar-ac,'budget_minor',br-bc,'forecast_minor',fr-fc,'variance_vs_budget_minor',(ar-ac)-(br-bc),'variance_vs_forecast_minor',case when p_forecast_version_id is null then null else (ar-ac)-(fr-fc) end),'opex',jsonb_build_object('actual_minor',ao,'budget_minor',bo,'forecast_minor',fo,'variance_vs_budget_minor',ao-bo,'variance_vs_forecast_minor',case when p_forecast_version_id is null then null else ao-fo end),'ebitda',jsonb_build_object('actual_minor',ar-ac-ao,'budget_minor',br-bc-bo,'forecast_minor',fr-fc-fo,'variance_vs_budget_minor',(ar-ac-ao)-(br-bc-bo),'variance_vs_forecast_minor',case when p_forecast_version_id is null then null else (ar-ac-ao)-(fr-fc-fo) end)) from m)) into v_result;
 return v_result;
end;
$func$;
revoke all on function public.get_variance_analysis(uuid,uuid,uuid,uuid) from public,anon;
grant execute on function public.get_variance_analysis(uuid,uuid,uuid,uuid) to authenticated;
