-- Add scoped action permissions for forecast and scenarios and backfill initialized users.
insert into public.organization_permissions(permission_key,name,description,permission_type,screen_key,route_path,category,sort_order) values
 ('forecast.view','عرض التوقعات','عرض شاشة التوقعات','action','forecast','/workspace/forecast','planning',1010),('forecast.create','إنشاء توقع','إنشاء إصدار توقع جديد','action','forecast','/workspace/forecast','planning',1011),('forecast.edit','تعديل التوقع','تعديل بيانات التوقع','action','forecast','/workspace/forecast','planning',1012),('forecast.delete','حذف التوقع','حذف بيانات التوقع','action','forecast','/workspace/forecast','planning',1013),('forecast.submit','إرسال التوقع','إرسال التوقع للمراجعة','action','forecast','/workspace/forecast','planning',1014),('forecast.approve','اعتماد التوقع','اعتماد التوقع','action','forecast','/workspace/forecast','planning',1015),('forecast.reject','رفض التوقع','رفض التوقع أو طلب تعديله','action','forecast','/workspace/forecast','planning',1016),
 ('scenario.view','عرض السيناريوهات','عرض السيناريوهات','action','scenarios','/workspace/scenarios','planning',1020),('scenario.create','إنشاء سيناريو','إنشاء سيناريو جديد','action','scenarios','/workspace/scenarios','planning',1021),('scenario.edit','تعديل السيناريو','تعديل السيناريو','action','scenarios','/workspace/scenarios','planning',1022),('scenario.delete','حذف السيناريو','حذف السيناريو','action','scenarios','/workspace/scenarios','planning',1023),('scenario.run','تشغيل السيناريو','تشغيل حسابات السيناريو','action','scenarios','/workspace/scenarios','planning',1024)
on conflict(permission_key) do update set name=excluded.name,description=excluded.description,permission_type=excluded.permission_type,screen_key=excluded.screen_key,route_path=excluded.route_path,category=excluded.category,sort_order=excluded.sort_order;

insert into public.organization_role_permissions(organization_id,role_key,permission_key)
select o.id,r.role_key,p.permission_key from public.organizations o
cross join (values('company_admin'),('executive_director'),('cfo'),('finance_manager'),('fpa_analyst'),('accountant'),('department_manager'),('viewer')) r(role_key)
cross join (values('forecast.view'),('forecast.create'),('forecast.edit'),('forecast.delete'),('forecast.submit'),('forecast.approve'),('forecast.reject'),('scenario.view'),('scenario.create'),('scenario.edit'),('scenario.delete'),('scenario.run')) p(permission_key)
where not exists(select 1 from public.organization_role_permissions x where x.organization_id=o.id and x.role_key=r.role_key and x.permission_key=p.permission_key);

insert into public.organization_member_permission_overrides(organization_id,user_id,permission_key,granted)
select m.organization_id,m.user_id,p.permission_key,true from public.organization_members m
cross join lateral (values
 ('forecast.view',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('view','manage_forecast') and x.granted)),('forecast.create',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('create','manage_forecast') and x.granted)),('forecast.edit',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('edit','manage_forecast') and x.granted)),('forecast.delete',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('delete','manage_forecast') and x.granted)),('forecast.submit',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('submit','manage_forecast') and x.granted)),('forecast.approve',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('approve','manage_forecast') and x.granted)),('forecast.reject',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('reject','manage_forecast') and x.granted)),('scenario.view',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('view','manage_scenarios') and x.granted)),('scenario.create',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('create','manage_scenarios') and x.granted)),('scenario.edit',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('edit','manage_scenarios') and x.granted)),('scenario.delete',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('delete','manage_scenarios') and x.granted)),('scenario.run',exists(select 1 from public.organization_member_permission_overrides x where x.organization_id=m.organization_id and x.user_id=m.user_id and x.permission_key in('manage_scenarios','submit') and x.granted))
) p(permission_key,granted) where m.permissions_initialized=true and p.granted on conflict(organization_id,user_id,permission_key) do update set granted=excluded.granted;
