create or replace function public.get_financial_statements_date_range(
  p_organization_id uuid,p_start_date date,p_end_date date,p_branch_id uuid default null,p_department_id uuid default null,p_cost_center_id uuid default null,p_region_id uuid default null,p_product_id uuid default null,p_project_id uuid default null,p_account_id uuid default null,p_cash_flow_method text default 'indirect'
) returns jsonb language plpgsql security definer set search_path='' as $function$
declare
 r record; x jsonb; oci jsonb; first_r jsonb:='{}'; last_r jsonb:='{}'; periods jsonb:='[]'; n int:=0; v_income jsonb:='{}'; v_cash jsonb:='{}'; v_balance jsonb:='{}'; v_equity jsonb:='{}'; v_oci_period jsonb:='[]'; k text; s bigint; op_in bigint:=0; op_out bigint:=0; op_net bigint:=0; inv_net bigint:=0; fin_net bigint:=0; inv_in bigint:=0; inv_out bigint:=0; fin_in bigint:=0; fin_out bigint:=0; dep bigint:=0; wc bigint:=0; ni bigint:=0; net_change bigint:=0; opening_cash bigint:=0; closing_cash bigint:=0; recon bigint:=0;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if not (public.has_org_permission(p_organization_id,'screen.financial_statements.view') or public.has_org_permission(p_organization_id,'statements.view') or public.has_org_permission(p_organization_id,'view')) then raise exception 'Financial statements view permission required'; end if;
 if p_start_date is null or p_end_date is null or p_start_date>p_end_date then raise exception 'Invalid date range'; end if;
 if p_cash_flow_method not in ('direct','indirect') then raise exception 'Invalid cash flow method'; end if;
 for r in select id,period_start,period_end,status from public.financial_periods where organization_id=p_organization_id and period_start>=p_start_date and period_end<=p_end_date order by period_start loop
  x:=public.get_financial_statements_v2(p_organization_id,r.id,p_branch_id,p_department_id,p_cost_center_id,p_region_id,p_product_id,p_project_id,p_account_id,p_cash_flow_method); oci:=public.get_other_comprehensive_income(p_organization_id,r.id,p_branch_id,p_department_id,p_cost_center_id,p_region_id,p_product_id,p_project_id);
  if n=0 then first_r:=x; opening_cash:=coalesce((x->'cash_flow'->>'opening_cash')::bigint,0); end if;
  last_r:=x; n:=n+1; periods:=periods||jsonb_build_object('id',r.id,'start',r.period_start,'end',r.period_end,'status',r.status);
  foreach k in array array['revenue','cogs','operating_expenses','other_income','depreciation_amortization','finance_cost','other_expenses','tax','net_income'] loop s:=coalesce((x->'income_statement'->>k)::bigint,0); v_income:=jsonb_set(v_income,array[k],to_jsonb(coalesce((v_income->>k)::bigint,0)+s),true); end loop;
  if p_cash_flow_method='direct' then op_in:=op_in+coalesce((x->'cash_flow'->'operating'->>'cash_inflows')::bigint,0); op_out:=op_out+coalesce((x->'cash_flow'->'operating'->>'cash_outflows')::bigint,0); else ni:=ni+coalesce((x->'cash_flow'->'operating'->>'net_income')::bigint,0); dep:=dep+coalesce((x->'cash_flow'->'operating'->>'depreciation_amortization')::bigint,0); wc:=wc+coalesce((x->'cash_flow'->'operating'->>'working_capital_change')::bigint,0); end if;
  inv_net:=inv_net+coalesce((x->'cash_flow'->'investing'->>'net_cash_flow')::bigint,0); inv_in:=inv_in+coalesce((x->'cash_flow'->'investing'->>'cash_inflows')::bigint,0); inv_out:=inv_out+coalesce((x->'cash_flow'->'investing'->>'cash_outflows')::bigint,0); fin_net:=fin_net+coalesce((x->'cash_flow'->'financing'->>'net_cash_flow')::bigint,0); fin_in:=fin_in+coalesce((x->'cash_flow'->'financing'->>'cash_inflows')::bigint,0); fin_out:=fin_out+coalesce((x->'cash_flow'->'financing'->>'cash_outflows')::bigint,0); v_oci_period:=v_oci_period||coalesce(oci->'period'->'rows','[]'::jsonb);
 end loop;
 if n=0 then raise exception 'No financial periods fully contained in the selected date range'; end if;
 closing_cash:=coalesce((last_r->'cash_flow'->>'closing_cash')::bigint,0); net_change:=closing_cash-opening_cash; if p_cash_flow_method='direct' then op_net:=op_in-op_out; else op_net:=ni+dep+wc; end if; recon:=net_change-(op_net+inv_net+fin_net);
 v_cash:=jsonb_build_object('method',p_cash_flow_method,'opening_cash',opening_cash,'closing_cash',closing_cash,'net_change',net_change,'operating',case when p_cash_flow_method='direct' then jsonb_build_object('cash_inflows',op_in,'cash_outflows',op_out,'net_operating_cash_flow',op_net) else jsonb_build_object('net_income',ni,'depreciation_amortization',dep,'working_capital_change',wc,'net_operating_cash_flow',op_net) end,'investing',jsonb_build_object('net_cash_flow',inv_net,'cash_inflows',inv_in,'cash_outflows',inv_out),'financing',jsonb_build_object('net_cash_flow',fin_net,'cash_inflows',fin_in,'cash_outflows',fin_out),'reconciliation_difference',recon,'direct_data_quality',coalesce(last_r->'cash_flow'->>'direct_data_quality','unknown'));
 v_balance:=coalesce(last_r->'balance_sheet','{}'); v_equity:=coalesce(last_r->'equity_statement','{}');
 return jsonb_build_object('range',jsonb_build_object('start',p_start_date,'end',p_end_date,'period_count',n,'periods',periods),'income_statement',v_income,'income_statement_ytd',coalesce(last_r->'income_statement_ytd','{}'),'balance_sheet',v_balance,'other_comprehensive_income',jsonb_build_object('period',jsonb_build_object('rows',v_oci_period,'total',coalesce((select sum((z->>'amount')::bigint) from jsonb_array_elements(v_oci_period) z),0)),'ytd',jsonb_build_object()),'cash_flow',v_cash,'equity_statement',v_equity,'validation',jsonb_build_object('balance_sheet_difference',coalesce((v_balance->>'balance_check')::bigint,0),'cash_flow_reconciliation_difference',recon,'equity_rollforward_difference',coalesce((last_r->'validation'->>'equity_rollforward_difference')::bigint,0),'unclassified_income_accounts',coalesce((last_r->'validation'->>'unclassified_income_accounts')::int,0)),'methodology',jsonb_build_object('range_aggregation','period_based','actuals_only',true,'published_only',true,'balance_sheet_as_of_range_end',true,'income_statement_sum_of_periods',true,'cash_flow_reconciled_from_range_opening_and_closing_cash',true));
end;$function$;
revoke all on function public.get_financial_statements_date_range(uuid,date,date,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text) from public,anon; grant execute on function public.get_financial_statements_date_range(uuid,date,date,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text) to authenticated;
