create or replace function public.set_account_equity_rollforward_role(p_organization_id uuid,p_account_id uuid,p_role text)
returns void language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if not (public.has_org_permission(p_organization_id,'screen.accounts.edit') or public.has_org_permission(p_organization_id,'accounts.edit') or public.has_org_permission(p_organization_id,'admin')) then raise exception 'Chart of accounts edit permission required'; end if;
 if p_role is not null and p_role not in ('capital_contribution','owner_distribution','retained_earnings','current_year_profit','other_comprehensive_income') then raise exception 'Invalid equity rollforward role'; end if;
 update public.accounts set equity_rollforward_role=p_role where id=p_account_id and organization_id=p_organization_id and statement_subclassification='equity';
 if not found then raise exception 'Equity account not found'; end if;
end; $$;
revoke all on function public.set_account_equity_rollforward_role(uuid,uuid,text) from public,anon;
grant execute on function public.set_account_equity_rollforward_role(uuid,uuid,text) to authenticated;

update public.accounts set equity_rollforward_role='capital_contribution' where code='3110' and statement_subclassification='equity' and equity_rollforward_role is null;
update public.accounts set equity_rollforward_role='owner_distribution' where code='3120' and statement_subclassification='equity' and equity_rollforward_role is null;
update public.accounts set equity_rollforward_role='retained_earnings' where code='3210' and statement_subclassification='equity' and equity_rollforward_role is null;

create or replace function public.get_equity_rollforward(p_organization_id uuid,p_period_id uuid,p_branch_id uuid default null,p_department_id uuid default null,p_cost_center_id uuid default null,p_region_id uuid default null,p_product_id uuid default null,p_project_id uuid default null,p_account_id uuid default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare p record; fy date; rows jsonb; opening_total bigint; closing_total bigint; contribution bigint; distribution bigint; retained bigint; profit bigint; oci bigint; recon bigint;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if not (public.has_org_permission(p_organization_id,'screen.financial_statements.view') or public.has_org_permission(p_organization_id,'statements.view') or public.has_org_permission(p_organization_id,'view')) then raise exception 'Financial statements view permission required'; end if;
 select fp.period_start,fp.period_end,o.fiscal_year_start_month into p from public.financial_periods fp join public.organizations o on o.id=fp.organization_id where fp.id=p_period_id and fp.organization_id=p_organization_id;
 if p.period_start is null then raise exception 'Financial period not found'; end if;
 fy:=make_date(extract(year from p.period_start)::integer-case when extract(month from p.period_start)::integer<greatest(1,least(12,p.fiscal_year_start_month)) then 1 else 0 end,greatest(1,least(12,p.fiscal_year_start_month)),1);
 with scoped as materialized (select f.account_id,f.debit_minor,f.credit_minor,fp.period_end,a.code,a.name,a.equity_rollforward_role from public.financial_facts f join public.financial_periods fp on fp.id=f.financial_period_id join public.accounts a on a.id=f.account_id and a.organization_id=p_organization_id where f.organization_id=p_organization_id and f.fact_type='actual' and f.status='published' and a.statement_subclassification='equity' and public.has_org_data_scope(f.organization_id,'legal_entity',f.legal_entity_id) and public.has_org_data_scope(f.organization_id,'branch',f.branch_id) and public.has_org_data_scope(f.organization_id,'department',f.department_id) and public.has_org_data_scope(f.organization_id,'cost_center',f.cost_center_id) and public.has_org_data_scope(f.organization_id,'region',f.region_id) and public.has_org_data_scope(f.organization_id,'product',f.product_id) and public.has_org_data_scope(f.organization_id,'project',f.project_id) and (p_branch_id is null or f.branch_id=p_branch_id) and (p_department_id is null or f.department_id=p_department_id) and (p_cost_center_id is null or f.cost_center_id=p_cost_center_id) and (p_region_id is null or f.region_id=p_region_id) and (p_product_id is null or f.product_id=p_product_id) and (p_project_id is null or f.project_id=p_project_id) and (p_account_id is null or f.account_id=p_account_id)), agg as (select code,name,equity_rollforward_role,coalesce(sum(debit_minor-credit_minor) filter(where period_end<fy),0)::bigint opening,coalesce(sum(debit_minor-credit_minor) filter(where period_end<=p.period_end),0)::bigint closing from scoped group by code,name,equity_rollforward_role), totals as (select coalesce(sum(opening),0)::bigint opening_total,coalesce(sum(closing),0)::bigint closing_total,coalesce(sum(closing-opening) filter(where equity_rollforward_role='capital_contribution'),0)::bigint contribution,coalesce(sum(closing-opening) filter(where equity_rollforward_role='owner_distribution'),0)::bigint distribution,coalesce(sum(closing-opening) filter(where equity_rollforward_role='retained_earnings'),0)::bigint retained,coalesce(sum(closing-opening) filter(where equity_rollforward_role='other_comprehensive_income'),0)::bigint oci from agg)
 select t.opening_total,t.closing_total,t.contribution,t.distribution,t.retained,t.oci into opening_total,closing_total,contribution,distribution,retained,oci from totals t;
 profit:=coalesce((select (public.get_financial_statements(p_organization_id,p_period_id,p_branch_id,p_department_id,p_cost_center_id,p_region_id,p_product_id,p_project_id,p_account_id,'indirect')->'income_statement_ytd'->>'net_income')::bigint),0);
 with scoped as (select f.account_id,f.debit_minor,f.credit_minor,fp.period_end,a.code,a.name,a.equity_rollforward_role from public.financial_facts f join public.financial_periods fp on fp.id=f.financial_period_id join public.accounts a on a.id=f.account_id and a.organization_id=p_organization_id where f.organization_id=p_organization_id and f.fact_type='actual' and f.status='published' and a.statement_subclassification='equity' and public.has_org_data_scope(f.organization_id,'legal_entity',f.legal_entity_id) and public.has_org_data_scope(f.organization_id,'branch',f.branch_id) and public.has_org_data_scope(f.organization_id,'department',f.department_id) and public.has_org_data_scope(f.organization_id,'cost_center',f.cost_center_id) and public.has_org_data_scope(f.organization_id,'region',f.region_id) and public.has_org_data_scope(f.organization_id,'product',f.product_id) and public.has_org_data_scope(f.organization_id,'project',f.project_id) and (p_branch_id is null or f.branch_id=p_branch_id) and (p_department_id is null or f.department_id=p_department_id) and (p_cost_center_id is null or f.cost_center_id=p_cost_center_id) and (p_region_id is null or f.region_id=p_region_id) and (p_product_id is null or f.product_id=p_product_id) and (p_project_id is null or f.project_id=p_project_id) and (p_account_id is null or f.account_id=p_account_id)), agg as (select code,name,equity_rollforward_role,coalesce(sum(debit_minor-credit_minor) filter(where period_end<fy),0)::bigint opening,coalesce(sum(debit_minor-credit_minor) filter(where period_end<=p.period_end),0)::bigint closing from scoped group by code,name,equity_rollforward_role) select coalesce(jsonb_agg(jsonb_build_object('code',code,'name',name,'role',equity_rollforward_role,'opening',opening,'movement',case when equity_rollforward_role='current_year_profit' then profit else closing-opening end,'closing',closing) order by code),'[]'::jsonb) into rows from agg;
 recon:=closing_total-opening_total-(contribution+distribution+retained+profit+oci);
 return jsonb_build_object('rows',rows,'opening_equity',opening_total,'capital_contributions',contribution,'owner_distributions',distribution,'retained_earnings_movement',retained,'net_income',profit,'other_comprehensive_income',oci,'total_comprehensive_income',profit+oci,'closing_equity',closing_total,'rollforward_difference',recon,'unclassified_equity_movement',recon);
end; $$;
revoke all on function public.get_equity_rollforward(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid) from public,anon;
grant execute on function public.get_equity_rollforward(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid) to authenticated;

create or replace function public.get_financial_statements_v2(p_organization_id uuid,p_period_id uuid,p_branch_id uuid default null,p_department_id uuid default null,p_cost_center_id uuid default null,p_region_id uuid default null,p_product_id uuid default null,p_project_id uuid default null,p_account_id uuid default null,p_cash_flow_method text default 'indirect')
returns jsonb language plpgsql security definer set search_path='' as $$
declare r jsonb; p record; fy date; opening bigint; closing bigint; cf jsonb; net bigint; recon bigint; eq jsonb;
begin
 r:=public.get_financial_statements(p_organization_id,p_period_id,p_branch_id,p_department_id,p_cost_center_id,p_region_id,p_product_id,p_project_id,p_account_id,p_cash_flow_method);
 select fp.period_start,fp.period_end,o.fiscal_year_start_month into p from public.financial_periods fp join public.organizations o on o.id=fp.organization_id where fp.id=p_period_id and fp.organization_id=p_organization_id;
 fy:=make_date(extract(year from p.period_start)::integer-case when extract(month from p.period_start)::integer<greatest(1,least(12,p.fiscal_year_start_month)) then 1 else 0 end,greatest(1,least(12,p.fiscal_year_start_month)),1);
 select coalesce(sum(case when fp.period_end<fy then f.debit_minor-f.credit_minor else 0 end),0)::bigint,coalesce(sum(case when fp.period_end<=p.period_end then f.debit_minor-f.credit_minor else 0 end),0)::bigint into opening,closing from public.financial_facts f join public.financial_periods fp on fp.id=f.financial_period_id where f.organization_id=p_organization_id and f.fact_type='actual' and f.status='published' and f.account_id in (select id from public.accounts where organization_id=p_organization_id and cash_flow_role='cash') and public.has_org_data_scope(f.organization_id,'legal_entity',f.legal_entity_id) and public.has_org_data_scope(f.organization_id,'branch',f.branch_id) and public.has_org_data_scope(f.organization_id,'department',f.department_id) and public.has_org_data_scope(f.organization_id,'cost_center',f.cost_center_id) and public.has_org_data_scope(f.organization_id,'region',f.region_id) and public.has_org_data_scope(f.organization_id,'product',f.product_id) and public.has_org_data_scope(f.organization_id,'project',f.project_id) and (p_branch_id is null or f.branch_id=p_branch_id) and (p_department_id is null or f.department_id=p_department_id) and (p_cost_center_id is null or f.cost_center_id=p_cost_center_id) and (p_region_id is null or f.region_id=p_region_id) and (p_product_id is null or f.product_id=p_product_id) and (p_project_id is null or f.project_id=p_project_id) and (p_account_id is null or f.account_id=p_account_id);
 cf:=r->'cash_flow'; cf:=jsonb_set(cf,'{opening_cash}',to_jsonb(opening),true); cf:=jsonb_set(cf,'{closing_cash}',to_jsonb(closing),true); cf:=jsonb_set(cf,'{net_change}',to_jsonb(closing-opening),true); net:=coalesce((cf->'operating'->>'net_operating_cash_flow')::bigint,0)+coalesce((cf->'investing'->>'net_cash_flow')::bigint,0)+coalesce((cf->'financing'->>'net_cash_flow')::bigint,0); recon:=closing-opening-net; cf:=jsonb_set(cf,'{reconciliation_difference}',to_jsonb(recon),true); r:=jsonb_set(r,'{cash_flow}',cf,true); r:=jsonb_set(r,'{validation,cash_flow_reconciliation_difference}',to_jsonb(recon),true);
 eq:=public.get_equity_rollforward(p_organization_id,p_period_id,p_branch_id,p_department_id,p_cost_center_id,p_region_id,p_product_id,p_project_id,p_account_id); r:=jsonb_set(r,'{equity_statement}',eq,true); r:=jsonb_set(r,'{validation,equity_rollforward_difference}',coalesce(eq->'rollforward_difference','0'::jsonb),true);
 return r;
end; $$;
revoke all on function public.get_financial_statements_v2(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text) from public,anon;
grant execute on function public.get_financial_statements_v2(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text) to authenticated;