-- Enrich the date-range statement account tree from the real account hierarchy.
-- The core statement function exposes account codes but older output rows did not carry UUIDs.
create or replace function public.get_financial_statements_date_range_filtered(p_organization_id uuid,p_start_date date,p_end_date date,p_journal_no text default null,p_cash_flow_method text default 'indirect',p_branch_id uuid default null,p_department_id uuid default null,p_cost_center_id uuid default null,p_region_id uuid default null,p_product_id uuid default null,p_project_id uuid default null,p_account_id uuid default null) returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_result jsonb; v_context jsonb; v_accounts jsonb;
begin
 v_result:=public.get_financial_statements_date_range_filtered_core(p_organization_id,p_start_date,p_end_date,p_journal_no,p_cash_flow_method,p_branch_id,p_department_id,p_cost_center_id,p_region_id,p_product_id,p_project_id,p_account_id);
 with recursive source_rows as (select x.value as row,a.id,a.parent_account_id,a.code from jsonb_array_elements(coalesce(v_result->'balance_sheet'->'accounts','[]'::jsonb)) x join public.accounts a on a.organization_id=p_organization_id and a.code=x.value->>'code'), tree as (select s.*,0::int depth,array[lpad(s.code,20,'0')]::text[] hierarchy_sort from source_rows s where s.parent_account_id is null union all select c.*,t.depth+1,t.hierarchy_sort||lpad(c.code,20,'0') from tree t join source_rows c on c.parent_account_id=t.id), shaped as (select t.*,exists(select 1 from source_rows c where c.parent_account_id=t.id) has_children from tree t) select coalesce(jsonb_agg(s.row || jsonb_build_object('id',s.id::text,'parent_account_id',s.parent_account_id::text,'depth',s.depth,'has_children',s.has_children) order by s.hierarchy_sort),'[]'::jsonb) into v_accounts from shaped s;
 v_result:=jsonb_set(v_result,'{balance_sheet,accounts}',v_accounts,true); v_context:=public.get_financial_statement_reporting_context(p_organization_id); return v_result || jsonb_build_object('reporting',v_context);
end;$function$;
