-- Fixes the source account reference used when deriving accounting profit before tax.
-- The authoritative classification lives on public.accounts, not public.financial_facts.
create or replace function public.calculate_tax_zakat_engine(
  p_organization_id uuid,p_period_id uuid,p_branch_id uuid,p_department_id uuid,p_cost_center_id uuid,p_region_id uuid,p_product_id uuid,p_project_id uuid,p_regime text,p_zakat_method text,p_saudi_ownership_percent numeric,p_income_tax_rate numeric,p_zakat_rate numeric
) returns jsonb language plpgsql security definer set search_path='' as $function$
declare p record; fy date; v_regime text:=lower(coalesce(p_regime,'zakat')); v_method text:=lower(coalesce(p_zakat_method,'indirect')); v_ownership numeric:=greatest(0,least(100,coalesce(p_saudi_ownership_percent,100))); pbt bigint:=0; map_tax_add bigint:=0; map_tax_ded bigint:=0; manual_tax_add bigint:=0; manual_tax_ded bigint:=0; taxable_profit bigint:=0; income_tax bigint:=0; zak_profit_add bigint:=0; zak_profit_ded bigint:=0; adjusted_profit bigint:=0; direct_zakat_assets bigint:=0; direct_deductible_liabilities bigint:=0; direct_base bigint:=0; internal_sources bigint:=0; external_financing bigint:=0; non_zakatable_assets bigint:=0; indirect_base bigint:=0; zakat bigint:=0; direct_indirect_diff bigint:=0; missing_income integer:=0; missing_balance integer:=0; warnings jsonb:='[]'::jsonb; calc_status text:='draft';
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if not (public.has_org_permission(p_organization_id,'screen.financial_statements.view') or public.has_org_permission(p_organization_id,'statements.view') or public.has_org_permission(p_organization_id,'view')) then raise exception 'Financial statements view permission required'; end if;
 if v_regime not in ('zakat','income_tax','mixed','none') then raise exception 'Invalid tax regime'; end if;
 if v_method not in ('direct','indirect') then raise exception 'Invalid zakat method'; end if;
 select fp.period_start,fp.period_end,o.fiscal_year_start_month into p from public.financial_periods fp join public.organizations o on o.id=fp.organization_id where fp.id=p_period_id and fp.organization_id=p_organization_id;
 if p.period_start is null then raise exception 'Financial period not found'; end if;
 fy:=make_date(extract(year from p.period_start)::integer-case when extract(month from p.period_start)::integer<greatest(1,least(12,p.fiscal_year_start_month)) then 1 else 0 end,greatest(1,least(12,p.fiscal_year_start_month)),1);
 with f as materialized (select ff.account_id,ff.debit_minor,ff.credit_minor,fp.period_start,fp.period_end,a.account_type,a.statement_subclassification,m.zakat_treatment,m.income_tax_treatment,m.approved from public.financial_facts ff join public.financial_periods fp on fp.id=ff.financial_period_id and fp.organization_id=p_organization_id join public.accounts a on a.id=ff.account_id and a.organization_id=p_organization_id left join public.tax_zakat_account_mappings m on m.organization_id=p_organization_id and m.account_id=a.id where ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published' and fp.period_end<=p.period_end and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id) and (p_branch_id is null or ff.branch_id=p_branch_id) and (p_department_id is null or ff.department_id=p_department_id) and (p_cost_center_id is null or ff.cost_center_id=p_cost_center_id) and (p_region_id is null or ff.region_id=p_region_id) and (p_product_id is null or ff.product_id=p_product_id) and (p_project_id is null or ff.project_id=p_project_id)), income_accounts as (select distinct account_id from f where statement_subclassification in ('revenue','cogs','operating_expense','other_income','depreciation_amortization','finance_cost','tax','other_expense') and period_start>=fy), bs_accounts as (select distinct account_id from f where statement_subclassification in ('asset','liability','equity')) select (select count(*) from income_accounts ia left join public.tax_zakat_account_mappings mm on mm.organization_id=p_organization_id and mm.account_id=ia.account_id where mm.account_id is null or not mm.approved or mm.income_tax_treatment='needs_review'),(select count(*) from bs_accounts ba left join public.tax_zakat_account_mappings mm on mm.organization_id=p_organization_id and mm.account_id=ba.account_id where mm.account_id is null or not mm.approved or mm.zakat_treatment='needs_review') into missing_income,missing_balance;
 with f as (select ff.debit_minor,ff.credit_minor,m.income_tax_treatment from public.financial_facts ff join public.financial_periods fp on fp.id=ff.financial_period_id join public.accounts a on a.id=ff.account_id left join public.tax_zakat_account_mappings m on m.organization_id=p_organization_id and m.account_id=a.id where ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published' and fp.period_start>=fy and fp.period_end<=p.period_end and a.organization_id=p_organization_id and m.approved and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id) and (p_branch_id is null or ff.branch_id=p_branch_id) and (p_department_id is null or ff.department_id=p_department_id) and (p_cost_center_id is null or ff.cost_center_id=p_cost_center_id) and (p_region_id is null or ff.region_id=p_region_id) and (p_product_id is null or ff.product_id=p_product_id) and (p_project_id is null or ff.project_id=p_project_id)) select coalesce(sum(case when income_tax_treatment='non_deductible_expense' then debit_minor-credit_minor else 0 end),0),coalesce(sum(case when income_tax_treatment='exempt_income' then credit_minor-debit_minor else 0 end),0) into map_tax_add,map_tax_ded from f;
 select coalesce(sum(case when adjustment_type='income_tax_addition' and approved then amount_minor else 0 end),0),coalesce(sum(case when adjustment_type in ('income_tax_deduction','tax_loss_carryforward') and approved then amount_minor else 0 end),0) into manual_tax_add,manual_tax_ded from public.tax_zakat_adjustments where organization_id=p_organization_id and period_id=p_period_id;
 select coalesce(sum(case when a.statement_subclassification in ('revenue','other_income') then ff.credit_minor-ff.debit_minor when a.statement_subclassification in ('cogs','operating_expense','depreciation_amortization','finance_cost','tax','other_expense') then ff.debit_minor-ff.credit_minor else 0 end),0)::bigint into pbt from public.financial_facts ff join public.financial_periods fp on fp.id=ff.financial_period_id join public.accounts a on a.id=ff.account_id where ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published' and fp.period_start>=fy and fp.period_end<=p.period_end and a.organization_id=p_organization_id and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id) and (p_branch_id is null or ff.branch_id=p_branch_id) and (p_department_id is null or ff.department_id=p_department_id) and (p_cost_center_id is null or ff.cost_center_id=p_cost_center_id) and (p_region_id is null or ff.region_id=p_region_id) and (p_product_id is null or ff.product_id=p_product_id) and (p_project_id is null or ff.project_id=p_project_id);
 taxable_profit:=greatest(pbt+map_tax_add+manual_tax_add-map_tax_ded-manual_tax_ded,0); income_tax:=round(taxable_profit*(100-v_ownership)/100.0*coalesce(p_income_tax_rate,20)/100.0)::bigint;
 select coalesce(sum(case when adjustment_type in ('zakat_profit_addition','zakat_other_addition') and approved then amount_minor else 0 end),0),coalesce(sum(case when adjustment_type in ('zakat_profit_deduction','zakat_other_deduction') and approved then amount_minor else 0 end),0) into zak_profit_add,zak_profit_ded from public.tax_zakat_adjustments where organization_id=p_organization_id and period_id=p_period_id;
 adjusted_profit:=greatest(pbt+zak_profit_add-zak_profit_ded,0);
 with balances as (select a.id,a.statement_subclassification,m.zakat_treatment,coalesce(sum(ff.debit_minor-ff.credit_minor),0)::bigint balance from public.accounts a join public.tax_zakat_account_mappings m on m.organization_id=p_organization_id and m.account_id=a.id and m.approved join public.financial_facts ff on ff.account_id=a.id and ff.organization_id=p_organization_id and ff.fact_type='actual' and ff.status='published' join public.financial_periods fp on fp.id=ff.financial_period_id and fp.period_end<=p.period_end where a.organization_id=p_organization_id and a.statement_subclassification in ('asset','liability','equity') and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id) and (p_branch_id is null or ff.branch_id=p_branch_id) and (p_department_id is null or ff.department_id=p_department_id) and (p_cost_center_id is null or ff.cost_center_id=p_cost_center_id) and (p_region_id is null or ff.region_id=p_region_id) and (p_product_id is null or ff.product_id=p_product_id) and (p_project_id is null or ff.project_id=p_project_id) group by a.id,a.statement_subclassification,m.zakat_treatment) select coalesce(sum(case when zakat_treatment in ('zakatable_asset','zakatable_investment') and statement_subclassification='asset' then balance else 0 end),0),coalesce(sum(case when zakat_treatment='deductible_liability' and statement_subclassification='liability' then -balance else 0 end),0),coalesce(sum(case when zakat_treatment='internal_source' then -balance else 0 end),0),coalesce(sum(case when zakat_treatment='non_zakatable_asset' and statement_subclassification='asset' then balance else 0 end),0) into direct_zakat_assets,direct_deductible_liabilities,internal_sources,non_zakatable_assets from balances;
 select coalesce(sum(case when adjustment_type='zakat_external_financing' and approved then amount_minor else 0 end),0)::bigint into external_financing from public.tax_zakat_adjustments where organization_id=p_organization_id and period_id=p_period_id;
 direct_base:=greatest(direct_zakat_assets-direct_deductible_liabilities,0); indirect_base:=greatest(internal_sources+adjusted_profit+external_financing-non_zakatable_assets,0); direct_indirect_diff:=direct_base-indirect_base; zakat:=round((case when v_method='direct' then direct_base else indirect_base end)*coalesce(p_zakat_rate,2.5)/100.0)::bigint;
 if missing_income>0 and v_regime in ('income_tax','mixed') then warnings:=warnings || jsonb_build_array('توجد حسابات دخل غير معتمدة في خريطة ضريبة الدخل: '||missing_income); end if;
 if missing_balance>0 and v_regime in ('zakat','mixed') then warnings:=warnings || jsonb_build_array('توجد حسابات قائمة مركز مالي غير معتمدة في الخريطة الزكوية: '||missing_balance); end if;
 if v_regime in ('zakat','mixed') and missing_balance=0 and direct_indirect_diff<>0 then warnings:=warnings || jsonb_build_array('الطريقة المباشرة وغير المباشرة للزكاة غير متطابقتين بمقدار '||direct_indirect_diff); end if;
 if (missing_income=0 or v_regime not in ('income_tax','mixed')) and (missing_balance=0 or v_regime not in ('zakat','mixed')) and (v_regime not in ('zakat','mixed') or direct_indirect_diff=0) then calc_status:='ready_for_review'; else calc_status:='needs_review'; end if;
 return jsonb_build_object('engine_version','1.2','status',calc_status,'period',jsonb_build_object('id',p_period_id,'start',p.period_start,'end',p.period_end,'fiscal_year_start',fy),'profile',jsonb_build_object('regime',v_regime,'zakat_method',v_method,'saudi_ownership_percent',v_ownership,'income_tax_rate',coalesce(p_income_tax_rate,20),'zakat_rate',coalesce(p_zakat_rate,2.5)),'income_tax',jsonb_build_object('accounting_profit_before_tax',pbt,'mapping_additions',map_tax_add,'manual_additions',manual_tax_add,'mapping_deductions',map_tax_ded,'manual_deductions',manual_tax_ded,'taxable_profit',taxable_profit,'non_saudi_taxable_share',round(taxable_profit*(100-v_ownership)/100.0)::bigint,'current_income_tax',case when v_regime in ('income_tax','mixed') then income_tax else 0 end),'zakat',jsonb_build_object('adjusted_profit',adjusted_profit,'direct',jsonb_build_object('zakatable_assets',direct_zakat_assets,'deductible_liabilities',direct_deductible_liabilities,'base',direct_base),'indirect',jsonb_build_object('internal_sources',internal_sources,'adjusted_profit',adjusted_profit,'external_financing',external_financing,'non_zakatable_assets',non_zakatable_assets,'base',indirect_base),'selected_method_base',case when v_method='direct' then direct_base else indirect_base end,'current_zakat',case when v_regime in ('zakat','mixed') then zakat else 0 end,'direct_indirect_difference',direct_indirect_diff),'completeness',jsonb_build_object('missing_income_tax_mappings',missing_income,'missing_zakat_mappings',missing_balance,'ready',calc_status='ready_for_review'),'warnings',warnings,'disclaimer','محرك حساب ومراجعة وليس إقرارًا نهائيًا. لا يتم إنشاء قيد محاسبي تلقائيًا. يجب اعتماد خريطة الحسابات والتعديلات ومراجعة المعالجة النظامية قبل التقديم لدى ZATCA.');
end;$function$;
revoke all on function public.calculate_tax_zakat_engine(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,text,numeric,numeric,numeric) from public,anon; grant execute on function public.calculate_tax_zakat_engine(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,text,numeric,numeric,numeric) to authenticated;
