create or replace function public.get_group_trial_balance(p_root_organization_id uuid, p_period_start date, p_period_end date)
returns jsonb
language plpgsql stable security definer set search_path=''
as $$
declare v_uid uuid := (select auth.uid()); v_orgs jsonb; v_rows jsonb; v_unmapped jsonb;
begin
 if v_uid is null then raise exception 'UNAUTHENTICATED'; end if;
 if p_period_start is null or p_period_end is null or p_period_start>p_period_end then raise exception 'INVALID_PERIOD_RANGE'; end if;
 if not public.has_org_permission(p_root_organization_id,'group.view') then raise exception 'FORBIDDEN'; end if;
 v_orgs:=public.get_group_organizations(p_root_organization_id);
 with recursive tree as (select o.id,o.base_currency from public.organizations o where o.id=p_root_organization_id union all select c.id,c.base_currency from public.organizations c join tree t on c.parent_organization_id=t.id), scoped as (select ff.organization_id,ff.account_id,t.base_currency as currency,coalesce(ff.debit_minor,case when ff.amount_minor>0 then ff.amount_minor else 0 end) debit_minor,coalesce(ff.credit_minor,case when ff.amount_minor<0 then -ff.amount_minor else 0 end) credit_minor from public.financial_facts ff join tree t on t.id=ff.organization_id join public.financial_periods fp on fp.id=ff.financial_period_id and fp.organization_id=ff.organization_id where ff.fact_type='actual' and fp.period_start>=p_period_start and fp.period_end<=p_period_end and public.has_org_data_scope(ff.organization_id,'legal_entity',ff.legal_entity_id) and public.has_org_data_scope(ff.organization_id,'branch',ff.branch_id) and public.has_org_data_scope(ff.organization_id,'department',ff.department_id) and public.has_org_data_scope(ff.organization_id,'cost_center',ff.cost_center_id) and public.has_org_data_scope(ff.organization_id,'region',ff.region_id) and public.has_org_data_scope(ff.organization_id,'product',ff.product_id) and public.has_org_data_scope(ff.organization_id,'project',ff.project_id)), mapped as (select s.organization_id,s.account_id,s.currency,s.debit_minor,s.credit_minor,g.id group_id,g.code group_code,g.name group_name from scoped s join public.group_account_mappings m on m.root_organization_id=p_root_organization_id and m.organization_id=s.organization_id and m.account_id=s.account_id join public.group_reporting_accounts g on g.id=m.group_reporting_account_id and g.root_organization_id=p_root_organization_id and g.is_active), unmapped as (select s.*,a.code,a.name,o.name organization_name from scoped s join public.accounts a on a.id=s.account_id and a.organization_id=s.organization_id join public.organizations o on o.id=s.organization_id where not exists(select 1 from public.group_account_mappings m where m.root_organization_id=p_root_organization_id and m.organization_id=s.organization_id and m.account_id=s.account_id)), grouped_rows as (select group_id,group_code,group_name,currency,sum(debit_minor)::bigint period_debit,sum(credit_minor)::bigint period_credit,(sum(debit_minor)-sum(credit_minor))::bigint period_net from mapped group by group_id,group_code,group_name,currency), unmapped_rows as (select organization_id,organization_name,code,name,currency,sum(debit_minor)::bigint period_debit,sum(credit_minor)::bigint period_credit,(sum(debit_minor)-sum(credit_minor))::bigint period_net from unmapped group by organization_id,organization_name,code,name,currency) select coalesce((select jsonb_agg(to_jsonb(grouped_rows) order by currency,group_code) from grouped_rows),'[]'::jsonb),coalesce((select jsonb_agg(to_jsonb(unmapped_rows) order by organization_name,code) from unmapped_rows),'[]'::jsonb) into v_rows,v_unmapped;
 return jsonb_build_object('root_organization_id',p_root_organization_id,'period_start',p_period_start,'period_end',p_period_end,'organizations',v_orgs,'rows',v_rows,'unmapped_rows',v_unmapped);
end $$;
revoke all on function public.get_group_trial_balance(uuid,date,date) from public,anon;
grant execute on function public.get_group_trial_balance(uuid,date,date) to authenticated;
