-- Company group hierarchy: parent companies own subsidiary organizations.
alter table public.organizations add column if not exists parent_organization_id uuid null references public.organizations(id) on delete restrict;
create index if not exists idx_organizations_parent on public.organizations(parent_organization_id);

create or replace function public.prevent_organization_hierarchy_cycle()
returns trigger language plpgsql security invoker set search_path=''
as $$
begin
  if new.parent_organization_id is null then return new; end if;
  if new.parent_organization_id = new.id then raise exception 'An organization cannot be its own parent'; end if;
  if exists(with recursive ancestors(id) as (select new.parent_organization_id union all select o.parent_organization_id from public.organizations o join ancestors a on o.id=a.id where o.parent_organization_id is not null) select 1 from ancestors where id=new.id) then raise exception 'Organization hierarchy cycle is not allowed'; end if;
  return new;
end; $$;
drop trigger if exists trg_prevent_organization_hierarchy_cycle on public.organizations;
create trigger trg_prevent_organization_hierarchy_cycle before insert or update of parent_organization_id on public.organizations for each row execute function public.prevent_organization_hierarchy_cycle();

create or replace function public.create_child_company(p_parent_organization_id uuid,p_name text,p_base_currency text default 'SAR',p_fiscal_year_start_month smallint default 1,p_company_profile jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path=''
as $$
declare v_user uuid:=auth.uid(); v_id uuid; v_slug text; v_name text:=coalesce(nullif(trim(p_name),''),'شركة تابعة جديدة'); v_currency text:=upper(coalesce(nullif(trim(p_base_currency),''),'SAR')); v_month smallint:=coalesce(p_fiscal_year_start_month,1);
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if p_parent_organization_id is null or not public.has_org_permission(p_parent_organization_id,'manage_settings') then raise exception 'Parent company management permission required'; end if;
 if not exists(select 1 from public.organizations where id=p_parent_organization_id) then raise exception 'Parent company not found'; end if;
 if length(v_name)<2 or length(v_name)>120 then raise exception 'Company name must contain 2 to 120 characters'; end if;
 if v_currency !~ '^[A-Z]{3}$' then raise exception 'Base currency must be a three-letter ISO code'; end if;
 if v_month<1 or v_month>12 then raise exception 'Fiscal year start month must be between 1 and 12'; end if;
 v_slug:=regexp_replace(lower(v_name),'[^[:alnum:]]+','-','g'); v_slug:=trim(both '-' from v_slug); if v_slug='' then v_slug:='company'; end if; v_slug:=left(v_slug,70)||'-'||left(replace(gen_random_uuid()::text,'-',''),8);
 insert into public.organizations(name,slug,base_currency,fiscal_year_start_month,parent_organization_id,legal_name,country,city,address,industry,company_size,tax_id,registration_number,website,contact_email,contact_phone,initial_data_source) values(v_name,v_slug,v_currency,v_month,p_parent_organization_id,nullif(trim(p_company_profile->>'legal_name'),''),nullif(trim(p_company_profile->>'country'),''),nullif(trim(p_company_profile->>'city'),''),nullif(trim(p_company_profile->>'address'),''),nullif(trim(p_company_profile->>'industry'),''),nullif(trim(p_company_profile->>'company_size'),''),nullif(trim(p_company_profile->>'tax_id'),''),nullif(trim(p_company_profile->>'registration_number'),''),nullif(trim(p_company_profile->>'website'),''),nullif(trim(p_company_profile->>'contact_email'),''),nullif(trim(p_company_profile->>'contact_phone'),''),nullif(trim(p_company_profile->>'initial_data_source'),'')) returning id into v_id;
 insert into public.organization_members(organization_id,user_id,role,role_key) values(v_id,v_user,'admin','company_admin');
 insert into public.organization_roles(organization_id,role_key,name,description) select v_id,r.role_key,r.name,r.description from (values ('company_admin','مسؤول الشركة','إدارة الشركة والمستخدمين والإعدادات'),('ceo','الرئيس التنفيذي','الرؤية التنفيذية والقرارات'),('cfo','المدير المالي','التخطيط المالي والمراجعة والتقارير'),('finance_manager','مدير مالي','التخطيط والتوقعات والتحليل'),('fpa_analyst','محلل FP&A','النماذج والتوقعات والتحليل'),('accountant','محاسب','البيانات الفعلية والاستيراد والمطابقات'),('viewer','مطلع','عرض البيانات المسموح بها'),('board','مجلس الإدارة','الاعتماد والاطلاع التنفيذي')) r(role_key,name,description) on conflict(organization_id,role_key) do nothing;
 insert into public.organization_role_permissions(organization_id,role_key,permission_key) select v_id,rp.role_key,rp.permission_key from (values ('company_admin','view'),('company_admin','create'),('company_admin','edit'),('company_admin','delete'),('company_admin','import'),('company_admin','export'),('company_admin','submit'),('company_admin','approve'),('company_admin','reject'),('company_admin','lock'),('company_admin','manage_users'),('company_admin','manage_settings'),('company_admin','manage_budget'),('company_admin','manage_forecast'),('company_admin','manage_scenarios'),('company_admin','access_ai'),('ceo','view'),('ceo','export'),('ceo','approve'),('ceo','access_ai'),('cfo','view'),('cfo','create'),('cfo','edit'),('cfo','export'),('cfo','submit'),('cfo','approve'),('cfo','reject'),('cfo','lock'),('cfo','manage_budget'),('cfo','manage_forecast'),('cfo','manage_scenarios'),('cfo','access_ai'),('finance_manager','view'),('finance_manager','create'),('finance_manager','edit'),('finance_manager','export'),('finance_manager','submit'),('finance_manager','manage_budget'),('finance_manager','manage_forecast'),('finance_manager','manage_scenarios'),('finance_manager','access_ai'),('fpa_analyst','view'),('fpa_analyst','create'),('fpa_analyst','edit'),('fpa_analyst','export'),('fpa_analyst','submit'),('fpa_analyst','manage_budget'),('fpa_analyst','manage_forecast'),('fpa_analyst','manage_scenarios'),('fpa_analyst','access_ai'),('accountant','view'),('accountant','create'),('accountant','import'),('accountant','export'),('accountant','submit'),('viewer','view'),('board','view'),('board','export'),('board','approve'),('board','access_ai')) rp(role_key,permission_key) where exists(select 1 from public.organization_permissions p where p.permission_key=rp.permission_key) on conflict do nothing;
 return v_id;
end; $$;
revoke all on function public.create_child_company(uuid,text,text,smallint,jsonb) from public,anon;
grant execute on function public.create_child_company(uuid,text,text,smallint,jsonb) to authenticated;

create or replace function public.get_my_organizations() returns jsonb language plpgsql stable security definer set search_path='' as $$ declare v_user uuid:=auth.uid(); v_result jsonb; begin if v_user is null then raise exception 'Authentication required'; end if; select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'name',o.name,'legal_name',o.legal_name,'base_currency',o.base_currency,'country',o.country,'industry',o.industry,'role',om.role_key,'parent_organization_id',o.parent_organization_id,'children_count',(select count(*) from public.organizations c where c.parent_organization_id=o.id)) order by o.created_at desc),'[]'::jsonb) into v_result from public.organization_members om join public.organizations o on o.id=om.organization_id where om.user_id=v_user; return v_result; end; $$;
revoke all on function public.get_my_organizations() from public,anon; grant execute on function public.get_my_organizations() to authenticated;

drop function if exists public.get_my_workspaces();
create function public.get_my_workspaces() returns table(id uuid,name text,legal_name text,industry text,city text,base_currency text,role text,role_key text,parent_organization_id uuid,children_count bigint) language sql stable security definer set search_path='' as $$ select o.id,o.name,o.legal_name,o.industry,o.city,o.base_currency,coalesce(om.role,'viewer'),coalesce(om.role_key,case om.role when 'admin' then 'company_admin' when 'planner' then 'fpa_analyst' when 'owner' then 'company_admin' else 'viewer' end),o.parent_organization_id,(select count(*) from public.organizations c where c.parent_organization_id=o.id) from public.organization_members om join public.organizations o on o.id=om.organization_id where om.user_id=auth.uid() order by o.created_at desc $$;
revoke all on function public.get_my_workspaces() from public,anon; grant execute on function public.get_my_workspaces() to authenticated;

create or replace function public.get_organization_context(p_organization_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare v_user uuid:=auth.uid(); v_result jsonb; begin if v_user is null then raise exception 'Authentication required'; end if; if p_organization_id is null or not public.has_org_permission(p_organization_id,'view') then raise exception 'Not authorized'; end if; select jsonb_build_object('organization',jsonb_build_object('id',o.id,'name',o.name,'legal_name',o.legal_name,'base_currency',o.base_currency,'country',o.country,'industry',o.industry,'company_size',o.company_size,'parent_organization_id',o.parent_organization_id),'role',om.role_key,'parent',case when o.parent_organization_id is null then null else jsonb_build_object('id',o.parent_organization_id,'name',po.name) end,'children',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'legal_name',c.legal_name,'base_currency',c.base_currency,'country',c.country) order by c.name) from public.organizations c where c.parent_organization_id=o.id),'[]'::jsonb),'legal_entities',coalesce((select jsonb_agg(jsonb_build_object('id',le.id,'name',le.name,'code',le.code,'currency',le.currency) order by le.name) from public.legal_entities le where le.organization_id=o.id),'[]'::jsonb)) into v_result from public.organizations o join public.organization_members om on om.organization_id=o.id and om.user_id=v_user left join public.organizations po on po.id=o.parent_organization_id where o.id=p_organization_id; if v_result is null then raise exception 'Organization not found'; end if; return v_result; end; $$;
revoke all on function public.get_organization_context(uuid) from public,anon; grant execute on function public.get_organization_context(uuid) to authenticated;