"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Account = { id:string; code:string; name:string; account_type:string|null; statement_subclassification:string|null; zakat_treatment:string|null; income_tax_treatment:string|null; notes:string|null; approved:boolean; approved_at:string|null };
const supabase=getSupabaseBrowserClient();
const zakat=[['zakatable_asset','أصل زكوي'],['zakatable_investment','استثمار زكوي'],['non_zakatable_asset','أصل غير زكوي'],['deductible_liability','التزام قابل للخصم'],['internal_source','مصدر تمويل داخلي'],['conditional','مشروط / يحتاج مراجعة'],['needs_review','يحتاج مراجعة'],['not_applicable','لا ينطبق']];
const tax=[['deductible_expense','مصروف قابل للخصم'],['non_deductible_expense','مصروف غير قابل للخصم'],['taxable_income','دخل خاضع للضريبة'],['exempt_income','دخل معفى'],['deferred','فروق ضريبية مؤجلة'],['needs_review','يحتاج مراجعة'],['not_applicable','لا ينطبق']];
export default function TaxZakatPage(){
 const [org,setOrg]=useState(''); const [rows,setRows]=useState<Account[]>([]); const [profile,setProfile]=useState<any>(null); const [q,setQ]=useState(''); const [onlyMissing,setOnlyMissing]=useState(false); const [saving,setSaving]=useState<string|null>(null); const [msg,setMsg]=useState('');
 async function load(){ const id=window.sessionStorage.getItem('activeOrganizationId')||''; setOrg(id); if(!id)return; const {data,error}=await supabase.rpc('get_tax_zakat_mapping_workbench',{p_organization_id:id}); if(error){setMsg(error.message);return;} setRows((data?.accounts||[]) as Account[]); setProfile(data?.profile||null); }
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(!q||`${r.code} ${r.name}`.toLowerCase().includes(q.toLowerCase()))&&(!onlyMissing||(r.zakat_treatment==null||r.income_tax_treatment==null||!r.approved))),[rows,q,onlyMissing]);
 async function save(r:Account,zk:string,taxv:string){setSaving(r.id);setMsg(''); const {error}=await supabase.rpc('set_tax_zakat_account_mapping',{p_organization_id:org,p_account_id:r.id,p_zakat_treatment:zk,p_income_tax_treatment:taxv,p_notes:r.notes||null,p_approved:Boolean(zk&&taxv&&zk!=='needs_review'&&taxv!=='needs_review')}); if(error){setMsg(error.message)}else{setRows(v=>v.map(x=>x.id===r.id?{...x,zakat_treatment:zk||null,income_tax_treatment:taxv||null,approved:Boolean(zk&&taxv&&zk!=='needs_review'&&taxv!=='needs_review'),approved_at:new Date().toISOString()}:x));setMsg('تم حفظ المعالجة واعتمادها');}setSaving(null)}
 const stats={total:rows.length,approved:rows.filter(x=>x.approved).length,missing:rows.filter(x=>!x.approved).length};
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px]">
  <div className="mb-6 flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold tracking-[.16em] text-slate-400">TAX & ZAKAT ENGINE</p><h1 className="mt-2 text-2xl font-bold text-slate-950">خريطة الزكاة وضريبة الدخل</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">لا يبدأ المحرك بالحساب قبل تحديد المعالجة النظامية لكل حساب واعتمادها. هذه الشاشة هي طبقة الربط بين الأرصدة المحاسبية والوعاء الزكوي والربح الخاضع للضريبة.</p></div><div className="grid grid-cols-3 border border-slate-200 bg-white"><div className="p-3 text-center"><b className="block text-lg">{stats.total}</b><span className="text-[10px] text-slate-500">الحسابات</span></div><div className="border-x border-slate-200 p-3 text-center"><b className="block text-lg">{stats.approved}</b><span className="text-[10px] text-slate-500">معتمدة</span></div><div className="p-3 text-center"><b className="block text-lg text-amber-600">{stats.missing}</b><span className="text-[10px] text-slate-500">تحتاج مراجعة</span></div></div></div>
  <div className="mb-5 grid gap-3 md:grid-cols-4">{[['النظام',profile?.regime],['الملكية السعودية',`${profile?.saudi_ownership_percent??100}%`],['نسبة الزكاة',`${profile?.zakat_rate??2.5}%`],['ضريبة الدخل',`${profile?.income_tax_rate??20}%`]].map(([a,b])=><div key={String(a)} className="border border-slate-200 bg-white p-4"><p className="text-[11px] font-bold text-slate-400">{a}</p><p className="mt-2 text-sm font-bold text-slate-900">{b}</p></div>)}</div>
  <div className="mb-3 flex flex-col gap-3 border border-slate-200 bg-white p-3 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث برقم أو اسم الحساب" className="min-h-10 flex-1 border border-slate-300 px-3 text-sm"/><label className="flex items-center gap-2 px-2 text-sm"><input type="checkbox" checked={onlyMissing} onChange={e=>setOnlyMissing(e.target.checked)}/> عرض غير المكتمل فقط</label></div>
  {msg&&<div className="mb-3 border border-slate-200 bg-white p-3 text-sm font-semibold text-slate-700">{msg}</div>}
  <div className="overflow-x-auto border border-slate-200 bg-white"><table className="w-full min-w-[1250px] text-right text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-3">الحساب</th><th className="px-3 py-3">التصنيف المحاسبي</th><th className="px-3 py-3">المعالجة الزكوية</th><th className="px-3 py-3">المعالجة الضريبية</th><th className="px-3 py-3">الحالة</th><th className="px-3 py-3">الإجراء</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-b border-slate-100 align-top"><td className="px-3 py-3"><b>{r.code}</b><div className="mt-1 text-xs text-slate-500">{r.name}</div></td><td className="px-3 py-3 text-xs text-slate-500">{r.statement_subclassification||r.account_type||'غير مصنف'}</td><td className="px-3 py-3"><select id={`z-${r.id}`} defaultValue={r.zakat_treatment||''} className="w-56 border border-slate-300 bg-white px-2 py-2 text-xs"><option value="">اختر</option>{zakat.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="px-3 py-3"><select id={`t-${r.id}`} defaultValue={r.income_tax_treatment||''} className="w-56 border border-slate-300 bg-white px-2 py-2 text-xs"><option value="">اختر</option>{tax.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="px-3 py-3">{r.approved?<span className="font-bold text-emerald-700">✓ معتمد</span>:<span className="font-bold text-amber-600">مراجعة مطلوبة</span>}</td><td className="px-3 py-3"><button disabled={saving===r.id} onClick={()=>{const z=(document.getElementById(`z-${r.id}`) as HTMLSelectElement).value;const t=(document.getElementById(`t-${r.id}`) as HTMLSelectElement).value;void save(r,z,t)}} className="bg-slate-950 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{saving===r.id?'جارٍ الحفظ…':'حفظ واعتماد'}</button></td></tr>)}</tbody></table></div>
  <div className="mt-5 border border-amber-200 bg-amber-50 p-4 text-xs leading-6 text-amber-900">الحساب لا يصبح صالحًا للحساب الآلي لمجرد اختيار تصنيف محاسبي. يجب أن تكون المعالجة الزكوية والضريبية معتمدة، وأي بند يحتاج حكمًا نظاميًا يظل في حالة مراجعة. نتيجة المحرك هي أداة حساب ومراجعة وليست إقرارًا مقدمًا إلى ZATCA.</div>
 </div></main>
}