"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { ReportDimensionFilters, emptyReportDimensionFilters, ReportDimensionFilterState } from "@/components/workspace/report-dimension-filters";

type Point={month:string;revenue:number;gross_profit:number;ebitda:number;net_income:number;operating_cash_flow:number};
type Forecast={ready:boolean;history_months:number;minimum_history_months:number;horizon_months:number;forecast:Point[];methodology?:{model?:string;source?:string;actuals_only?:boolean;published_only?:boolean;no_missing_as_zero?:boolean;filters_applied?:boolean}};
type Row={month:string;actual:Point;forecast:Point;variance:Point;ape:{revenue:number|null;gross_profit:number|null;ebitda:number|null;operating_cash_flow:number|null}};
type Validation={validated:boolean;backtest_months:number;minimum_backtest_months:number;metrics:{revenue_mape:number|null;gross_profit_mape:number|null;ebitda_mape:number|null;operating_cash_flow_mape:number|null;overall_mape:number|null};quality:"high"|"moderate"|"low"|"insufficient";rows?:Row[];methodology?:{model?:string;validation?:string;error_metric?:string;actuals_only?:boolean;published_only?:boolean;missing_months_excluded?:boolean;filters_applied?:boolean}};

const money=(n:number)=>new Intl.NumberFormat("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0));
const pct=(n:number|null)=>n==null?"—":`${Number(n).toFixed(2)}%`;
const metricLabels:{key:keyof Point;label:string}[]=[{key:"revenue",label:"الإيرادات"},{key:"gross_profit",label:"مجمل الربح"},{key:"ebitda",label:"EBITDA"},{key:"net_income",label:"صافي الدخل"},{key:"operating_cash_flow",label:"التدفق التشغيلي"}];

export default function ForecastPage(){
 const supabase=getSupabaseBrowserClient();
 const [orgId,setOrgId]=useState<string|null>(null);
 const [start,setStart]=useState("2026-01-01"); const [end,setEnd]=useState("2026-12-31");
 const [filters,setFilters]=useState<ReportDimensionFilterState>(emptyReportDimensionFilters);
 const [forecast,setForecast]=useState<Forecast|null>(null); const [validation,setValidation]=useState<Validation|null>(null);
 const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const [horizon,setHorizon]=useState(3);
 const load=useCallback(async(id:string)=>{
   setLoading(true);setError(null);
   const p={p_organization_id:id,p_start_date:start,p_end_date:end,p_branch_id:filters.branch||null,p_department_id:filters.department||null,p_cost_center_id:filters.costCenter||null,p_region_id:filters.region||null,p_product_id:filters.product||null,p_project_id:filters.project||null,p_account_id:filters.account||null};
   const [f,v]=await Promise.all([supabase.rpc("get_executive_dashboard_forecast",{...p,p_horizon_months:horizon}),supabase.rpc("get_executive_dashboard_forecast_validation",p)]);
   if(f.error){setError(f.error.message);setForecast(null)}else setForecast((f.data??null) as Forecast|null);
   if(v.error){setError(x=>x?x:`تعذر تحميل التحقق: ${v.error.message}`);setValidation(null)}else setValidation((v.data??null) as Validation|null);
   setLoading(false);
 },[supabase,start,end,filters,horizon]);
 useEffect(()=>{const id=window.sessionStorage.getItem("activeOrganizationId");if(!id){setError("لم يتم تحديد الشركة الحالية.");setLoading(false);return}setOrgId(id)},[]);
 useEffect(()=>{if(orgId)void load(orgId)},[orgId,load]);
 const approved=Boolean(forecast?.ready&&validation?.validated&&validation.quality!=="insufficient");
 const rows=validation?.rows??[];
 const qualityLabel=validation?.quality==="high"?"عالية":validation?.quality==="moderate"?"متوسطة":validation?.quality==="low"?"منخفضة":"غير كافية";
 const hasForecast=Boolean(forecast?.forecast?.length);
 const filterDateText=useMemo(()=>`${start} → ${end}`,[start,end]);
 return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">03 / FORECAST</p><h1 className="section-title mt-1 text-2xl sm:text-3xl">التنبؤ المالي</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">محرك مستقل للتنبؤ، التحقق التاريخي، ومقارنة التوقع بالفعلي. لا تُعامل الأشهر المفقودة كصفر.</p></div><div className="border border-slate-200 bg-slate-50 px-4 py-3 text-sm"><p className="text-[10px] font-bold text-slate-400">PERIOD</p><p className="mt-1 font-bold tabular-nums">{filterDateText}</p></div></div></div></header>
  <div className="mx-auto max-w-[1600px] space-y-5 px-4 py-6 sm:px-6 lg:px-8 lg:py-7">
   {error&&<div role="alert" className="border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
   <section className="saas-card p-5 sm:p-6"><div className="mb-5"><p className="eyebrow">CONTROL PANEL</p><h2 className="mt-1 font-extrabold">نطاق التنبؤ والفلاتر</h2></div><div className="grid gap-3 md:grid-cols-[1fr_1fr_160px_auto]"><label className="text-xs font-bold text-slate-500">من<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="input mt-1"/></label><label className="text-xs font-bold text-slate-500">إلى<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="input mt-1"/></label><label className="text-xs font-bold text-slate-500">أفق التنبؤ<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))} className="input mt-1"><option value={3}>3 أشهر</option><option value={6}>6 أشهر</option><option value={12}>12 شهرًا</option></select></label><button onClick={()=>orgId&&void load(orgId)} disabled={loading||!orgId} className="min-h-11 self-end bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{loading?"جارٍ التحميل…":"تحديث التنبؤ"}</button></div><div className="mt-5"><ReportDimensionFilters filters={filters} setFilters={setFilters} dateRange={{start,end}}/></div></section>
   <section className="grid gap-3 md:grid-cols-4"><div className="saas-card p-5"><p className="eyebrow">HISTORY</p><p className="mt-2 text-2xl font-black">{forecast?.history_months??0}</p><p className="mt-1 text-sm text-slate-500">أشهر فعلية مستخدمة</p></div><div className="saas-card p-5"><p className="eyebrow">BACKTEST</p><p className="mt-2 text-2xl font-black">{validation?.backtest_months??0}</p><p className="mt-1 text-sm text-slate-500">أشهر تحقق تاريخي</p></div><div className="saas-card p-5"><p className="eyebrow">ACCURACY</p><p className="mt-2 text-2xl font-black">{pct(validation?.metrics?.overall_mape??null)}</p><p className="mt-1 text-sm text-slate-500">MAPE الإجمالي</p></div><div className="saas-card p-5"><p className="eyebrow">QUALITY</p><p className="mt-2 text-2xl font-black">{qualityLabel}</p><p className="mt-1 text-sm text-slate-500">حالة التحقق</p></div></section>
   <section className="saas-card p-5 sm:p-6"><div className="flex flex-col gap-2 border-b border-slate-100 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">FORECAST OUTPUT</p><h2 className="mt-1 font-extrabold">التوقعات المستقبلية</h2><p className="mt-1 text-sm text-slate-500">الأرقام المستقبلية تظهر فقط بعد اجتياز متطلبات البيانات والتحقق.</p></div><span className={`border px-3 py-2 text-xs font-bold ${approved?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-amber-200 bg-amber-50 text-amber-800"}`}>{approved?"التنبؤ متاح بعد التحقق":"التنبؤ محجوب حتى اكتمال التحقق"}</span></div>{approved&&hasForecast?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500"><tr><th className="px-4 py-3">الشهر</th>{metricLabels.map(m=><th key={m.key} className="px-4 py-3">{m.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{forecast!.forecast.map(p=><tr key={p.month}><td className="px-4 py-4 font-bold">{p.month}</td>{metricLabels.map(m=><td key={m.key} className="px-4 py-4 tabular-nums">{money(p[m.key])}</td>)}</tr>)}</tbody></table></div>:<div className="mt-5 border border-dashed border-slate-300 bg-slate-50 p-7 text-sm leading-7 text-slate-600">يحتاج المحرك إلى {forecast?.minimum_history_months??6} أشهر فعلية منشورة على الأقل، مع تحقق تاريخي كافٍ، قبل عرض أرقام مستقبلية قابلة للاستخدام الإداري.</div>}</section>
   <section className="saas-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><p className="eyebrow">FORECAST VS ACTUAL</p><h2 className="mt-1 font-extrabold">التحقق التاريخي</h2><p className="mt-1 text-sm text-slate-500">Rolling holdout لآخر أشهر فعلية متاحة، مع استبعاد الأشهر المفقودة من الحساب.</p></div>{validation?.validated&&rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-right text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500"><tr><th className="px-4 py-3">الشهر</th><th className="px-4 py-3">المؤشر</th><th className="px-4 py-3">الفعلي</th><th className="px-4 py-3">التنبؤ</th><th className="px-4 py-3">الانحراف</th><th className="px-4 py-3">APE</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.flatMap(r=>metricLabels.map(m=>{const apeKey=m.key==="net_income"?null:m.key;const ape=apeKey?r.ape[apeKey as keyof typeof r.ape]:null;return <tr key={`${r.month}-${m.key}`}><td className="px-4 py-3 font-bold">{r.month}</td><td className="px-4 py-3">{m.label}</td><td className="px-4 py-3 tabular-nums">{money(r.actual[m.key])}</td><td className="px-4 py-3 tabular-nums">{money(r.forecast[m.key])}</td><td className="px-4 py-3 tabular-nums">{money(r.variance[m.key])}</td><td className={`px-4 py-3 font-bold tabular-nums ${ape!=null&&ape>=20?"text-red-700":""}`}>{pct(ape)}</td></tr>}))}</tbody></table></div>:<div className="p-8 text-sm text-slate-500">لا يوجد تحقق تاريخي كافٍ ضمن النطاق والفلاتر الحالية.</div>}</section>
   <section className="saas-card p-5 sm:p-6"><p className="eyebrow">MODEL GOVERNANCE</p><h2 className="mt-1 font-extrabold">المنهجية والحوكمة</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="border border-slate-200 bg-slate-50 p-4 text-sm leading-7"><strong>النموذج:</strong> {forecast?.methodology?.model??validation?.methodology?.model??"—"}<br/><strong>التحقق:</strong> {validation?.methodology?.validation??"—"}<br/><strong>مقياس الخطأ:</strong> {validation?.methodology?.error_metric??"MAPE"}</div><div className="border border-slate-200 bg-slate-50 p-4 text-sm leading-7">المصدر: بيانات مالية <strong>منشورة</strong> فقط.<br/>الأشهر المفقودة لا تُعامل كصفر.<br/>الفلاتر الحالية تُطبق على المحرك والتحقق.<br/>لا توجد قيم AI أو قيم مفترضة مخفية داخل الأرقام.</div></div></section>
   <section className="saas-card p-5 sm:p-6"><p className="eyebrow">ACCURACY BY METRIC</p><h2 className="mt-1 font-extrabold">دقة النموذج حسب المؤشر</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{l:"الإيرادات",v:validation?.metrics.revenue_mape},{l:"مجمل الربح",v:validation?.metrics.gross_profit_mape},{l:"EBITDA",v:validation?.metrics.ebitda_mape},{l:"التدفق التشغيلي",v:validation?.metrics.operating_cash_flow_mape}].map(x=><div key={x.l} className="border border-slate-200 p-4"><p className="text-sm font-bold">{x.l}</p><p className="mt-2 text-xl font-black tabular-nums">{pct(x.v??null)}</p></div>)}</div></section>
  </div>
 </main>;
}
