"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Version = { id: string; name: string; status: string; created_at: string; review_note: string | null };
type Period = { id: string; period_start: string; period_end: string; status: string };
type Account = { id: string; code: string; name: string };
type Line = { id: string; financial_period_id: string; account_id: string; amount_minor: number; notes: string | null };
type Payload = { version: Version | null; periods: Period[]; accounts: Account[]; lines: Line[] };

const statusLabels: Record<string, string> = { draft: "مسودة", submitted: "بانتظار المراجعة", changes_requested: "مطلوب تعديل", approved: "معتمدة", locked: "مقفلة" };
function money(minor: number) { return new Intl.NumberFormat("ar-SA", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(minor / 100); }

export default function ForecastPage() {
  const supabase = getSupabaseBrowserClient();
  const [orgId, setOrgId] = useState<string | null>(null);
  const [payload, setPayload] = useState<Payload>({ version: null, periods: [], accounts: [], lines: [] });
  const [versionId, setVersionId] = useState<string | null>(null);
  const [name, setName] = useState(""); const [periodId, setPeriodId] = useState(""); const [accountId, setAccountId] = useState(""); const [amount, setAmount] = useState(""); const [notes, setNotes] = useState(""); const [reviewNote, setReviewNote] = useState("");
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (organizationId: string, selectedVersionId?: string | null) => {
    setLoading(true); setError(null);
    const { data, error: rpcError } = await supabase.rpc("get_forecast_workspace", { p_organization_id: organizationId, p_planning_version_id: selectedVersionId ?? null });
    if (rpcError) { setError(rpcError.message); setLoading(false); return; }
    const next = (data ?? {}) as Payload;
    setPayload({ version: next.version ?? null, periods: next.periods ?? [], accounts: next.accounts ?? [], lines: next.lines ?? [] }); setVersionId(next.version?.id ?? null); setLoading(false);
  }, [supabase]);

  useEffect(() => { const id = window.sessionStorage.getItem("activeOrganizationId"); if (!id) { setError("لم يتم تحديد الشركة الحالية."); setLoading(false); return; } setOrgId(id); void load(id); }, [load]);
  const total = useMemo(() => payload.lines.reduce((sum, line) => sum + Number(line.amount_minor || 0), 0), [payload.lines]);
  const editable = payload.version?.status === "draft" || payload.version?.status === "changes_requested";
  const periodName = (id: string) => { const p = payload.periods.find((x) => x.id === id); return p ? `${p.period_start} → ${p.period_end}` : id; };
  const accountName = (id: string) => { const a = payload.accounts.find((x) => x.id === id); return a ? `${a.code} — ${a.name}` : id; };

  async function createVersion() { if (!orgId || !name.trim()) return; setBusy(true); setError(null); const { data, error: e } = await supabase.rpc("create_planning_version", { p_organization_id: orgId, p_version_type: "forecast", p_name: name.trim() }); if (e) setError(e.message); else { setName(""); setVersionId(data as string); await load(orgId, data as string); } setBusy(false); }
  async function saveLine() { if (!orgId || !versionId || !periodId || !accountId || amount.trim() === "") { setError("اختر الفترة والحساب وأدخل قيمة التوقع."); return; } const parsed = Number(amount.replace(/,/g, "")); if (!Number.isFinite(parsed)) { setError("قيمة التوقع غير صحيحة."); return; } setBusy(true); setError(null); const { error: e } = await supabase.rpc("upsert_forecast_line", { p_organization_id: orgId, p_planning_version_id: versionId, p_financial_period_id: periodId, p_account_id: accountId, p_amount_minor: Math.round(parsed * 100), p_notes: notes.trim() || null }); if (e) setError(e.message); else { setAmount(""); setNotes(""); await load(orgId, versionId); } setBusy(false); }
  async function deleteLine(id: string) { if (!orgId) return; setBusy(true); setError(null); const { error: e } = await supabase.rpc("delete_forecast_line", { p_organization_id: orgId, p_forecast_line_id: id }); if (e) setError(e.message); else await load(orgId, versionId); setBusy(false); }
  async function submit() { if (!versionId || !orgId) return; setBusy(true); setError(null); const { error: e } = await supabase.rpc("submit_planning_version", { p_planning_version_id: versionId }); if (e) setError(e.message); else await load(orgId, versionId); setBusy(false); }
  async function review(action: "approve" | "changes_requested" | "reject") { if (!versionId || !orgId) return; if (action !== "approve" && !reviewNote.trim()) { setError("اكتب ملاحظة قبل طلب التعديل أو الرفض."); return; } setBusy(true); setError(null); const { error: e } = await supabase.rpc("review_planning_version", { p_planning_version_id: versionId, p_action: action, p_note: reviewNote.trim() || null }); if (e) setError(e.message); else { setReviewNote(""); await load(orgId, versionId); } setBusy(false); }

  return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">03 / FORECAST</p><h1 className="section-title mt-1 text-2xl sm:text-3xl">التوقعات</h1><p className="mt-2 text-sm leading-6 text-slate-500">بناء توقع مالي حسب الفترة والحساب ثم إرساله لمسار الاعتماد.</p></div><div className="border border-slate-200 bg-slate-50 px-4 py-3"><p className="text-[10px] font-bold text-slate-400">TOTAL FORECAST</p><p className="mt-1 text-lg font-black text-slate-950 tabular-nums">{money(total)} ريال</p></div></div></div></header>
    <div className="mx-auto max-w-[1500px] space-y-5 px-4 py-6 sm:px-6 lg:px-8 lg:py-7">
      {error && <div role="alert" className="border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
      <section className="saas-card p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">PLANNING VERSION</p><h2 className="mt-1 font-extrabold text-slate-950">إصدار التوقع</h2><p className="mt-1 text-sm text-slate-500">الإصدار هو الحاوية الرسمية لبيانات التوقع ومسار اعتماده.</p></div>{payload.version && <span className="border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold">{statusLabels[payload.version.status] ?? payload.version.status}</span>}</div>{!payload.version ? <div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={name} onChange={(e) => setName(e.target.value)} className="input flex-1" placeholder="مثال: التوقع المحدث للربع الرابع" /><button disabled={busy || !name.trim()} onClick={() => void createVersion()} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-50">إنشاء التوقع</button></div> : <div className="mt-4 flex flex-wrap items-center gap-3"><p className="font-bold text-slate-950">{payload.version.name}</p>{editable && <button disabled={busy} onClick={() => void submit()} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-50">إرسال للمراجعة</button>}{payload.version.status === "approved" && <span className="border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700">التوقع معتمد</span>}</div>}{payload.version?.review_note && <div className="mt-4 border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-900"><strong>ملاحظة المراجع:</strong> {payload.version.review_note}</div>}</section>
      {payload.version && <>
        <section className="saas-card p-5 sm:p-6"><div className="mb-5"><p className="eyebrow">INPUT</p><h2 className="mt-1 font-extrabold text-slate-950">إضافة بند توقع</h2><p className="mt-1 text-sm text-slate-500">كل بند مرتبط بإصدار التوقع والفترة والحساب داخل نفس الشركة.</p></div>{payload.periods.length === 0 || payload.accounts.length === 0 ? <div className="border border-dashed border-slate-300 bg-slate-50 p-5 text-sm leading-7 text-slate-600">لا يمكن إدخال بنود بعد. يجب أولًا وجود فترات مالية وحسابات للشركة. لم يتم إنشاء بيانات تجريبية تلقائيًا.</div> : <div className="grid gap-3 lg:grid-cols-[1fr_1.4fr_1fr_1fr_auto]"><select disabled={!editable || busy} value={periodId} onChange={(e) => setPeriodId(e.target.value)} className="input"><option value="">اختر الفترة</option>{payload.periods.map((p) => <option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><select disabled={!editable || busy} value={accountId} onChange={(e) => setAccountId(e.target.value)} className="input"><option value="">اختر الحساب</option>{payload.accounts.map((a) => <option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select><input disabled={!editable || busy} value={amount} onChange={(e) => setAmount(e.target.value)} className="input" inputMode="decimal" placeholder="المبلغ بالريال" /><input disabled={!editable || busy} value={notes} onChange={(e) => setNotes(e.target.value)} className="input" placeholder="ملاحظة اختيارية" /><button disabled={!editable || busy} onClick={() => void saveLine()} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:opacity-40">حفظ</button></div>}</section>
        <section className="saas-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><p className="eyebrow">FORECAST LINES</p><h2 className="mt-1 font-extrabold text-slate-950">بنود التوقع</h2><p className="mt-1 text-sm text-slate-500">{payload.lines.length} بند · {money(total)} ريال</p></div>{loading ? <div className="p-8 text-center text-sm text-slate-500">جارٍ التحميل…</div> : payload.lines.length === 0 ? <div className="p-8 text-center text-sm text-slate-500">لم تتم إضافة أي بنود بعد.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500"><tr><th className="px-5 py-3">الفترة</th><th className="px-5 py-3">الحساب</th><th className="px-5 py-3">المبلغ</th><th className="px-5 py-3">ملاحظة</th><th className="px-5 py-3">إجراء</th></tr></thead><tbody className="divide-y divide-slate-100">{payload.lines.map((line) => <tr key={line.id} className="transition hover:bg-slate-50"><td className="px-5 py-4">{periodName(line.financial_period_id)}</td><td className="px-5 py-4 font-semibold">{accountName(line.account_id)}</td><td className="px-5 py-4 font-bold tabular-nums">{money(Number(line.amount_minor))} ريال</td><td className="px-5 py-4 text-slate-500">{line.notes || "—"}</td><td className="px-5 py-4">{editable && <button disabled={busy} onClick={() => void deleteLine(line.id)} className="text-xs font-bold text-red-600 disabled:opacity-40">حذف</button>}</td></tr>)}</tbody></table></div>}</section>
        {payload.version.status === "submitted" && <section className="saas-card p-5 sm:p-6"><p className="eyebrow">REVIEW</p><h2 className="mt-1 font-extrabold text-slate-950">مراجعة التوقع</h2><p className="mt-1 text-sm text-slate-500">متاحة فقط لمن يملك صلاحية الاعتماد أو الرفض وفق سياسة الشركة.</p><textarea value={reviewNote} onChange={(e) => setReviewNote(e.target.value)} className="input mt-4 min-h-[110px]" placeholder="ملاحظة المراجع" /><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void review("approve")} className="min-h-11 bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">اعتماد</button><button disabled={busy} onClick={() => void review("changes_requested")} className="min-h-11 border border-amber-300 bg-amber-50 px-5 py-3 text-sm font-bold text-amber-800 disabled:opacity-50">طلب تعديل</button><button disabled={busy} onClick={() => void review("reject")} className="min-h-11 border border-red-200 bg-red-50 px-5 py-3 text-sm font-bold text-red-700 disabled:opacity-50">رفض</button></div></section>}
      </>}
    </div>
  </main>;
}
