"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Period={id:string;period_start:string;period_end:string;status:string};
type Option={id:string;code:string|null;name:string};
type TrialRow={code:string;name:string;account_type:string|null;statement_type:string|null;statement_section:string|null;statement_subclassification:string|null;opening_debit:number;opening_credit:number;period_debit:number;period_credit:number;closing_debit:number;closing_credit:number};
type TrialBalance={period_start:string;period_end:string;period_status:string;fiscal_year_start:string;row_count:number;total_period_debit:number;total_period_credit:number;period_difference:number;total_opening_debit:number;total_opening_credit:number;opening_difference:number;total_closing_debit:number;total_closing_credit:number;closing_difference:number;rows:TrialRow[]};
const money=(v:number)=>(Number(v||0)/100).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString("ar-SA",{year:"numeric",month:"long",day:"numeric"});

export default function TrialBalancePage(){
 const supabase=getSupabaseBrowserClient(); const [org,setOrg]=useState(""); const [periods,setPeriods]=useState<Period[]>([]); const [period,setPeriod]=useState(""); const [data,setData]=useState<TrialBalance|null>(null); const [options,setOptions]=useState<any>({}); const [advanced,setAdvanced]=useState(false); const [query,setQuery]=useState(""); const [filters,setFilters]=useState({branch:"",department:"",cost_center:"",region:"",product:"",project:"",account:""}); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{const id=window.sessionStorage.getItem("activeOrganizationId")||window.localStorage.getItem("activeOrganizationId")||"";setOrg(id);if(!id){setLoading(false);setError("لم يتم تحديد مساحة عمل.");return;}void Promise.all([supabase.from("financial_periods").select("id,period_start,period_end,status").eq("organization_id",id).order("period_start",{ascending:false}),supabase.rpc("get_reporting_filter_options",{p_organization_id:id})]).then(([p,f])=>{if(p.error)setError(p.error.message);const rows=(p.data||[]) as Period[];setPeriods(rows);if(rows[0])setPeriod(rows[0].id);if(!f.error)setOptions(f.data||{});setLoading(false);});},[]);
 const activeFilterCount=Object.values(filters).filter(Boolean).length; const accounts=(options.accounts||[]) as any[]; const filteredAccounts=useMemo(()=>{const q=query.trim().toLocaleLowerCase("ar");return q?accounts.filter(a=>`${a.code} ${a.name}`.toLocaleLowerCase("ar").includes(q)):accounts;},[accounts,query]);
 async function load(){if(!org||!period)return;setRunning(true);setError("");const {data:result,error:e}=await supabase.rpc("get_trial_balance",{p_organization_id:org,p_period_id:period,p_branch_id:filters.branch||null,p_department_id:filters.department||null,p_cost_center_id:filters.cost_center||null,p_region_id:filters.region||null,p_product_id:filters.product||null,p_project_id:filters.project||null,p_account_id:filters.account||null});if(e){setError(e.message);setData(null);}else setData(result as TrialBalance);setRunning(false);}
 const clear=()=>{setFilters({branch:"",department:"",cost_center:"",region:"",product:"",project:"",account:""});setData(null);};
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] text-[#172033]"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><a href="/workspace" className="text-sm font-semibold text-slate-500">العودة لمساحة العمل</a><div><p className="text-[10px] font-bold tracking-[.14em] text-slate-400">FINANCIAL MODEL</p><h1 className="mt-1 font-bold text-slate-950">ميزان المراجعة</h1></div></div></header><section className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8"><div className="border-b border-slate-200 pb-6"><p className="text-xs font-bold text-slate-400">Trial Balance</p><h2 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">ميزان المراجعة الفعلي</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">واجهة فلترة شبيهة بـ Odoo مع فلاتر متقدمة، مع عرض الافتتاحي وحركة الفترة والختامي في جدول واحد.</p></div>
 <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.5fr_1fr_auto]"><select value={period} onChange={e=>{setPeriod(e.target.value);setData(null)}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold">{periods.map(p=><option key={p.id} value={p.id}>{date(p.period_start)} — {date(p.period_end)}</option>)}</select><select value={filters.branch} onChange={e=>{setFilters({...filters,branch:e.target.value});setData(null)}} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="">كل الفروع</option>{(options.branches||[]).map((x:Option)=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select><div className="flex gap-2"><button onClick={()=>setAdvanced(v=>!v)} className={`min-h-11 flex-1 rounded-xl border px-4 text-sm font-bold ${advanced||activeFilterCount?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white"}`}>الفلاتر {activeFilterCount?`(${activeFilterCount})`:""}</button><button disabled={!period||running} onClick={load} className="min-h-11 rounded-xl bg-slate-950 px-5 text-sm font-bold text-white disabled:opacity-50">{running?"جاري...":"تطبيق"}</button></div></div>
 {activeFilterCount>0&&<div className="mt-3 flex flex-wrap gap-2">{Object.entries(filters).filter(([,v])=>v).map(([k])=><button key={k} onClick={()=>setFilters({...filters,[k]:""})} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold">{({branch:"الفرع",department:"الإدارة",cost_center:"مركز التكلفة",region:"المنطقة",product:"المنتج",project:"المشروع",account:"الحساب"} as any)[k]} ×</button>)}<button onClick={clear} className="text-xs font-bold text-red-600">مسح الكل</button></div>}
 {advanced&&<div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2 lg:grid-cols-4"><Select label="الإدارة" value={filters.department} setValue={v=>setFilters({...filters,department:v})} items={options.departments}/><Select label="مركز التكلفة" value={filters.cost_center} setValue={v=>setFilters({...filters,cost_center:v})} items={options.cost_centers}/><Select label="المنطقة" value={filters.region} setValue={v=>setFilters({...filters,region:v})} items={options.regions}/><Select label="المنتج" value={filters.product} setValue={v=>setFilters({...filters,product:v})} items={options.products}/><Select label="المشروع" value={filters.project} setValue={v=>setFilters({...filters,project:v})} items={options.projects}/><div><label className="text-xs font-bold text-slate-500">الحساب</label><input value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setFilters({...filters,account:""})}} placeholder="ابحث بالكود أو الاسم" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"/>{query&&<div className="mt-1 max-h-40 overflow-auto rounded-xl border bg-white">{filteredAccounts.slice(0,20).map(a=><button key={a.id} onClick={()=>{setFilters({...filters,account:a.id});setQuery(`${a.code} — ${a.name}`)}} className="block w-full px-3 py-2 text-right text-xs hover:bg-slate-50">{a.code} — {a.name}</button>)}</div>}</div></div>}
 </div>
 {loading?<div className="mt-7 rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">جاري تحميل الفترات...</div>:error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>:!data?<div className="mt-7 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">اختر الفترة ثم اضغط تطبيق لعرض الميزان.</div>:<><div className="mt-6 grid gap-3 sm:grid-cols-3 xl:grid-cols-6"><Metric label="مدين الفترة" value={data.total_period_debit}/><Metric label="دائن الفترة" value={data.total_period_credit}/><Metric label="فرق الفترة" value={data.period_difference} good={data.period_difference===0}/><Metric label="فرق الافتتاح" value={data.opening_difference} good={data.opening_difference===0}/><Metric label="فرق الإغلاق" value={data.closing_difference} good={data.closing_difference===0}/><Metric label="عدد الحسابات" value={data.row_count} raw/></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-right text-sm"><thead className="sticky top-0 z-10 border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="sticky right-0 bg-slate-50 px-4 py-3">الحساب</th><th className="px-4 py-3">التصنيف</th><th className="px-4 py-3">افتتاحي مدين</th><th className="px-4 py-3">افتتاحي دائن</th><th className="px-4 py-3">حركة مدين</th><th className="px-4 py-3">حركة دائن</th><th className="px-4 py-3">ختامي مدين</th><th className="px-4 py-3">ختامي دائن</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.code} className="border-b border-slate-100 hover:bg-slate-50"><td className="sticky right-0 bg-white px-4 py-3 font-semibold text-slate-900">{r.code} — {r.name}</td><td className="px-4 py-3 text-xs text-slate-500">{r.statement_subclassification||r.account_type||"غير مصنف"}</td><td className="px-4 py-3 tabular-nums">{money(r.opening_debit)}</td><td className="px-4 py-3 tabular-nums">{money(r.opening_credit)}</td><td className="px-4 py-3 tabular-nums">{money(r.period_debit)}</td><td className="px-4 py-3 tabular-nums">{money(r.period_credit)}</td><td className="px-4 py-3 tabular-nums">{money(r.closing_debit)}</td><td className="px-4 py-3 tabular-nums">{money(r.closing_credit)}</td></tr>)}</tbody></table></div><div className="border-t border-slate-200 px-4 py-4 text-xs font-semibold text-slate-500">السنة المالية تبدأ في {date(data.fiscal_year_start)} · البيانات فعلية ومنشورة فقط</div></div></>}</section></main>
}
function Select({label,value,setValue,items}:{label:string;value:string;setValue:(v:string)=>void;items:Option[]}){return <label><span className="text-xs font-bold text-slate-500">{label}</span><select value={value} onChange={e=>setValue(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">الكل</option>{(items||[]).map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select></label>}
function Metric({label,value,good=true,raw=false}:{label:string;value:number;good?:boolean;raw?:boolean}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[11px] font-bold text-slate-400">{label}</p><p className={`mt-2 text-lg font-bold ${good?"text-slate-950":"text-red-700"}`}>{raw?Math.round(Number(value||0)):money(value)}</p></div>}
