"use client";
import { useEffect,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
const months=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
type CompanyProfile={id:string;name:string;legal_name:string|null;industry:string|null;city:string|null;base_currency:string;fiscal_year_start_month:number};
export default function EditCompanyPage(){const router=useRouter(),params=useSearchParams(),id=params.get("id");const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");const [name,setName]=useState(""),[legalName,setLegalName]=useState(""),[industry,setIndustry]=useState(""),[city,setCity]=useState(""),[currency,setCurrency]=useState("SAR"),[fiscalMonth,setFiscalMonth]=useState("1");
useEffect(()=>{let active=true;async function load(){if(!id){setError("معرّف الشركة غير موجود.");setLoading(false);return;}const s=getSupabaseBrowserClient();const {data:userData}=await s.auth.getUser();if(!userData.user){router.replace(`/login?next=${encodeURIComponent(`/start/edit?id=${id}`)}`);return;}const {data,error:e}=await s.rpc("get_workspace_profile",{p_organization_id:id});if(e){if(active){setError(e.message||"تعذر تحميل بيانات الشركة.");setLoading(false);}return;}const c=(data?.[0]) as CompanyProfile|undefined;if(!c){if(active){setError("الشركة غير موجودة أو لا تملك صلاحية الوصول إليها.");setLoading(false);}return;}setName(c.name||"");setLegalName(c.legal_name||"");setIndustry(c.industry||"");setCity(c.city||"");setCurrency(c.base_currency||"SAR");setFiscalMonth(String(c.fiscal_year_start_month||1));setLoading(false);}void load();return()=>{active=false};},[id,router]);
async function save(){if(!id||!name.trim()){setError("اكتب اسم الشركة أولًا.");return;}setSaving(true);setError("");try{const s=getSupabaseBrowserClient();const {data,error:e}=await s.rpc("update_workspace_profile",{p_organization_id:id,p_name:name.trim(),p_legal_name:legalName.trim(),p_industry:industry.trim(),p_city:city.trim(),p_base_currency:currency,p_fiscal_year_start_month:Number(fiscalMonth)});if(e)throw e;if(!data)throw new Error("تعذر حفظ بيانات الشركة.");router.replace("/start");router.refresh();}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ بيانات الشركة.");}finally{setSaving(false);}}
if(loading)return <main className="min-h-screen bg-[#f7f8fa] p-8 text-[#172033]" dir="rtl"><div className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-8 text-center">جارٍ تحميل بيانات الشركة…</div></main>;
return <main className="min-h-screen bg-[#f7f8fa] px-4 py-6 text-[#172033] sm:px-6 lg:px-10" dir="rtl"><div className="mx-auto w-full max-w-5xl"><header className="flex items-center justify-between border-b border-slate-200 pb-5"><button type="button" onClick={()=>router.push("/start")} className="text-sm font-semibold text-slate-500 hover:text-slate-950">← العودة إلى شركاتي</button><div className="text-right"><p className="text-xs font-bold tracking-[0.16em] text-slate-400">COMPANY SETTINGS</p><p className="mt-1 font-bold text-slate-950">تعديل الشركة</p></div></header><section className="mx-auto max-w-3xl py-8 sm:py-12"><div className="mb-8"><p className="text-xs font-bold tracking-[0.14em] text-slate-400">EDIT COMPANY</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">بيانات الشركة</h1><p className="mt-3 text-sm leading-7 text-slate-500">حدّث البيانات الأساسية للشركة. الصلاحية تُتحقق من قاعدة البيانات عند الحفظ.</p></div><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="اسم الشركة *"><input className="input" value={name} onChange={e=>setName(e.target.value)} autoFocus /></Field><Field label="الاسم القانوني"><input className="input" value={legalName} onChange={e=>setLegalName(e.target.value)} /></Field><Field label="القطاع"><input className="input" value={industry} onChange={e=>setIndustry(e.target.value)} /></Field><Field label="المدينة"><input className="input" value={city} onChange={e=>setCity(e.target.value)} /></Field><Field label="العملة الأساسية"><select className="input" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="SAR">ريال سعودي (SAR)</option><option value="AED">درهم إماراتي (AED)</option><option value="USD">دولار أمريكي (USD)</option><option value="EGP">جنيه مصري (EGP)</option></select></Field><Field label="بداية السنة المالية"><select className="input" value={fiscalMonth} onChange={e=>setFiscalMonth(e.target.value)}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></Field></div>{error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm leading-6 text-red-700" role="alert">{error}</div>}<div className="mt-8 flex flex-col-reverse gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:justify-end"><button type="button" disabled={saving} onClick={()=>router.push("/start")} className="rounded-xl border border-slate-200 px-6 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50">إلغاء</button><button type="button" disabled={saving||!name.trim()} onClick={()=>void save()} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-bold text-white hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50">{saving?"جارٍ الحفظ…":"حفظ التعديلات"}</button></div></section></section></div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>}
